### ISSUE TITLE
run_ref_gds.sh script is outdated

### ISSUE THREAD

**Issue by matzipan** [nasa/fprime#100]
Following the readme at https://github.com/nasa/fprime/blob/master/Gds/README.md#gds-gui-usage, I get the following error:

```
$ ./Ref/scripts/run_ref_gds.sh 
usage: run_deployment.py [-h] [-d DEPLOY] [-l LOGS] [--log-directly]
                         [--tts-port TTS_PORT] [--tts-addr TTS_ADDR]
                         [-g {none,html}] [--dictionary DICTIONARY]
                         [-c CONFIG] [--comm-adapter {ip}] [-n] [--app APP]
run_deployment.py: error: argument -g/--gui: invalid choice: 'wx' (choose from 'none', 'html')
```

I'm assuming this is due to the recent change to the HTML gds. 

I would gladly submit a PR as soon as I'm told this is `html` is intended.

**Comment by matzipan** [comment]
I have edited the original report to reflect that the second error was due to me not having built the reference application.

**Comment by LeStarch** [comment]
Ok, yes.  Once you build Ref and run `make install` then all you need to do is choose `html` as the GUI.   You can still use wx, but the installation is often complicated, so we removed it as a default from the pacakge.

**Comment by LeStarch** [comment]
Honestly, we probably need to update that whole readme section.  I'll look into that to.
