### ISSUE TITLE
No assertion when ping port is not connected

### ISSUE THREAD

**Issue by rawinza555** [nasa/fprime#1006]
| | |
|:---|:---|
|**_F´ Version_**| 2.0.0|
|**_Affected Component_**| Health?  |
---
## Problem Description

Based on this [discussion](https://github.com/nasa/fprime/discussions/1002), turned out we can compile and run the flight software even when the component that doesn't have a ping port are registered to `Health` is set in ping entries table in `topology.cpp`

## How to Reproduce

1. add a component that doesn't have a ping port attached to ping entries in `topology.cpp`
2. compile and run it

## Expected Behavior

There should be no assertion until after you execute the binary file. FATAL 122 is handled slightly afterward.

**Comment by LeStarch** [comment]
Should be fixed by FPP in that FPP wouldn't allow the improper connection.
