### ISSUE TITLE
Getting started guide references pip_required_gui.txt which doesn't exist anymore

### ISSUE THREAD

**Issue by matzipan** [nasa/fprime#101]
The guide contains this line:
```
pip install -r fprime/mk/python/pip_required_gui.txt
```

But the `pip_required_gui.txt` does not exist anymore.

**Comment by matzipan** [comment]
I think the User Guide also contains this mistake.

**Comment by LeStarch** [comment]
Agreed.  Thanks for pointing this out!

**Comment by LeStarch** [comment]
This getting started has been rewritten for python packages and CMake.
