### ISSUE TITLE
gen_make for reference application does not build successfully

### ISSUE THREAD

**Issue by matzipan** [nasa/fprime#102]
Hi, 

In order to be able to build the make files for the reference applications I had to apply the following patch:
```
diff --git a/mk/configs/modules/modules.mk b/mk/configs/modules/modules.mk
index 0a7b67ee..454b01cd 100644
--- a/mk/configs/modules/modules.mk
+++ b/mk/configs/modules/modules.mk
@@ -45,15 +45,11 @@ SVC_MODULES := \
        Svc/CmdDispatcher \
        Svc/CmdSequencer \
        Svc/Seq \
-       Svc/GndIf \
        Svc/ActiveRateGroup \
        Svc/RateGroupDriver \
        Svc/Sched \
        Svc/ComLogger \
-       Svc/SocketGndIf \
-       Svc/BuffGndSockIf \
        Svc/TlmChan \
-       Svc/PassiveTextLogger \
        Svc/PassiveConsoleTextLogger \
        Svc/Time \
        Svc/Cycle \
```

Otherwise, `make gen_make` would exit with the following message:
```
**Error: File Svc/GndIf/mod.mk does not exist.**
Command exited with non-zero status 255
Build Time: 0:00.03
make: *** [/home/andrei/Workspace/fprime/mk/makefiles/deployment_makefile.mk:107: gen_make] Error 255
```

I'm thinking this might not be correct behavior to obtain a full build though, as later on, when I call `make`, I get:

```
In file included from /home/andrei/Workspace/fprime/Ref/Top/Components.hpp:8,
                 from /home/andrei/Workspace/fprime/Ref/Top/RefTopologyAppAc.cpp:2:
/home/andrei/Workspace/fprime/Svc/PassiveConsoleTextLogger/ConsoleTextLoggerImpl.hpp:4:10: fatal error: Svc/PassiveConsoleTextLogger/PassiveTextLoggerComponentAc.hpp: No such file or directory
 #include <Svc/PassiveConsoleTextLogger/PassiveTextLoggerComponentAc.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /home/andrei/Workspace/fprime/Ref/Top/Components.hpp:8,
                 from /home/andrei/Workspace/fprime/Ref/Top/Topology.cpp:1:
/home/andrei/Workspace/fprime/Svc/PassiveConsoleTextLogger/ConsoleTextLoggerImpl.hpp:4:10: fatal error: Svc/PassiveConsoleTextLogger/PassiveTextLoggerComponentAc.hpp: No such file or directory
 #include <Svc/PassiveConsoleTextLogger/PassiveTextLoggerComponentAc.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [/home/andrei/Workspace/fprime/mk/makefiles/bin_targets.mk:19: /home/andrei/Workspace/fprime/Ref/Top/linux-linux-x86-debug-gnu-bin/RefTopologyAppAc.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [/home/andrei/Workspace/fprime/mk/makefiles/bin_targets.mk:14: /home/andrei/Workspace/fprime/Ref/Top/linux-linux-x86-debug-gnu-bin/Topology.o] Error 1
In file included from /home/andrei/Workspace/fprime/Ref/Top/Components.hpp:8,
                 from /home/andrei/Workspace/fprime/Ref/Top/Main.cpp:5:
/home/andrei/Workspace/fprime/Svc/PassiveConsoleTextLogger/ConsoleTextLoggerImpl.hpp:4:10: fatal error: Svc/PassiveConsoleTextLogger/PassiveTextLoggerComponentAc.hpp: No such file or directory
 #include <Svc/PassiveConsoleTextLogger/PassiveTextLoggerComponentAc.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [/home/andrei/Workspace/fprime/mk/makefiles/bin_targets.mk:9: /home/andrei/Workspace/fprime/Ref/Top/linux-linux-x86-debug-gnu-bin/Main.o] Error 1
make[1]: Leaving directory '/home/andrei/Workspace/fprime/Ref'
Command exited with non-zero status 2
Build Time: 0:00.82
make: *** [/home/andrei/Workspace/fprime/mk/makefiles/deployment_makefile.mk:52: LINUX] Error 2
```

**Comment by LeStarch** [comment]
@matzipan it looks like the older make system has diverged from the CMake one.  Your patch is correct, but we should add in:

```
   Svc/GroundInterface
```

Still looking into the compile errors.

**Comment by david-kooi** [comment]
Having a similar issue with the RPI demo.

`compilation terminated.
/home/david/Workspace/fprime/mk/makefiles/bin_targets.mk:12848: recipe for target '/home/david/Workspace/fprime/RPI/Top/raspian-raspian-arm-debug-gnu-bin/Topology.o' failed
make[1]: *** [/home/david/Workspace/fprime/RPI/Top/raspian-raspian-arm-debug-gnu-bin/Topology.o] Error 1
In file included from /home/david/Workspace/fprime/RPI/Top/Components.hpp:9:0,
                 from /home/david/Workspace/fprime/RPI/Top/RPITopologyAppAc.cpp:2:
/home/david/Workspace/fprime/Svc/PassiveConsoleTextLogger/ConsoleTextLoggerImpl.hpp:4:73: fatal error: Svc/PassiveConsoleTextLogger/PassiveTextLoggerComponentAc.hpp: No such file or directory
 #include <Svc/PassiveConsoleTextLogger/PassiveTextLoggerComponentAc.hpp>
                                                                         ^
compilation terminated.
/home/david/Workspace/fprime/mk/makefiles/bin_targets.mk:12853: recipe for target '/home/david/Workspace/fprime/RPI/Top/raspian-raspian-arm-debug-gnu-bin/RPITopologyAppAc.o' failed
make[1]: *** [/home/david/Workspace/fprime/RPI/Top/raspian-raspian-arm-debug-gnu-bin/RPITopologyAppAc.o] Error 1
make[1]: Leaving directory '/home/david/Workspace/fprime/RPI'
Command exited with non-zero status 2
Build Time: 0:00.57
Makefile:20: recipe for target 'rpi_cross' failed
make: *** [rpi_cross] Error 2
`

**Comment by LeStarch** [comment]
@timcanham is this fixed?

**Comment by LeStarch** [comment]
Fixed by @timcanham , thanks!
