### ISSUE TITLE
Fw:Logger API does not work for floating point or string args, or possibly large integers

### ISSUE THREAD

**Issue by martyvona** [nasa/fprime#1055]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  Fw::Logger |
---
## Problem Description

Currently the Fw::Logger API takes up to 10 arguments which are all of type POINTER_CAST, an unsigned integer type equal to the platform pointer width, e.g. U64 on a 64 bit platform.

Also, the Fw::Logger API takes a printf style format string, and the current imlementation of Os::Log actually calls the platform's printf() implementation.

There are several issues with this setup, mainly for floating point argument types, but also for C-style strings, and possibly some of the wider integer types depending on the platform.

This is related to but not the same as #549.

Consider what currently happens when using the Os::Log implementation of Fw::Logger with a floating point argument:
1. The compiler implicitly converts the floating point value to a POINTER_CAST integer when the log() call is made.  The implementation of log() then calls printf() uses va_arg() to fetch the value to be formatted. va_arg() is opaque and implementation dependent, but apparently in many modern architectures, its behavior often differs for floating point types which are expected to be stored in a separate register bank than other types of arguments in many common circumstances. Thus va_arg() will typically fetch the value to be formatted from a floating point register, but that register will be uninitialized because the actual function call had only integer arguments.
1. passing a floating point value to Fw::Logger::log() would implictly coerce coerce the value to the POINTER_CAST integer type, dropping the fractional part (unless compiling with something like -Wconversion)
1. there is no provision for ensuring that the sizeof() the POINTER_CAST integer type used by Fw::Logger::log() is sufficiently large to pass all 4 bytes of an IEEE754 float (but on most modern architectures it probably would have been) or all 8 bytes of an IEEE754 double

The issue with string args is that the compiler won't implicitly convert `const char *` to POINTER_CAST, though that could be worked around with an explicit cast.

The issue with wide integers is that on some platforms the width of POINTER_CAST may be narrower than the width of some integer types, e.g. on a 32 bit platform POINTER_CAST might be 4 bytes which is insufficient to store e.g. int64_t.

Given that the varargs mechanism itself may be disallowed in some flight software rules, problem 1 with floating point arguments could be resolved by replacing the underlying call to printf() with a custom implementation of printf() style formatting that has a limited max number of args, without using va_arg().

The remainder of the issues could be resolved by not using POINTER_CAST as the log argument type, but rather something like a LogArg class that can hold a value of any of the POD types, with appropriate explicit (or implicit, where allowed by FSW rules) conversions from the POD types.

**Comment by thomas-bc** [comment]
Fixed by latest refactor
