### ISSUE TITLE
RPI Tutorial: Failed to uplink and open socket

### ISSUE THREAD

**Issue by juliannerice** [nasa/fprime#1060]
| | |
|:---|:---|
|**_2.0.0_**| |
|**_RPI Tutorial_**|   |
---
## Problem Description

After following the RPI Demo Tutorial, when trying to connect between the GUI and RPI every command uplink fails. Exiting the 
GUI results in a message that the socket at 0.0.0.0:50000 failed to open. 
![Screenshot from 2021-09-22 14-11-36](https://user-images.githubusercontent.com/89213755/134398591-ae7918f9-f3dc-4e00-a0c6-a52d98f0de79.png)

## How to Reproduce

1. Follow RPI Tutorial
2. Use command _fprime-gds -n_ instead of _./scripts/run_rpi_cross.sh_ to launch GUI
3. Send a command in the GUI
4. Exit GUI in the terminal

## Expected Behavior
After sending a command in the GUI, the uplink should fail to send the respective number of bytes of data after 3 retries. When exiting the GUI, an error should appear: _Failed to open socket at 0.0.0.0:50000, retrying: OSError: [Errno 22] Invalid argument_

**Comment by timcanham** [comment]
@juliannerice Have you check firewall settings? The ports might be blocked.

**Comment by juliannerice** [comment]
Hi there! I have checked the firewall settings and none of the respective ports should be blocked. It's weird because I got it to work a couple times, but it hasn't been consistent.

**Comment by LeStarch** [comment]
We haven't been able to reproduce, but this kind of inconsistency usually means firewall or router settings.
