### ISSUE TITLE
CMake documentation references tasks which do not exist

### ISSUE THREAD

**Issue by matzipan** [nasa/fprime#107]
In the CMake [documentation section about building deployments](https://github.com/nasa/fprime/tree/master/cmake#building-deployments-iterated-on-change), the documentation references the command `make check`, which I cannot find the final CMake build. Perhaps it's a remnant from the past?

**Comment by LeStarch** [comment]
This "make check" target is now in the "Testing" build variant.  Need to update documentation.

**Comment by LeStarch** [comment]
Should be fixed.
