### ISSUE TITLE
Unsafe Array Creation

### ISSUE THREAD

**Issue by DentOpt** [nasa/fprime#1137]
|**_1.5.3, 2.0.1_**| |
|**_All_**|   |
---
## Problem Description

The autogenerated return function for array values, does not appear to be safe. 

## How to Reproduce

[/Types/Vector3DSerializableAi.xml](/Types/Vector3DSerializableAi.xml)

```
<serializable namespace="Types" name="Vector3D">
    <comment>
    Vector class for description of 3D vectors
    </comment>
    <members>
        <member name="vec" type="F32" size="3"/>
    </members>
</serializable>
```
generates the interface 

[build-fprime-automatic-native/Types/Vector3DSerializableAc.cpp](build-fprime-automatic-native/Types/Vector3DSerializableAc.cpp)

```
const F32* Vector3D::getvec(NATIVE_INT_TYPE& size) {
    size = 3;
    return this->m_vec;
}
```
To get the array values the interface returns only a raw pointer. 
This leads to undefined behavior (if values are not immediately stored, interrupts happening, etc.).

```
Types::Vector3d a;
Types::Vector3d b;
...
const F32 *vec1 = a.getvec(3);
const F32 *vec2 = b.getvec(3);
```

## Expected Behavior

Getter interface should provide a reference interface to ensure safe allocation.
void get(F32 & return).

**Comment by LeStarch** [comment]
@bocchino was this fixed by the new array autocoding?  If so, would you close this?

**Comment by bocchino** [comment]
Yes, this is fixed:
* As of FPP v1.1.0, we have FPP-to-C++ code generation for structs a.k.a. SerializableAc.cpp files
* In the FPP-generated code the getter method for a member array returns a const or non-const reference to the array type. The array size is encoded in the return type. No raw pointers are returned.
