### ISSUE TITLE
Add Missing FPP Models

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#1144]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

We are missing FPP models for the following items:

## Drv Items
- [x] ./Drv/GpioDriverPorts/GpioReadPortAi.xml
- [x]  ./Drv/GpioDriverPorts/GpioWritePortAi.xml
- [x] ./Drv/SerialDriverPorts/SerialWritePortAi.xml
- [x] ./Drv/SerialDriverPorts/SerialReadPortAi.xml
- [x] ./Drv/LinuxSpiDriver/LinuxSpiDriverComponentAi.xml
- [x] ./Drv/LinuxI2cDriver/LinuxI2cDriverComponentAi.xml
- [x] ./Drv/I2cDriverPorts/I2cWriteReadPortAi.xml
- [x] ./Drv/I2cDriverPorts/I2cPortAi.xml
- [x] ./Drv/I2cDriverPorts/I2cStatusEnumAi.xml
- [x] ./Drv/LinuxGpioDriver/LinuxGpioDriverComponentAi.xml
- [x] ./Drv/SocketIpDriver/SocketIpDriverComponentAi.xml -- Should we remove this component?  It has been replaced
- [x] ./Drv/SpiDriverPorts/SpiReadWritePortAi.xml
- [x] ./Drv/LinuxSerialDriver/LinuxSerialDriverComponentAi.xml

## RPI Example. Do we want to update this for v3.0.0?
- [x] ./RPI/Top/RPITopologyAppAi.xml
- [x] ./RPI/RpiDemo/RpiDemoComponentAi.xml

## Svc Items
- [x] ./Svc/TlmPacketizer/TlmPacketizerComponentAi.xml -- Should we ask @timcanham to update this?

**Comment by bocchino** [comment]
I vote for removing SocketIpDriver at this time.
