### ISSUE TITLE
Upgrade Tutorials to Reference FPP

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#1186]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

Update GPS and other tutorials to reference FPP.

**Comment by thomas-bc** [comment]
@LeStarch with our new [Tutorials page](https://nasa.github.io/fprime/Tutorials/README.html) and the discontinuation of the GPS tutorial, I think this issue can be closed? Feel free to reopen if you see more to it.
