### ISSUE TITLE
README.md cluttered with release notes

### ISSUE THREAD

**Issue by ThibFrgsGmz** [nasa/fprime#1190]
| | |
|:---|:---|
|**_F´ Version_**| devel |
|**_Affected Component_**|  README.md |
---
## Problem Description

The release notes are starting to clutter the project's README.md file.

## How to Reproduce

Successfully navigate to the bottom of the release notes section of the README.md file. 😀

## Expected Behavior

I think of several ways to make it more digestible. We should empty the section by exporting the information elsewhere and redirecting the reader to that new location. The section would only include a link to the change log and a high-level summary, which would only be updated when there are major changes.

For the centralized change history, I think we should redirect to https://github.com/nasa/fprime/releases. Another option is to copy/paste the section into a new file called CHANGELOG.md in the root directory of the project.

## Miscellaneous

I also recommend renaming the "F´ Release Notes" to simply "Release Notes" because including the project name here is unnecessary.

**Comment by ThibFrgsGmz** [comment]
When I compare it to other popular Open Source repositories, I notice that they don't have a "Release Notes" section in their README.

- React from Facebook https://github.com/facebook/react
- Rust language https://github.com/rust-lang/rust
- Vuejs https://github.com/vuejs/vue

They let the user to go directly to the "Releases" section of the GitHub project to obtain the necessary information.

So I'm wondering if we should just leave the Release Notes section out of the README.

**Comment by LeStarch** [comment]
I think we'd prefer to use the `CHANGELOG.md` file and for now, we can track that data there.   Release notes are quite nice, but it is also nice to have this information in the repository directly so moving the items out to a new file would achieve this balance and clean up the README.md.

I am going to mark this as an "Easy First Issue" and "Documentation".
