### ISSUE TITLE
Create reference sub-repo for testing

### ISSUE THREAD

**Issue by timcanham** [nasa/fprime#1221]
| | |
|:---|:---|
|**_F´ Version_**| V3.0 |
|**_Affected Component_**| all |
---
## Feature Description

Create a reference deployment (probably in https://github.com/fprime-community) that includes fprime as a sub-repo. That could help detect issues like https://github.com/nasa/fprime/pull/1220. This repo would be built and tested for each release of F Prime. Suggestion would be to reproduce the `Ref` app with another name. It could include all the components from the F Prime subrepo.

## Rationale

Help find errors when using F Prime as a subrepo.

**Comment by LeStarch** [comment]
We have a Ref repo, it just isn't maintained. We should update it, and add the build to CI.

**Comment by Joshua-Anderson** [comment]
Does the GPS app count? https://github.com/fprime-community/gps-tutorial

**Comment by Joshua-Anderson** [comment]
We already have testing F' to make sure the gps-tutorial builds

**Comment by LeStarch** [comment]
We need to add the `separated-project-example` repo into CI in the same way `gps-tutorial` is done.

**Comment by LeStarch** [comment]
Hurray system reference!  **Note:** currently the build is manual, but it exists.
