### ISSUE TITLE
Intermittent UT failure in Drv::TcpServer

### ISSUE THREAD

**Issue by kevin-f-ortega** [nasa/fprime#1290]
| | |
|:---|:---|
|**_F´ Version_**| v3.0.0 |
|**_Affected Component_**|  Drv::TcpServer |
---
## Problem Description

Intermittent unit test failure in Drv::TcpServer when running `fprime-util  check native --all --jobs 24`

## How to Reproduce

1. `cd <deployment-directory>`
2. `fprime-util check native --all --jobs 24`

## Expected Behavior

I expect Drv::TcpServer's UTs to always pass.

**Comment by kevin-f-ortega** [comment]
This happened with `Drv::TcpClient` too.

**Comment by kevin-f-ortega** [comment]
Drv_p_Tcp_test too

**Comment by LeStarch** [comment]
Does this problem persist when running:

```
fprime-util check native --all --jobs 1
```

**Comment by LeStarch** [comment]
If errors persist, please post them here.

**Comment by LeStarch** [comment]
No reproduction reported.  Closing.  Reopen if specific reproductions available.
