### ISSUE TITLE
MagicDraw 

### ISSUE THREAD

**Issue by lchomas** [nasa/fprime#13]
I'm trying to open the various MagicDraw files in the repo and I keep getting an error that the SSCAEProjectUsageInegrityProfile.mdzip is missing.  I've tried searching around manually and can't find it either.  Is this really missing or am I overlooking it?

**Comment by genemerewether** [comment]
That file is not needed - I don't have or use it. Just click "No" when you're prompted to find it manually.

Then, you'll get another prompt about it not being found and asking if you want to launch Resource/Plugin Manager. Click "Cancel" there and the MagicDraw file should finish loading.

You may need to set the `ISF.dir` path variable (MagicDraw (on Mac)->Preferences->Path Variables) to the root directory of the repository, but that is unrelated to this error.

**Comment by lchomas** [comment]
Thank you!
