### ISSUE TITLE
Error in directions in INSTALL.md

### ISSUE THREAD

**Issue by aaronbuchwald** [nasa/fprime#132]
https://github.com/nasa/fprime/blob/master/docs/INSTALL.md
After completing all of the instructions on this page, the final command to see if everything was successfully installed seems to be failing. It seems that the command in the documentation is not actually one of the options to use for fprime-util. I am trying to run:
```fprime-util -g html -d <path/to/fprime/checkout>/Ref```

However, when I run this I see the following result
<img width="1378" alt="Screen Shot 2020-01-26 at 2 44 59 PM" src="https://user-images.githubusercontent.com/24684335/73140758-6b4a2400-404a-11ea-9c60-c954accf2770.png">

**Comment by LeStarch** [comment]
@aaronbuchwald good catch.  Yes, the GDS is a separate command.  I have updated the documentation for master.  Thanks!

**Comment by aaronbuchwald** [comment]
Thanks for the quick fix!
