### ISSUE TITLE
Segmentation fault when running RPI demo

### ISSUE THREAD

**Issue by aaronbuchwald** [nasa/fprime#135]
After completing the RPI demo step by step: https://github.com/nasa/fprime/blob/master/RPI/README.md

I get an immediate segmentation fault error when running the RPI binary on the raspberry pi. Ground station is running successfully when I do this and does not register any messages/telemetry from the RPI. Here is the output:

<img width="1226" alt="Screen Shot 2020-01-30 at 4 55 20 PM" src="https://user-images.githubusercontent.com/24684335/73494130-f8aab280-4381-11ea-94aa-30013b737d4e.png">

**Comment by LeStarch** [comment]
@aaronbuchwald have you properly setup the Rapberry PI configuration?  This segmentation fault usually occurs when the GPIO has not been enabled.  Make sure your settings look like the settings in the "Board Preparation" part of that guide.

**Comment by aaronbuchwald** [comment]
Ok I have enabled every interface in the Raspberry Pi configuration panel now. Also do you mean that Remote GPIO should be enabled? Because in the picture in the documentation it is shown as disabled. I have also made sure to follow the instructions for disabling UART.

I am still getting the exact same segmentation fault error.

**Comment by timcanham** [comment]
Are you running as sudo? Sometimes as the regular user it won't let you open the device?

**Comment by aaronbuchwald** [comment]
I'll try with sudo tomorrow.

Also, should Remote GPIO be disabled as in the image in the documentation or enabled?

**Comment by timcanham** [comment]
Disabled. It has some other purpose we don't use.

**Comment by aaronbuchwald** [comment]
Got rid of the segmentation fault, but it is still not able to connect to the ground station server. On the raspberry pi it simply prints out hit ctrl c to quit and then does nothing. The ground station does not react at all and there is a red x in the top right, which I assumed indicates it's not connected to anything. I tried adding the parameters
```
-a 127.0.0.1 -p 50000
```
to the script running on the ground station, but this didn't change anything.

I went through logs for the last run and the interesting thing is the comm-adapter log:

<img width="739" alt="Screen Shot 2020-01-31 at 4 56 19 PM" src="https://user-images.githubusercontent.com/24684335/73577360-a1bce000-444a-11ea-9cc8-c24c89754e7b.png">

**Comment by aaronbuchwald** [comment]
How can I get it to connect? I made sure that they are both running on the same WiFi network already and not sure what else to try.

**Comment by timcanham** [comment]
`127.0.0.0` is a private address, so the RPI can't connect to it there. What is the command line on the RPI side?

**Comment by aaronbuchwald** [comment]
On RPI side it is:
```
sudo ./RPI -a 10.0.2.15 -p 50000
```
And I also tried it on the laptop side without those parameters added (as in the documentation I was just playing around and trying to get it to work), which produced the same result.

**Comment by LeStarch** [comment]
According to your logs, you are connecting the GDS server to 0.0.0.0, which is correct.  That says "listen to all incoming connections".

Usually this issue happens when the firewall on the ground system is fighting you.  Try the following:

```
ufw allow 50000
```

**Comment by aaronbuchwald** [comment]
Ran this and then enabled the firewall, but it did not have any effect. I realize now I should have mentioned earlier, that I'm running the ground station from within virtualBox, so this is most likely a port forwarding issue.

**Comment by timcanham** [comment]
That could be it. In the past, I've used a USB network adapter and attached it to the VM so that the guest OS can set the network address, firewall, etc.

**Comment by LeStarch** [comment]
You need to forward port 50000 from the host into virtual box.  Typically I
forward it with the server address "0.0.0.0", at least to get going.

**Comment by LeStarch** [comment]
@aaronbuchwald did this work?  Can we close this?

**Comment by aaronbuchwald** [comment]
No, this didn't work for me. Figuring out a different solution now. Topic has shifted from original post, so might as well close
