### ISSUE TITLE
link to Platform Template File on F´ and CMake Platforms page redirects to 404

### ISSUE THREAD

**Issue by capsulecorplab** [nasa/fprime#1354]
link to [Platform Template File](https://github.com/nasa/fprime/blob/devel/docs/UsersGuide/api/cmake/platform/platform-template.md) on [F´ and CMake Platforms](https://github.com/nasa/fprime/blob/devel/docs/UsersGuide/cmake/cmake-platforms.md) page redirects to 404

**Comment by LeStarch** [comment]
I think this is as easy as repairing the link to point to the devel version of that file.
