### ISSUE TITLE
Seeding STest::Random causes a failure in Deframer unit tests

### ISSUE THREAD

**Issue by bocchino** [nasa/fprime#1366]
Steps to reproduce:

1. In `Svc/Deframer/test/ut-unified/TestMain.cpp`, add the line `STest::Random::seed();` just before `return RUN_ALL_TESTS();`
2. In `Svc/Deframer`, run `fprime-util build --ut`
3. In `build-fprime-automatic-native-ut/bin/[native os name]`
    1. Run `echo 545994 > seed`. This step captures the random seed that causes the issue to appear.
    2. Run `./Svc_Deframer_with_fprime`. You should see the failure output.

**Comment by LeStarch** [comment]
More failing seeds:
386613
774723

**Comment by bocchino** [comment]
I think I have a fix for this one. Right now the tests are adding non-uplink data to the received deque on the input side, and then searching through this data on the output side. The tests seem to work better if we just don't add this data on the input side. Then the search code on the output side can go away. I tried it, and these seeds seem to work now.

**Comment by bocchino** [comment]
I'm preparing a PR following the unit test review. If I confirm that this fix works, I'll include it in the PR. @arizvi786 @kevin-f-ortega FYI.
