### ISSUE TITLE
Adding WiringPi to the FPrime repository

### ISSUE THREAD

**Issue by scbrechter** [nasa/fprime#137]
My name is Stefan Brechter and I'm with the CisLunar Explorers cubesat team at Cornell University. My team and I have found that using WiringPi has made it much easier for our fprime components and drivers to interface with hardware and sensors on the cubesat. We are running into an issue when we try compiling components that include the wiringpi library. We're not sure what file needs to be changed to correctly include WiringPi so that fprime sees it and knows it is there.

Do you have any idea about what files need to be edited in order to resolve this issue? Could it be a good idea to include WiringPi in the default FPrime repo?
<img width="1081" alt="Screen Shot 2020-02-09 at 2 55 55 PM" src="https://user-images.githubusercontent.com/60856267/74109169-20063a00-4b4f-11ea-81f4-3f6049c36ee0.png">

**Comment by LeStarch** [comment]
Are you compiling with CMake and "fprime-util" or "make"?

**Comment by scbrechter** [comment]
When we ran into this issue we were still compiling with "make". Our team is going through the GPS tutorial and shifting our work to the updated CMake version of F Prime now.

**Comment by LeStarch** [comment]
Did we close the loop on this effort?

**Comment by LeStarch** [comment]
Closing.  Reopen if you still have issues with CMake.
