### ISSUE TITLE
MagicDraw errors when opening demo project: ISFRefApplication.mdxml

### ISSUE THREAD

**Issue by Absolute0K** [nasa/fprime#14]
We are trying to generate XML's using the Autocoder MagicDraw plugin for the Ref example project.

When opening the demo project located in [https://github.com/nasa/fprime/blob/master/Autocoders/MagicDrawCompPlugin/Demos/ISFRefApplication.mdxml](https://github.com/nasa/fprime/blob/master/Autocoders/MagicDrawCompPlugin/Demos/ISFRefApplication.mdxml)

We get the following messages and here are the steps we took:

**1. Missing PingPortModule.mdxml**
![missing ping](https://user-images.githubusercontent.com/21226231/47674924-d75f8300-db8e-11e8-820a-54751b932806.PNG)

For the missing PingPortModule.mdxml, we manually selected the file located at [https://github.com/nasa/fprime/tree/master/Svc/Ping](https://github.com/nasa/fprime/tree/master/Svc/Ping)

**2. Missing CmdSequencerModule.mdxml**
![missing cmdsquencer](https://user-images.githubusercontent.com/21226231/47674999-18f02e00-db8f-11e8-9c2a-10d85b2731d4.PNG)

For this missing file, we could only find the file **CmdSequencerComponent.mdxml** here: [https://github.com/nasa/fprime/tree/master/Svc/CmdSequencer](https://github.com/nasa/fprime/tree/master/Svc/CmdSequencer). So we manually select this file.

**3. The project opens. But when we try generating the xml's through Component Autocoder -> Auto Generate Component/Port/Topology XML. We get the following type error. (Note: there are also errors involving two connections, highlighted in red on the right.)**
![image](https://user-images.githubusercontent.com/21226231/47675112-6e2c3f80-db8f-11e8-8e90-a94cf97cc246.png)

When we expanded out this component, we saw that the type field was blank, which was the reason for the error.
![image](https://user-images.githubusercontent.com/21226231/47675178-95830c80-db8f-11e8-8f0f-270740f687cc.png)

We also noticed that there was also an error with the **BlockDriver** module as well, with the Interrupt port having no data type, which again causes an error.
![image](https://user-images.githubusercontent.com/21226231/47675271-d1b66d00-db8f-11e8-8b60-c1d7d5a44967.png)

Do you have any fixes for these missing type errors? Or are we happen to be using the wrong project file for generating XML's for the Ref application? We tried using the topology XML's found in Ref with Autocoder with no luck (unknown error when generating port xml's).

Thank you very much for your help.

**Comment by Absolute0K** [comment]
We have tried the reference topology located in [https://github.com/nasa/fprime/blob/master/Ref/Top/REFApplication.mdxml](https://github.com/nasa/fprime/blob/master/Ref/Top/REFApplication.mdxml)

Here is the output we get:
![image](https://user-images.githubusercontent.com/21226231/47684830-a2f9c000-dbaa-11e8-9df4-03523eedbfa1.png)
As you can see, there are couple warnings involving the Stereotype components and then there is an error when it is parsing the model for ports.

And for your reference, here is our path environment variable setup:
![image](https://user-images.githubusercontent.com/21226231/47684874-cb81ba00-dbaa-11e8-8dd5-08602453e50b.png)

Also, there are also couple errors with the connections, as shown in the bottom panel highlighted in red. 
 They come up as expression creation failures, as shown below. Perhaps they are the cause for the errors we are seeing?
![image](https://user-images.githubusercontent.com/21226231/47685214-15b76b00-dbac-11e8-878b-384c3b81ec94.png)

Again, thank you so much for your help.

**Comment by LeStarch** [comment]
It looks like the magic-draw version might be the issue.  We are currently using MagicDraw 18 (SP5, SP6) both work.

**Comment by LeStarch** [comment]
See https://github.com/nasa/fprime/issues/17 for a fix that will support newer MagicDraw versions.  On our end, we were able to test through MagicDraw 18.5.

**Comment by LeStarch** [comment]
Can we close this ticket, or is there more that needs work here?

**Comment by LeStarch** [comment]
Closing, as issues should be resolved here or in #17.
