### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [nasa/fprime#141]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [BufferQueue::finalize](https://github.com/nasa/fprime/blob/44bc57574daaac8d455b60912f664e6c57d487d9/Os/Pthreads/PriorityBufferQueue.cpp#L101 "BufferQueue::finalize function")
- [RandomlyBoundedScenario](https://github.com/nasa/fprime/blob/c35ab7ee882e2de906e731d525573b6aba560c9e/STest/STest/Scenario/RandomlyBoundedScenario.hpp#L48 "Destructor for RandomlyBoundedScenario")

**Comment by timcanham** [comment]
Good point! Make a fix and do a PR and we'll incorporate it.

**Comment by SterlingPeet** [comment]
@timcanham : can we actually guarantee this is the case?  Sometimes custom ``new`` and ``delete `` implementations are needed for smaller platforms, e.g.: like 8-bit AVRs.  Then again, those implementations could include the protection there...

**Comment by SterlingPeet** [comment]
This issue is stale, and can likely be closed.

**Comment by LeStarch** [comment]
Agreed.  It can be reopened if needed.
