### ISSUE TITLE
Recover Seed File for CI

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#1416]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|   |
---
## Problem Description

Randomized test seed-history files are not recovered making debugging and reproduction difficult or impossible.

**Comment by bocchino** [comment]
This should be partially mitigated by https://github.com/nasa/fprime/pull/1402. It prints the seed info as part of the test output.

**Comment by LeStarch** [comment]
Considered fixed by #1402 as UT output is easily obtained.
