### ISSUE TITLE
Segfault In AssertFatalAdapter

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#1418]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|   |
---
## Problem Description

The fprintf call to put the assert message into stderr segfaults on linux systems.  Switch back to printf.

**Comment by LeStarch** [comment]
Here is the series of events:

1. Ref ships with a stack size per-thread of 16K via `instances.fpp`
2. AssertFatalAdapter calls fprintf(stderr...
3. stderr is unbuffered
4. fprintf tries to buffer stderr by allocating a large buffer on the stack (rumored to be 8K)
5. 8K on an already saturated stack of only 16K causes a seg-fault.

Solution: swtich to stdout and printf, as stdout is a buffered stream and does not trigger an allocation.

**Comment by vietjtnguyen** [comment]
I'm curious, would switching to a `write()` syscall to `STDERR_FILENO` resolve this? I would expect that to not generate any additional buffers on the stack, though you'll probably need some logic to handle partial/incomplete writes.

**Comment by LeStarch** [comment]
Yes, it does.  As does an `fwrite`.
