### ISSUE TITLE
Getting Started with F' Tutorial: Cannot Exit out of Running Deployment.

### ISSUE THREAD

**Issue by sjz38** [nasa/fprime#143]
Under the "Installing the F´ Executable and Dictionaries "Installing the F´ Executable and Dictionaries" section, after I ran the ./bin/Linux/Ref command to run the deployment, the code runs, but when I try to  CTRL+C out of the deployment, it would not exit out. Is there any way to resolve this issue?

**Comment by LeStarch** [comment]
CTRL-Z
kill %1
<If still hung>
kill -KILL %1

**Comment by SterlingPeet** [comment]
@LeStarch : seems like regularly needing to resort to ``kill`` is a bug.  I'll report back if I try this and see the same behavior.

**Comment by LeStarch** [comment]
Usually this occurs when an active component or Task has been added without the proper call to shutdown at the end.  It bears investigation what was added to cause this.

**Comment by LeStarch** [comment]
Fix should be delivered.
