### ISSUE TITLE
Unanticipated Regenerations

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#1431]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|   |
---
## Problem Description

Ref occasionally regenerates the build-cache between the build and the installation step.  Why?

Reports of regeneration of AC files if they are touched.  Why?

**Comment by JackNWhite** [comment]
I experience this problem on our project, but it always happens - not just sometimes.

Perhaps turning on verbosity might shed some light on this. I ran `VERBOSE=1 make` from my unit-testing build cache and on only the third line:
```
Re-run cmake file: Makefile older than: MyComponent/MyComponentComponentAi.xml
```
I touched the Makefile, and got the same for `CMakeFiles/cmake.check_cache`. Could these files be created after the autocoders have completed?

**Comment by LeStarch** [comment]
@JackNWhite this is great insight!  Are you using FPP to model?

If so, then the issue is that the `Ai.xml` files (generated during the build) are still marked as influencing the CMake system...which means it will randomly regenerate.

We need to add a check in the CMake system to only make that dependence if and only if the Ai.xml is not a generated product.

**Comment by JackNWhite** [comment]
Yes, it's all FPP now.
