### ISSUE TITLE
Cheetah version error

### ISSUE THREAD

**Issue by aaronbuchwald** [nasa/fprime#145]
When compiling, I get the error that there is an incompatible cheetah version as in the screenshot. I checked and made sure and when running 
```bash
cheetah --version
```
it says that I have cheetah version 3 installed. I haven't built anything else before, so I'm not sure why it should need to recompile with the new version. Do you know what's wrong here?
<img width="750" alt="Screen Shot 2020-02-17 at 4 43 11 PM" src="https://user-images.githubusercontent.com/24684335/74690893-9db0f200-51ae-11ea-8278-e0f380ed2a5e.png">

**Comment by LeStarch** [comment]
This happens if you switch between Python 2 and Python 3.  ( Note, it will blow away any changes in Autocoders) Try this to fix:

```
git clean -xdf fprime/Autocoders/
```

**Comment by LeStarch** [comment]
Then rebuild, and it will recompile templates.

**Comment by aaronbuchwald** [comment]
Thanks, this worked!
