### ISSUE TITLE
Ground Station "localhost:5000" does not include GPS tutorial commands

### ISSUE THREAD

**Issue by scbrechter** [nasa/fprime#147]
I was able to open the Ground Station html window and have it send commands to a terminal window on native MacOS(see below). However, I was not able to find the GPS tutorial commands I created in the GS drop-down list. I think I copy and pasted all your topology code from the tutorial section "Build the Topology Sources" and updated the CMakeLists.txt file correctly, but the commands do not appear in the list. Everyone on my software team who has gone through the GPS tutorial has run into the same issue.  What are we doing wrong?
<img width="831" alt="Screen Shot 2020-02-20 at 4 46 52 PM" src="https://user-images.githubusercontent.com/60856267/74981739-ca5c4800-5400-11ea-9359-203746549a00.png">
<img width="799" alt="Screen Shot 2020-02-20 at 4 46 33 PM" src="https://user-images.githubusercontent.com/60856267/74981756-d3e5b000-5400-11ea-9077-dbe4ea37e8f3.png">

**Comment by LeStarch** [comment]
Thanks for posting this issue.  I am going to take a look.

**Comment by LeStarch** [comment]
@scbrechter quick question: do the Channels for the GPS appear in the Channels tab above?

Double check that you are running from the "GpsApp" directory.

**Comment by LeStarch** [comment]
If you have ensured you ran the "fprime-gds -d . -n" from the GpsApp directory, then make sure that the "Commands.xml' is imported in the "GpsApp/Gps/GpsComponentAi.xml" as shown below:

```
    <!-- Import command, telemetry, and event dictionaries -->
    <import_dictionary>GpsApp/Gps/Commands.xml</import_dictionary>
```

**Comment by LeStarch** [comment]
Then run run the following:
```
cd GpsApp
# Clean and regenerate
fprime-util purge
fprime-util generate
# Rebuild and install
fprime-util build
fprime-util install
# Now run the ground station on the fully-rebuilt code
fprime-gds -d . -n
```

**Comment by LeStarch** [comment]
Feel free to post more if you still have issues.

**Comment by scbrechter** [comment]
I copied the "GpsApp/Gps/GpsComponentAi.xml" exactly from the tutorial which includes that import dictionary statement.
<img width="687" alt="Screen Shot 2020-03-01 at 2 07 41 PM" src="https://user-images.githubusercontent.com/60856267/75632038-2162d980-5bc6-11ea-8f38-8ce13c6dd642.png">
However I'm not seeing any GPS channels under the Channels tab
<img width="1132" alt="Screen Shot 2020-03-01 at 2 04 40 PM" src="https://user-images.githubusercontent.com/60856267/75632309-c5e61b00-5bc8-11ea-9624-45412e1a1d16.png">
Could the issue be that I'm not actually connected to a RPI with a GPS sensor? I'm just running the ground station and other end terminal locally on my Mac. If it helps to know, Im successfully sending no_op commands to the other end terminal.

**Comment by LeStarch** [comment]
If you do not have a GPS unit plugged into your mac via USB, then you should not expect channels or EVRs.  I believe the GPS component assumes that is available.

**Comment by LeStarch** [comment]
Can I close this, or are there still unresolved issues?
