### ISSUE TITLE
Correction to the GPS Tutorial for MacOS native users

### ISSUE THREAD

**Issue by scbrechter** [nasa/fprime#148]
In "Running the Executable On the Native Host with the Ground System":
https://github.com/nasa/fprime/blob/master/docs/Tutorials/GpsTutorial/Tutorial.md#running-the-executable-on-the-native-host-with-the-ground-system

Please add that for MacOS users `Linux` should be replaced with `Darwin` in this command for it to run:
<img width="1000" alt="Screen Shot 2020-02-20 at 4 59 43 PM" src="https://user-images.githubusercontent.com/60856267/74982650-85391580-5402-11ea-9c34-c6864da19ec3.png">
so MacOS users should use: 
`cd fprime/GpsApp`
`./bin/Darwin/GpsApp -a 127.0.0.1 -p 50000 -d /dev/ttyACM0`

**Comment by LeStarch** [comment]
Good catch.  I'll get this fixed.

**Comment by LeStarch** [comment]
@scbrechter could you look at #149.  See if the proposed clarifiactions are what you'd expect.

**Comment by LeStarch** [comment]
Fixed, closing.
