### ISSUE TITLE
Add standard FPP types

### ISSUE THREAD

**Issue by timcanham** [nasa/fprime#1486]
| | |
|:---|:---|
|**_F´ Version_**| 3.0 |
|**_Affected Component_**| None |
---
## Feature Description

Add some common types that users could use. Things like:

ON, OFF (ex. a device)
HIGH, LOW (logic level)
OPEN, CLOSED (file, cover, etc)
IN, OUT (direction of flow)
ACTIVE, INACTIVE (behavior)
HEALTHY, SICK, FAILED (Device health)

## Rationale

Would avoid users defining them again and again.

**Comment by ThibFrgsGmz** [comment]
And ``INOUT`` in addition for direction of flow ?

**Comment by LeStarch** [comment]
I **really** want this.

**Comment by LeStarch** [comment]
We should also scan the code base for common types implemented within components and see if we can make them generic.

**Comment by codeflight1** [comment]
I'm currently working on this. Which module should the definitions reside in?

**Comment by LeStarch** [comment]
This was merged in.  Is it complete?
