### ISSUE TITLE
fprime-util generate produces error in instances.fpp

### ISSUE THREAD

**Issue by mrb0y** [nasa/fprime#1493]
The following error occurs for me after entering the fprime-util generate command for the Ref example...

-- Generating FPP location index
fpp-locate-defs
/home/***/fprime/Ref/Top/instances.fpp: 231.5
    type "Drv::TcpClient" \
    ^
error: } expected
CMake Error at /home/***/fprime/cmake/target/fpp_locs.cmake:56 (message):
-- Configuring incomplete, errors occurred!
  Failed to run fpp-locate-deps

I had an adventure installing FPP for WSL2 Ubuntu 20.04 but I think it's properly installed but possibly the root of the problem.

**Comment by LeStarch** [comment]
This looks like a possible version of FPP vs version of F´ miss-match.  If you are on the latest devel:

```
pip install -r fprime/requirements.txt
```

You can rerun that above command when you update devel to continue and  track tool dependencies.

**Comment by LeStarch** [comment]
Did the above suggestion work?  I am going to close, feel free to reopen if it isn't resolved.
