### ISSUE TITLE
Ground Station throws exception when leaving ground station app in browser on Mac

### ISSUE THREAD

**Issue by aaronbuchwald** [nasa/fprime#150]
When I am running the ground station on MacOS (working off of LeStarch's gps-application branch), I run into an exception that occurs whenever I leave the ground station application. The web app starts successfully, but once I leave the web app to go back to the command line, I get the following error:

<img width="1005" alt="Screen Shot 2020-02-27 at 9 51 08 PM" src="https://user-images.githubusercontent.com/24684335/75506301-8d1d2a80-59ab-11ea-8c1b-a6dff76ff6b8.png">

**Comment by LeStarch** [comment]
That may mean the gps-application branch needs a pull from devel.  You could try that yourself, and I'll see if I can update that branch and push the updates sometime soon.

**Comment by LeStarch** [comment]
I am going to move this to my fork, as that is where the update needs to occur.

**Comment by LeStarch** [comment]
Needs updated GPS base app.

**Comment by LeStarch** [comment]
This should be fixed.
