### ISSUE TITLE
Show what version of FPRIME is in the branch from the README

### ISSUE THREAD

**Issue by sfregoso** [nasa/fprime#1506]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

A quick description of the requested feature.

I would be great that at the top of the README it would state what version of FPRIME I would be checking out from this branch, especially the "devel" branch.  If its there, it was not quickly visible to me.

## Rationale

A rationale for why the feature should be implemented in F´.

**Comment by ThibFrgsGmz** [comment]
You would like to have a badge that automatically displays the last tagged version ?
GitHub already handles that in the project metadata.
Otherwise these infos are handled by git.
VSCode offers awesome git extension to navigate/visualize for branches.

**Comment by astroesteban** [comment]
Yeah I think a locally installed tool like Git Graph or GitLens would be better. I personally use the latter.
The `devel` branch is a moving target and the latest development "version" might become stale rather quickly. The `devel` branch is the latest and greatest so I assume it's whatever the current release version is plus some improvements. Thoughts?

**Comment by pouriya73** [comment]
https://github.com/pouriya73/Camputer-Quantum-Programming

**Comment by LeStarch** [comment]
You could also run:

```
git describe --tag --always
```

and this will print the version.

**Comment by LeStarch** [comment]
I think we can close this issue.  The latest release should be easily available to the right of the window.
