### ISSUE TITLE
Math Tutorial Unit Test Object Is of Wrong Class

### ISSUE THREAD

**Issue by sfregoso** [nasa/fprime#1516]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|   |
---
## Problem Description

The object "component" of the unit test is of wrong type.  It should be of type "MathSender", but the autogenerating code writes it as "MathSendorComponentImpl".

## How to Reproduce

1. Create unit test implementation for the "MathSender"
2.  Open "Test.hpp", got to line 92 where the object "component" is defined.
3.  Note the type of the object.  It should be of type "MathSender" and not "MathSenderComponentImpl"

## Expected Behavior

The object should be type "MathSender" and not "MathSenderComponentImpl"
A description of the expected behavior.

<img width="456" alt="image" src="https://user-images.githubusercontent.com/51178479/174635413-6e927b04-92eb-4f10-905e-b266f1072214.png">

**Comment by LeStarch** [comment]
Also it is merged.  I am closing this issue.  Good catch!
