### ISSUE TITLE
F Prime version with schema version in the GDS

### ISSUE THREAD

**Issue by kevin-f-ortega** [nasa/fprime#1546]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

fprime version with schema version in the GDS compatibility check

**Comment by LeStarch** [comment]
@kevin-f-ortega can you elaborate?  I don't remember this one.

**Comment by kevin-f-ortega** [comment]
@LeStarch I don't exactly remember. We can close this ticket for now.
