### ISSUE TITLE
Autogenerated code does not compile

### ISSUE THREAD

**Issue by aaronbuchwald** [nasa/fprime#155]
I am working on a camera component and when I try to run
```
fprime-util install native
```
I run into about 20 errors that occur when compiling an autogenerated C++ file:

<img width="558" alt="Screen Shot 2020-03-04 at 5 51 32 PM" src="https://user-images.githubusercontent.com/24684335/75930606-f506c180-5e40-11ea-9ec6-cb02b31d551d.png">

Do you have any idea what might be causing this? I can make the branch available if you need.

**Comment by LeStarch** [comment]
Is there a space in your telemetry item name in the Telemetry XML?

**Comment by aaronbuchwald** [comment]
Yes this was the problem, thanks
