### ISSUE TITLE
Refactor README.md

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#1617]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|   |
---
## Problem Description

Users are discovering F´ via the github repo directly (as opposed to the documentation landing page).  This is causing difficulty in finding and running the installation instructions.

We should look into refactoring the README so it has a similar flow (or links to) our documentation.

**Comment by LeStarch** [comment]
@gjwatney feel free to provide specific thoughts here, or direct them to me directly.

**Comment by LeStarch** [comment]
In discussing this further, the `README.md` page here should highlight a link to the documentation `Home` and `Getting Started` pages. It should otherwise be minimal.   To be precise:

1. Short intro paragraph (what is F´). Must be succinct.
2. Links to `Documentation Home` and `Getting Started`
3. Links to release notes

**Comment by saminarp** [comment]
Hi, 
I would really like to contribute to this as part of Hacktoberfest! I just started out in open-source development and want to help as much as possible. Please let me know how to get started and I will put my best into it. :)
Thank you!!

**Comment by thomas-bc** [comment]
Released! Go check out our new README https://github.com/nasa/fprime

**Comment by ThibFrgsGmz** [comment]
Yes awesome !
