### ISSUE TITLE
Ref, nproc, deployment directory - Autocoder Install MacOS

### ISSUE THREAD

**Issue by jake14000** [nasa/fprime#1666]
| | |
|:---|:---|
|**_F´ Version_**| 3.1 |
|**_Affected Component_**| Ref, nproc, deployment directory, Autocoder install MacOS  |
---
## Problem Description
Hello, I am downloading F' for a CubeSat project and need some help with installation. I am not a software person by-trade, so if someone can guide me through these steps/where I misstepped, that would help me out a lot. Thanks!

Operating System:
MacOS Catalina 10.15.7 

Installation Programs Installed:
Python 3.10.7 with command line certificates
CMake  3.24.2
XCode 12.4 with command line tools

## How to Reproduce
SEE PHOTOS AT THE BOTTOM

1. Run Install Code In MacOS Terminal:
python3 -m venv $HOME/fprime-venv
. $HOME/fprime-venv/bin/activate
pip install -U setuptools setuptools_scm wheel pip

2. Run the Repository and F' Tools:
git clone https://github.com/nasa/fprime
pip install -r fprime/requirements.txt

3.  Wait for successful download:
Successfully installed Brotli-1.0.9 Cheetah3-3.2.6.post1 Flask-1.1.4 Flask-Compress-1.12 Flask-RESTful-0.3.9 Jinja2-2.11.3 Markdown-3.3.7 MarkupSafe-2.0.1 Pygments-2.12.0 Werkzeug-1.0.1 aniso8601-9.0.1 argcomplete-1.12.3 arrow-1.2.2 attrs-21.4.0 binaryornot-0.4.4 certifi-2022.6.15 chardet-4.0.0 charset-normalizer-2.0.12 click-7.1.2 cookiecutter-1.7.3 fprime-fpp-1.0.2 fprime-gds-3.1.3 fprime-tools-3.1.1 gcovr-5.1 idna-3.3 importlib-metadata-4.11.4 iniconfig-1.1.1 itsdangerous-1.1.0 jinja2-time-0.2.0 lxml-4.9.0 pexpect-4.8.0 pluggy-1.0.0 poyo-0.5.0 ptyprocess-0.7.0 py-1.11.0 pytest-6.2.5 python-dateutil-2.8.2 python-slugify-6.1.2 pytz-2022.1 pyzmq-22.3.0 requests-2.28.0 six-1.16.0 text-unidecode-1.3 toml-0.10.2 urllib3-1.26.9 zipp-3.8.0

4. This is where it said it was downloading to:
Stored in directory: /Users/myname/Library/Caches/pip/wheels/
(added "myname" instead of my actual name)

5. Run the Autocoder Install Test:
cd Ref
fprime-util generate
fprime-util build --jobs "$(nproc || printf '%s\n' 1)"

##Expected Behavior

6. Error Messages Received:
cd: no such file or directory: Ref
[ERROR] Could not detect deployment directory for: /Users/myname
zsh: command not found: nproc
[ERROR] Could not detect deployment directory for: /Users/myname

7. Tested Step 1 Again and Received the "Requirement Already Satisfied" for all site packages
_____________________
My MacOS terminal says the following:
myname -- -zsh -- 166x34
(fprime-venv) myname@MacBook-Pro ~ %

Should I have other applications open (CMake, XCode, Python, etc)? I read a similar Issue Ticket for a Linux user, and the post reply had something to do with pip installing in the .local directory, causing the Terminal to not find it. I am not sure how to fix that (if it is the case with my issue). Any help would be appreciated, thank you!

![Screen Shot 2022-09-23 at 10 13 08 AM](https://user-images.githubusercontent.com/114238662/191981644-d76a223d-01a4-42a6-a9f6-636b54d3032a.png)
![Screen Shot 2022-09-23 at 10 15 07 AM](https://user-images.githubusercontent.com/114238662/191981672-c29a6cab-14d0-4298-8521-052391eb7f6f.png)

**Comment by ThibFrgsGmz** [comment]
You should first `cd fprime` then `cd Ref`

**Comment by jake14000** [comment]
> You should first `cd fprime` then `cd Ref`

Success! Thank you for that. For the second step, here is another install warning I am receiving:

(fprime-venv) myname@MacBook-Pro Ref %  fprime-gds -g html -r <path to fprime checkout>/Ref/build-artifacts
zsh: no such file or directory: path

**Comment by ThibFrgsGmz** [comment]
Do you have `zsh` installed? What do you see when you write the following command? `zsh --version`

Note: I don't have `zsh` on my `Ubuntu` installation. Maybe this is a necessity for `MacOS` ?

**Comment by ThibFrgsGmz** [comment]
Did you run the commands `fprime-util generate` and then `fprime-util build` ? Were they successful?

Do you have the same problem if you just run the `fprime-gds` command without any arguments in the Ref folder? (Making sure the build went well.)

**Comment by jake14000** [comment]
> Do you have `zsh` installed? What do you see when you write the following command? `zsh --version`
> 
> Note: I don't have `zsh` on my `Ubuntu` installation. Maybe this is a necessity for `MacOS` ?

Here is the terminal response:
zsh 5.7.1 (x86_64-apple-darwin19.0)

**Comment by jake14000** [comment]
> Did you run the commands `fprime-util generate` and then `fprime-util build` ? Were they successful?
> 
> Do you have the same problem if you just run the `fprime-gds` command without any arguments in the Ref folder? (Making sure the build went well.)

Just so I understand correctly, I should run the following:
fprime-util generate

fprime-util build

then run 
fprime-gds -g html -r /Ref/build-artifacts

**Comment by ThibFrgsGmz** [comment]
Yes, `fprime-util generate` "generates" all the files needed by the tool chain (compiler, linker) to build your deployment.

`fprime-util build` "builds" your deployment/application/binary;

`fprime-gds` launches the "embedded" software, gds backend and gds frontend.

**Comment by jake14000** [comment]
Okay, so I ran fprime-gds WITHOUT -g html -r /Ref/build-artifacts and here is what I got:

* Serving Flask app "fprime_gds.flask.app"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
[INFO] F prime is now running. CTRL-C to shutdown all components.

I was also directed to the F' Commanding page and sent the command "cmdDisp.CMD_NO_OP"

Does this mean F' is now set up, and I can continue with the Math Component Tutorial?

**Comment by jake14000** [comment]
> > Does this mean F' is now set up, and I can continue with the Math Component Tutorial?
> 
> Yes, you're ready buddy!

Awesome! Thank you for hopping on here to help me out @ThibFrgsGmz! I really appreciate your time and expertise. Looks like everything is a go.
