### ISSUE TITLE
Construct Hadware CI Framework 

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#1684]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

Construct a framework for hardware CI. Allow easy integration of new boards, toolchains, and example projects.

**Comment by SterlingPeet** [comment]
Is there any example of this already, or a model to look at for deployment level integration testing?

**Comment by LeStarch** [comment]
@rlcheng keep this in mind while you integrate the baremetal reference.  In short the goal is to make it configurable on the boards we run on.

I suggested a `run` and `cleanup` script provided by the use.   Closing for now as this is captured in your work.
