### ISSUE TITLE
Fix Cookiecutter Insecure Version

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#1692]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|   |
---
## Problem Description

Fix use of cookiecutter to newer version

**Comment by thomas-bc** [comment]
Cookiecutter releases: https://github.com/cookiecutter/cookiecutter/releases

We are currently using **1.7.3**, I would recommend upgrading to **2.1.1** (latest).

As far as I can tell, none of the changes should affect our current usage of cookiecutter in fprime. There's a very small probability that some users may be affected if they created their own cookiecutter templates, but I don't think we should worry about this?

Path forward:
1. Loosen the cookiecutter requirement in fprime-tools (current requirement is [cookiecutter>=1.7.2, <2.0.0](https://github.com/fprime-community/fprime-tools/blob/3f7865a8a8b980b16a0aff969e8150c632670281/setup.py#L89))
2. Release fprime-tools (should also include the updates from https://github.com/nasa/fprime/issues/1690)
3. Update fprime with new fprime-tools and cookiecutter==2.1.1

Let me know if I missed anything.
