### ISSUE TITLE
fprime/docs/INSTALL.md : Hanging on installing F' Python packages

### ISSUE THREAD

**Issue by jackyyl** [nasa/fprime#170]
When I first attempted to install the F' Python packages with the commands: 
pip install ./Fw/Python
pip install ./Gds
It would hang halfway through the installation process. This was done on the Zynq-Z1 FPGA board. My current solution was to simply wait for however long it needed to finish running the command, in my case it was approximately 4 hours. I have tested the same command on WSL and had no issues installing the F' Python packages however.

**Comment by LeStarch** [comment]
This likely is caused by a slow internet connection or caused by older python code.  When setting up python (before running the commands above), you can run the following to fix the problem.  We need to add these commands to the `INSTALL.md` document.

```
pip install --upgrade wheel setuptools pip
```

**Comment by LeStarch** [comment]
Did this help? Can I close?

**Comment by LeStarch** [comment]
Reopen if this hasn't helped you.
