### ISSUE TITLE
FW_NO_ASSERT does not work

### ISSUE THREAD

**Issue by timcanham** [nasa/fprime#1706]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|   |
---
## Problem Description

Turning off asserts by setting assert level to FW_NO_ASSERT causes compilation issues with all the classes subclassing AssertHook.

We have 2 options:
1. Conditionally compile all classes subclassing AssertHook
2. Always define AssertHook class, and disable asserts at the macro level

**Comment by LeStarch** [comment]
@timcanham I think option 2 is best. It does leave extra code around when not using asserts, but it limits a very suspect use of conditional compilation.  If you agree, please let me know.

**Comment by timcanham** [comment]
Sounds good to me!
