### ISSUE TITLE
Math Component F' Tutorial

### ISSUE THREAD

**Issue by csmith608** [nasa/fprime#171]
After we have connected the components in section 3 of this tutorial we are told to run:
`fprime-util build`
from 
`Ref/Top`
If run from that location this error is thrown:
make: *** No rule to make target `Ref_Top'.  Stop.
[ERROR] CMake erred with return code 2.

I believe we should actually be running that command from 
`Ref`

**Comment by LeStarch** [comment]
Yes, this needs to be fixed!

**Comment by LeStarch** [comment]
Already fixed in devel.  Needs to be pushed to master for display.

**Comment by LeStarch** [comment]
Delivered!

**Comment by Hackerman342** [comment]
Hi,
I'm getting this same error. Just to confirm - we should not be running `fprime-util build` from `Ref/Top` and should only run it from `Ref`?
Thanks.

**Comment by LeStarch** [comment]
Yes that is correct.  A correction to the tutorial will be delivered in the next release.

**Comment by Hackerman342** [comment]
Awesome, thanks!
