### ISSUE TITLE
Clickable UT Assert Messages

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#1724]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

Currently F´ unittest assert messages look like the following:

```
File: <file>
Line: ###
```

However, IDEs typically make messages automatically clickable if they are of the form:
```
<file>:###
```
GoogleTest asserts follow this form, and we should switch.

**Comment by SMorettini** [comment]
If someone didn't pick it up yet, I can do it :)

**Comment by LeStarch** [comment]
@SMorettini go for it!

**Comment by SMorettini** [comment]
I create the pull request. I update the messages for the asserts in the UT. Should I change also the messages in the normal asserts?

**Comment by SMorettini** [comment]
@LeStarch Should I apply the same change to the other ASSERTS? If yes should I do another issue or link to this one?

**Comment by LeStarch** [comment]
@SMorettini I opened up #1847 to track this. However, let's not implement just yet.  I need to think through the implications.

**Comment by SMorettini** [comment]
Yes, I was referring to FW_ASSERTS. Since you create specific issues for that, I think you can proceed with closing this issue(I can't because you made it).
