### ISSUE TITLE
Math Component F' Tutorial Section 4 GDS Error

### ISSUE THREAD

**Issue by csmith608** [nasa/fprime#173]
In section 4 when the ground system is running and the MS_DO_MATH command is sent, the  error below is produced.  Other commands are sent and information shows up correctly.  
<img width="1333" alt="Screen Shot 2020-05-21 at 2 52 16 PM" src="https://user-images.githubusercontent.com/63731123/82603969-87d21500-9b81-11ea-9aad-731212002e95.png">

**Comment by JHDeerin** [comment]
I'm getting the same error, but am also getting it for any command that takes a typed-in argument (e.g. `MR_SET_FACTOR_1`,  `factor2_PRM_SET`, `cmdDisp.CMD_TEST_CMD_1`, etc.). Math commands that don't take an argument, as well as commands with drop-down menus for selecting arguments, etc., seem to work fine and are recorded in the event log.

**Comment by kbiesiadecki141** [comment]
Any update on this? I'm coming across this exact error only for commands that take arguments (mathSender.MS_DO_MATH, mathReceiver.MR_SET_FACTOR1, etc.) like JHDeerin above

**Comment by LeStarch** [comment]
Yes.  It seems to be an issue with float and double arguments.   A fix is in progress.

**Comment by LeStarch** [comment]
Once number #182 is merged, this problem should be fixed.  Nothing y'all did wrong.

**Comment by LeStarch** [comment]
Closing this issue.

**Comment by lewisjaggi** [comment]
Hello,
I did the tutorial yesterday and I encountered this problem.
Can you tell me what can i do to fix it ?
