### ISSUE TITLE
Fpp constants available at compile-time

### ISSUE THREAD

**Issue by mohamed-ghita** [nasa/fprime#1752]
| | |
|:---|:---|
|**_3.x**| |
|**All**|  |
---
## Feature Description

Make Fpp constants available at compile-time by auto-coding them as `constexpr` variables.

## Rationale

Fpp constants are auto coded as either `enum` member for integral constants or `extern const` for floating-point. 
`extern const` variables are not available at compile time. For example, `static_assert(FPP_F32_CONSTANT > 0);` will fail to compile because value of `FPP_F32_CONSTANT` is available only during linkage.

Also, it's cleaner to use `constexpr` for both integrals and floating-points instead of relying on enums. 

Current FppConstantAC.hpp:
```
namespace ModuleNamespace {
      enum FppConstant_CONSTANT_I32{
        CONSTANT_I32 = 5
      };
      extern const F32 CONSTANT_F32; // value assigned in .cpp file
}
```

with constexpr:
```
namespace ModuleNamespace {
      constexpr I32 CONSTANT_I32{5};
      constexpr F32 CONSTANT_F32{5.5F};
      // perhaps also a c-string?
      constexpr char const* CONSTANT_STRING = "some compile-time string"; 
}

// This will also scale for member constants of structs or classes:
class SOME_STRUCT {
    static constexpr F32 MEMBER_CONSTANT{5.5F};
}
```

**Comment by codeflight1** [comment]
I believe this hasn't been done because `constexpr` is a C++11 feature.

**Comment by ThibFrgsGmz** [comment]
According to the [coding style](https://github.com/nasa/fprime/blob/master/docs/UsersGuide/dev/code-style.md#c), C++ 11 is the official project standard, but some features are avoided - perhaps `constexpr` is one of them.

**Comment by mohamed-ghita** [comment]
According to the [coding guidlines](https://github.com/nasa/fprime/blob/master/docs/UsersGuide/dev/code-style.md#embedded-c-usage), developers are encouraged to used `std::numeric_limits` which defines `constexpr` methods such as `static constexpr T std::numeric_limits<T>::max(); since C++11` [cpp refrence](https://en.cppreference.com/w/cpp/types/numeric_limits/max).

**Comment by bocchino** [comment]
I agree it would be better to use constexpr. The FPP constant code gen was written back when we were still using C++98.

**Comment by LeStarch** [comment]
@bocchino is this one on your radar?

**Comment by bocchino** [comment]
It's an open issue in FPP (https://github.com/fprime-community/fpp/issues/269). See above.

**Comment by LeStarch** [comment]
I am going to close this one since it is tracked directly in FPP.
