### ISSUE TITLE
Spelling Check Deprecated WARNINGs

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#1758]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|   |
---
## Problem Description

From the spell check actions:

```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

**Comment by thomas-bc** [comment]
This was brought up in #1790 - it looks like it should have been corrected with this update.
