### ISSUE TITLE
[Math Component Tutorial] Unit test check fail

### ISSUE THREAD

**Issue by kbiesiadecki141** [nasa/fprime#176]
Hi,

I'm running through the Math Component tutorial right now and while i've been able to successfully build (fprime-util build-ut in MathSender directory), my fprime-util check is failing. I seem to be getting different output than is shown in the tutorial, so I'm not sure if it's something in my code or how I'm running it. Any help would be much appreciated! 

<img width="1105" alt="Screen Shot 2020-05-26 at 1 48 54 PM" src="https://user-images.githubusercontent.com/13440927/82949789-0e5b6d80-9f59-11ea-9f9a-8d32565c3713.png">

**Comment by LeStarch** [comment]
This looks like one your unit tests is failing.  You'll need to inspect the UT output to understand why. For your version of F´, the output is captured in a file.  You should be able to find the output here:
```
fprime/Ref/build-fprime-automatic-default-ut/Ref/MathSender/Testing/Temporary/LastTest.log
```

We are in the process of releasing F´ 1.4, which would display the UT output inline.   I can supply update instruction if that would help.

**Comment by kbiesiadecki141** [comment]
Ah thank you!

**Comment by LeStarch** [comment]
Before we close this issue, was there a problem in the tutorial that caused the error?  I want to make sure the tutorial isn't causing bugs.

**Comment by kbiesiadecki141** [comment]
Nope, looks like it was a copy-paste error - accidentally had my completion status reply too soon. Thanks for a quick response!

**Comment by LeStarch** [comment]
Ok, I will close.  I appreciate the feedback.  Welcome to F´!
