### ISSUE TITLE
Tab related error message 

### ISSUE THREAD

**Issue by hAkselS** [nasa/fprime#1811]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

Explicit error message for tabs used in fpp

## Rationale

Tabs are not allowed in fpp, but if a tab is included the resulting error message is not clear to inexperienced users.

**Comment by bocchino** [comment]
Good point, I added an issue to the FPP repo. It's on the list of issues to close in the next FPP release.

**Comment by hAkselS** [comment]
Awesome!

**Comment by bocchino** [comment]
This issue is resolved as of FPP v1.2.0.
