### ISSUE TITLE
Question about Apache-2.0 in space

### ISSUE THREAD

**Issue by tmechelke** [nasa/fprime#1831]
Excerpt from the Apache-2.0 license:
... each Contributor hereby grants to You
        a perpetual, worldwide ... copyright license ...
        a perpetual, worldwide ... patent license ...

The copyright and patent grants are restricted: **worldwide**.
A satellite around Earth is arguably not included by that definition.
Or is it? What about software on the Moon or on Mars?

Is Apache-2.0 licensed software legally usable in space?

**Comment by astroesteban** [comment]
Do we have any space lawyers in the community? 👀

**Comment by ThibFrgsGmz** [comment]
It would be good to ask this on cFS as well: they have lawyers in their process.

**Comment by tmechelke** [comment]
I asked it over there as well: https://github.com/nasa/cFS/issues/637

**Comment by ThibFrgsGmz** [comment]
Note: according to ChatGPT, the answer is yes: "the Apache-2.0 license allows the use of Apache licensed software in space". 😁

**Comment by astroesteban** [comment]
Our AI overlords have spoken 🤖

**Comment by LeStarch** [comment]
Given this was pinged over at CFS, I will close here for the time being.
