### ISSUE TITLE
F' documentation lists multiple latest versions

### ISSUE THREAD

**Issue by jefferyjohn** [nasa/fprime#1835]
## Problem Description

The [F' website](https://nasa.github.io/fprime/) lists several releases.

![image](https://user-images.githubusercontent.com/53410876/210735518-cada2a5d-ad68-42e3-88af-b042c54d2694.png)

However, all versions after v1.5 note that they are the latest F' framework.

![image](https://user-images.githubusercontent.com/53410876/210735612-81593cbe-404f-4abe-881c-040351d39e46.png)

I've resolved this with #1833 to update the documentation for these versions aside from 3.1.0 to include a link to documentation home, similar to v1.5.

![image](https://user-images.githubusercontent.com/53410876/210736614-5fd63543-25c4-4e3d-9c0b-6aa9c4dd0e13.png)

**Comment by LeStarch** [comment]
Thanks for the fix!
