### ISSUE TITLE
Add more accurate error handling for the `SystemResources` component

### ISSUE THREAD

**Issue by ThibFrgsGmz** [nasa/fprime#1837]
| | |
|:---|:---|
|**_F´ Version_**| latest |
|**_Affected Component_**| Os/SystemResources |
---
## Feature Description

It is necessary to add more fine-grained error handling for the SystemResources component.
Currently, there are only two return codes:

```cpp
enum SystemResourcesStatus {
    SYSTEM_RESOURCES_OK,     //!< Call was successful
    SYSTEM_RESOURCES_ERROR,  //!< Call failed
};
```

## Rationale

It is more useful to define separate enumeration values for each possible type of error.
Otherwise, if an error occurs, we don't know exactly where it came from.

**Comment by thomas-bc** [comment]
Fixed
