### ISSUE TITLE
Add GitHub Action - Markdown link check

### ISSUE THREAD

**Issue by ThibFrgsGmz** [nasa/fprime#1840]
| | |
|:---|:---|
|**_F´ Version_**| latest |
|**_Affected Component_**|  |
---
## Feature Description

A workflow for checking broken links in Markdown files should be integrated through the GitHub Action [markdown-link-check](https://github.com/gaurav-nelson/github-action-markdown-link-check).

This GitHub Action should check all Markdown files in the repository and report any broken links it detects.

The action should be configurable to exclude certain parts of the repository (e.g., specific directories or files) from link checking.

If broken links are detected, the action should display an error and stop the workflow, with a message indicating the files and links involved.

## Rationale

Broken links can be frustrating for users and affect the quality and user experience of a site or software. They can also be difficult to spot manually, especially in large repositories with many Markdown files.

Adding a GitHub Action that automatically checks for broken links in Markdown files would make it easier to maintain and improve the quality of the repository by quickly flagging broken links and allowing contributors to fix them.

It could also improve the user experience for people using the repository, providing them with quality content without broken links.

**Comment by SauravMaheshkar** [comment]
I'd like to take this up 😃

**Comment by thomas-bc** [comment]
That'd be great! I really would love to have this, just never got the time to get to it.

**Comment by thomas-bc** [comment]
Once you have the PR ready for this, we can help fixing the markdown links that may be invalid. It's possible some might not be that trivial to resolve if files have been moved around and such.
