### ISSUE TITLE
Multiple definition of `Os::IntervalTimer::IntervalTimer()` on Baremetal

### ISSUE THREAD

**Issue by kevin-f-ortega** [nasa/fprime#1845]
| | |
|:---|:---|
|**_F´ Version_**| [d177bb7](https://github.com/nasa/fprime/commit/d177bb7ef91f0b00ac805a0414e793bcfa053da2)|
|**_Affected Component_**|   Baremetal Os::IntervalTimer |
---
## Problem Description

When building for baremetal, using `Os::IntervalTimer` generates these types of errors:

multiple definition of `Os::IntervalTimer::~IntervalTimer()` 
multiple definition of `Os::IntervalTimer::IntervalTimer()`

## How to Reproduce

1. Include <Os/IntervalTimer.hpp>
2. Instantiate an Os::IntervalTimer variable
3. Compile with bare metal

## Expected Behavior

I expect to successfully compile.

**Comment by kevin-f-ortega** [comment]
Seems like the issue is the Baremetal implementation has a constructor and destructor with the same signature as the ones found in IntervalTimerCommon.cpp.

Question: How would one go about implementing their own IntervalTimer for their specific Baremetal project?

**Comment by LeStarch** [comment]
@gjwatney ran into this too.  We need to fix this in F´.

**Comment by LeStarch** [comment]
See: https://github.com/nasa/fprime/issues/1846

**Comment by thomas-bc** [comment]
Baremetal reference has been delivered
