### ISSUE TITLE
OS BareMetal implementation

### ISSUE THREAD

**Issue by gjwatney** [nasa/fprime#1846]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|   |
---
## Problem Description

When building an application using BareMetal, all the F' BareMetal capabilities are brought in including the stubbed capabilities like IntervalTimer.  This prevents an application from bringing in their own implementation specific capabilities. 

## How to Reproduce

1. In the Application cmake file, set the FPRIME_USE_BAREMETAL_SCHEDULER to "ON"
2. Create a project specific IntervalTimer
3. Instantiate the IntervalTimer

## Expected Behavior

A description of the expected behavior.

**Comment by LeStarch** [comment]
Linked this to @kevin-f-ortega's issue #1845

**Comment by LeStarch** [comment]
Closing this. Baremetal is being worked elsewhere.
