### ISSUE TITLE
`docs/Tutorials/GettingStarted/Tutorial.md` refers to removed `install` command

### ISSUE THREAD

**Issue by ivanperez-keera** [nasa/fprime#1877]
| | |
|:---|:---|
|**_F' Version_**|3.0|
|**_Affected Component_**| docs/Tutorials/GettingStarted/Tutorial.md |
---
## Problem Description

The [tutorial](https://github.com/nasa/fprime/blob/master/docs/Tutorials/GettingStarted/Tutorial.md) refers to the `"install"` command in the 'Build Ref Deployment' section (bold mine to highlight the issue):

> Note: the user almost always wants to run the "**install**" command on deployments. This builds the binary like "build" but also copies the binary to the deployments "bin" directory, i.e. fprime/Ref/bin. **Install is described below.**
> 
> This process also built the Dictionaries for the project and places the dictionary in the "Top" folder of the deployment. This happens any time the "**install**" or "build" command are run on a deployment.
> 
> The user can also build a component or deployment for a cross-compile by specifying the toolchain. A previous generate for that toolchain should have been run. Again for deployments, **the user typically should run "install", see below**. These steps require the setup described here: [RPI](https://github.com/nasa/fprime/blob/master/RPI/README.md)

The `install` command was removed in 20b5f2950c5f264a1be3d47e0e94a69518d7aeca. The first tagged version that includes this commit is v2.0.0~193^2. 

## How to Reproduce

1. Running the `install` command as implied by the text in docs/Tutorials/GettingStarted/Tutorial.md results in an error message (output of intermediate tools hidden for clarity):
```
$ git clone https://github.com/nasa/fprime
$ pip install -r fprime/requirements.txt
$ cd fprime/Ref
$ fprime-util generate
$ fprime-util build
$ fprime-util install
usage: fprime-util [-h]
                   {build,impl,check,generate,purge,fpp-check,hash-to-file,info,new}
                   ...
fprime-util: error: argument command: invalid choice: 'install' (choose from 'build', 'impl', 'check', 'generate', 'purge', 'fpp-check', 'hash-to-file', 'info', 'new')
```

## Expected Behavior

The tutorial should only refer to the build command, not the install command. Any capabilities in the install command that are now present in the build command should be rephrased to indicate so.

**Comment by ivanperez-keera** [comment]
If you want I can send a PR.

**Comment by LeStarch** [comment]
Yes a PR would be awesome.  `fprime-util build` performs the install as well, so that section just needs to be removed.

**Comment by ivanperez-keera** [comment]
Great. I'll do that.

**Comment by thomas-bc** [comment]
Getting Started tutorial has been modernized and renamed HelloWorld to leverage the new `fprime-util new` commands: https://nasa.github.io/fprime/Tutorials/HelloWorld/Tutorial.html
Closing this issue
