### ISSUE TITLE
SocketIpDriverCfg is substituted by IpCfg?

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#1895]
### Discussed in https://github.com/nasa/fprime/discussions/1891

<div type='discussions-op-text'>

<sup>Originally posted by **SMorettini** February 15, 2023</sup>
I notice in `Fprime/config` there are two very similar files: `SocketIpDriverCfg.hpp` is substituted by `IpCfg.hpp`. The first one is never included inside Fprime. It is a duplicate? Should we remove it?</div>

**Comment by LeStarch** [comment]
Yes, it should.

**Comment by SMorettini** [comment]
If you want, assign to me

**Comment by SMorettini** [comment]
@LeStarch the pull request was merged. I think you can close this issue

**Comment by LeStarch** [comment]
Yes!

**Comment by LeStarch** [comment]
Yes!
