### ISSUE TITLE
Add CMAKE variable list to F Prime docs

### ISSUE THREAD

**Issue by timcanham** [nasa/fprime#1912]
| | |
|:---|:---|
|**_F´ Version_**| 3.x |
|**_Affected Component_**| n/a |
---
## Feature Description

There are a handy set of CMAKE defined variables like `${FPRIME_PROJECT_ROOT}` that make the CMakeList.txt pathnames cleaner. Add a table of them to the F Prime docs with some examples.

## Rationale

Makes writing CMakeList.txt files easier.

**Comment by LeStarch** [comment]
This is a web linking issue, this is documented.
