### ISSUE TITLE
Broken link in GPS tutorial

### ISSUE THREAD

**Issue by keck-in-space** [nasa/fprime#1927]
| | |
|:---|:---|
|**_F´ Version_**| na |
|**_Affected Component_**| documentation   |
---
## Problem Description

There is a broken link in the GPS tutorial. It links to a User's Guide PDF which does not exist.

https://github.com/nasa/fprime/blob/7bf79db61b1b63d60a624328dc909ee62869e8ba/docs/Tutorials/GpsTutorial/Tutorial.md?plain=1#L60

**Comment by AngeloSorte** [comment]
Hi. I am new to contributing here. I don't understand well how this should be solved, but I found a link to the guide here on GitHub, on someone else's page. Can it be useful?

**Comment by AngeloSorte** [comment]
> The updated location for the user's guide is here: https://nasa.github.io/fprime/UsersGuide/guide.html

Ah, ok. I though a PDF version was needed.

**Comment by LeStarch** [comment]
We have scrubbed the GPS tutorial due to it not being updated with FPP.  Closing this issue.
