### ISSUE TITLE
Enum not added to TopologyAppDictionary

### ISSUE THREAD

**Issue by sommercharles** [nasa/fprime#193]
Hi,

I've specified an enumeration in xml (xFaultEnumAi.xml) so I can use it with several variables of a serializable.
The binary is built and installed without errors. But when I launch gds, I run into the following error:

`fprime_gds.common.data_types.exceptions.GseControllerParsingException: Parsing error: Could not find type Ref::xFault!`

Manually adding the definition of my enum in RefTopologyAppDictionary.xml does the trick.
But I'm guessing if the parsers don't add the enum automatically, I must have missed something, correct?

**Comment by sommercharles** [comment]
Here is an attempt to better explain this issue using the Math tutorial and based on JHDeerin issue #186 template.

### Bug description:

Importing and using an xml enum type in a serializable successfully compiles, but does not create top dictionary enum entry, leading to GDS unable to find the referenced enum.

### Steps to reproduce bug:

Clone and install F' master branch per installation instructions
Follow Math tutorial up to the end
Add MathOpSerEnumAi.xml in MathTypes folder with the following code:

	<enum namespace="Ref" name="MathOpSer">
	    <item name="ADD"/>
	    <item name="SUB"/>
	    <item name="MULT"/>
	    <item name="DIVIDE"/>
	</enum>

Add MathOpSerEnumAi.xml in CMakeLists.txt file of MathTypes:

	set(SOURCE_FILES
	  "${CMAKE_CURRENT_LIST_DIR}/MathOpSerializableAi.xml"
	  "${CMAKE_CURRENT_LIST_DIR}/MathOpSerEnumAi.xml"
	)
	register_fprime_module()

Include enum and replace declaration of member "op" of MathOpSerializableAi.xml by MathOpSer:

	<serializable namespace="Ref" name="MathOp">
	    <import_enum_type>Ref/MathTypes/MathOpSerEnumAi.xml</import_enum_type>
	    <comment>
	    This value holds the values of a math operation
	    </comment>
	    <members>
	        <member name="val1" type="F32"/>
	        <member name="val2" type="F32"/>
	        <member name="op" type="Ref::MathOpSer"/>
	        <member name="result" type="F32"/>
	    </members>
	</serializable>

Add MathOpSer reference in Ref/MathReceiver/MathReceiverComponentImpl.cpp mathIn handler:

 ```
 void MathReceiverComponentImpl ::
    mathIn_handler(
        const NATIVE_INT_TYPE portNum,
        F32 val1,
        F32 val2,
        MathOperation operation
    )
  {
    // declare result serializable
    Ref::MathOp op;
    F32 res = 0.0;
    switch (operation) {
        case MATH_ADD:
            op.setop(MathOpSer::ADD);
            res = (val1 + val2)*this->m_factor1;
            break;
        case MATH_SUB:
            op.setop(MathOpSer::SUB);
            res = (val1 - val2)*this->m_factor1;
            break;
        case MATH_MULTIPLY:
            op.setop(MathOpSer::MULT);
            res = (val1 * val2)*this->m_factor1;
            break;
        case MATH_DIVIDE:
            op.setop(MathOpSer::DIVIDE);
            res = (val1 / val2)*this->m_factor1;
            break;
        default:
            FW_ASSERT(0,operation);
            break;
    }
    Fw::ParamValid valid;
    res = res/paramGet_factor2(valid);

    op.setval1(val1);
    op.setval2(val2);
    op.setresult(res);
    this->log_ACTIVITY_HI_MR_OPERATION_PERFORMED(op);
    this->tlmWrite_MR_OPERATION(op);
    this->mathOut_out(0,res);
  }
```

In Ref, run `fprime-util purge` to start on a clean build

In Ref, run `fprime-util generate`
Verify that the enum was found: 
`Found enum: MathOperation in /home/csommer/Dolce-Software/Ref/MathTypes/MathOpSerEnumAi.xml
`

In Ref, `run fprime-util install`

In Ref, `run fprime-gds -d .`
The error is: 
`fprime_gds.common.data_types.exceptions.GseControllerParsingException: Parsing error: Could not find type Ref::MathOpSer!
`

In Ref/RefTopologyAppDictionary.xml, observe that MathOp Serializable is mentioned, but not Ref::MathOpSer itself:

	<serializable type="Ref::MathOp">
	  <members>
	    <member name="val1" format_specifier="%g" type="F32"/>
	    <member name="val2" format_specifier="%g" type="F32"/>
	    <member name="op" format_specifier="%s" type="Ref::MathOpSer"/>
	    <member name="result" format_specifier="%g" type="F32"/>
	  </members>
	</serializable>

Manually add MathOpSer in Ref/RefToplogyAppDictionary.xml (with default values):

	<enum type="Ref::MathOpSer">
	  <item name="ADD" value="0"/>
	  <item name="SUB" value="1"/>
	  <item name="MULT" value="2"/>
	  <item name="DIVIDE" value="3"/>
	</enum>

Launching gds once again now works

### Suspected bug location:

https://github.com/nasa/fprime/blob/f28c92e31d58e7e44bff09ad57d574ca5d5e91c7/Autocoders/Python/bin/codegen.py#L332

Only included serializable are added to the dictionnary. 
Included enums are not added (by design?).

### Suggested solution:

Add enum inclusion parsing (copy of existing enum parsing) in codegen.py at two locations:

For included enums in the xml component referenced at the xTopologyApp.xml https://github.com/nasa/fprime/blob/f28c92e31d58e7e44bff09ad57d574ca5d5e91c7/Autocoders/Python/bin/codegen.py#L331

                # check for included enum XML in referenced XML at top
                if(parsed_xml_dict[comp_type].get_enum_type_files() != []):
                    enum_file_list = parsed_xml_dict[comp_type].get_enum_type_files()
                    for enum_file in enum_file_list:
                        enum_file = search_for_file("Enum", enum_file)
                        enum_model = XmlEnumParser.XmlEnumParser(enum_file)
                        enum_elem = etree.Element("enum")
                        enum_type = enum_model.get_namespace() + "::" + enum_model.get_name()
                        enum_elem.attrib["type"] = enum_type
                        members_elem = etree.Element("members")
                        for (member_name, member_value, member_comment) in enum_model.get_items():
                            enum_mem = etree.Element("item")
                            enum_mem.attrib["name"] = member_name
                            # keep track of incrementing enum value
                            if member_value != None:
                                enum_value = int(member_value1)

                            enum_mem.attrib["value"] = "%d"%enum_value
                            enum_value = enum_value + 1
                            if member_comment != None:
                                enum_mem.attrib["description"] = member_comment
                            enum_elem.append(enum_mem)
                            enum_list.append(enum_elem)

And for included enums in included serializables https://github.com/nasa/fprime/blob/f28c92e31d58e7e44bff09ad57d574ca5d5e91c7/Autocoders/Python/bin/codegen.py#L339

                        
                        # check for included enum XML in included serializable XML
                        if(len(serializable_model.get_include_enums()) != 0):
                            enum_file_list = serializable_model.get_include_enums()
                            for enum_file in enum_file_list:
                                enum_file = search_for_file("Enum", enum_file)
                                enum_model = XmlEnumParser.XmlEnumParser(enum_file)
                                enum_elem = etree.Element("enum")
                                enum_type = enum_model.get_namespace() + "::" + enum_model.get_name()
                                enum_elem.attrib["type"] = enum_type
                                members_elem = etree.Element("members")
                                for (member_name1, member_value1, member_comment1) in enum_model.get_items():
                                    enum_mem = etree.Element("item")
                                    enum_mem.attrib["name"] = member_name1
                                    # keep track of incrementing enum value
                                    if member_value1 != None:
                                        enum_value = int(member_value1)

                                    enum_mem.attrib["value"] = "%d"%enum_value
                                    enum_value = enum_value + 1
                                    if member_comment1 != None:
                                        enum_mem.attrib["description"] = member_comment1
                                    enum_elem.append(enum_mem)
                                    enum_list.append(enum_elem)


### Comment:

There's another issue linked to this one if I try to use an included enum straight into an element of a component (instead of using type="ENUM" etc.): the header of the enum is generated, but it is not included in the autocoded component header. 
Can we use enums like this?

**Comment by LeStarch** [comment]
@sommercharles do you want to make a PR for the suggested fix?

**Comment by sommercharles** [comment]
@LeStarch sure thing. I'll raise another issue for the header inclusion bug I mentioned once I have a fix for it.

**Comment by sommercharles** [comment]
So regarding the other issue I mentioned, I browsed through the autocoder and it looks like I might be misusing enums in this case.

It doesn't seem that you can use import_enum in a component and use it as is.
A workaround I found is declaring a serializable with a single enum member and use that serializable several time through the component.

Too bad that we cannot re-use ENUM over several component members. Maybe someone can confirm?

Other than that, I think we can close this issue.

**Comment by LeStarch** [comment]
This is an issue, and we'll fix it.

**Comment by sommercharles** [comment]
Got it, thank you.

**Comment by LeStarch** [comment]
Closing this issue.  Tracking bug separately.
