### ISSUE TITLE
CI CppCheck/CppScan failing

### ISSUE THREAD

**Issue by thomas-bc** [nasa/fprime#1931]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|   |
---
## Problem Description

See https://github.com/nasa/fprime/actions/runs/4390265240/jobs/7688586298. CI is failing on CppLint and CppCheck scans because the `--force` option of Microsoft's SARIF-Multitool converter is not available anymore. Probably an update of the convert tool.

Fix is likely going to be to simply remove the option (or use the older version of the tool?), but we should also check what it used to be doing to be sure we're not losing any functionality.

**Comment by thomas-bc** [comment]
@ThibFrgsGmz do you want to take a look into that or should I?

**Comment by ThibFrgsGmz** [comment]
@thomas-bc I'll take a look tonight. While browsing the github repo I see some people get the same issue: https://github.com/microsoft/sarif-sdk/issues/2638

**Comment by ThibFrgsGmz** [comment]
For the time being, we may revert to the previous version, i.e. 4.0.0, by replacing the installation commands:

https://github.com/nasa/fprime/blob/bbf049ecbd82895a0c2de3e5d126dcea55618ceb/.github/workflows/cpplint-scan.yml#L33

and 

https://github.com/nasa/fprime/blob/bbf049ecbd82895a0c2de3e5d126dcea55618ceb/.github/workflows/cppcheck-scan.yml#L32
 with `npm i @microsoft/sarif-multitool@4.0.0`

**Comment by thomas-bc** [comment]
Fixed - Thanks for working on this!
