### ISSUE TITLE
Revisit Python Packaging

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#1995]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|   |
---
## Problem Description

Some of our packages are in violation of PEP-517.  We should consider revising.  See:  https://github.com/fprime-community/fprime-workshop-led-blinker/issues/2

**Comment by thomas-bc** [comment]
Will likely flow down from https://github.com/nasa/fprime/issues/2321

**Comment by LeStarch** [comment]
Native image packing has been corrected and tested!
