### ISSUE TITLE
Publish aarch64/linux FPP Packages

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#1996]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

Users running on arm hardware need aarch64 compilations of the FPP tools. This is critical for running in a VM on macOS with the new arm hardware.

**Comment by jwest115** [comment]
Setup odroid as fprime-community GitHub action runner and tested PR trigger in [Test PR - Add odroid runner #17
]( https://github.com/fprime-community/fpp/actions/runs/4985958534). Need to confirm release trigger works as expected and create PR for review.

**Comment by jwest115** [comment]
PR was approved and merged, closing this issue
