### ISSUE TITLE
Fix GTest Usage

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#1998]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|   |
---
## Problem Description

Downloading GTest during the generate phase is problematic:

1. It puts build and code in the source tree
2. Multiple deployments fight over it
3. It requires internet

**Comment by ThibFrgsGmz** [comment]
Also see more info here: https://github.com/nasa/fprime/discussions/1819#discussioncomment-4759041

**Comment by thomas-bc** [comment]
Some things to remember:
- Update tools to do submodule update --init --recursive
- Remove the googletest.cmake stuff
