### ISSUE TITLE
Add LED Blinker as a Formal Tutorial

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#1999]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

Two steps:
- [x] Add it to the tutorial landing page (documentation)
- [x] Build in CI to ensure it stays current

**Comment by thomas-bc** [comment]
- LedBlinker now shows in https://nasa.github.io/fprime/Tutorials/README.html
- Added CI check as part of https://github.com/nasa/fprime/pull/2049

Done!
