### ISSUE TITLE
Add Hello World Sample Deployment to CI

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#2001]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

Add a sample deployment for hello-world to CI.  May consider moving tutorial text to hello-world as was done with LED Blinker.

Depends on #2000

**Comment by thomas-bc** [comment]
We are now building LedBlinker as part of CI checks. See https://github.com/nasa/fprime/pull/2049/files
Is that enough for now or do we want others as well? @LeStarch

**Comment by LeStarch** [comment]
We need a bunch, but none are ready today.  @hAkselS please update use when we can add Hello World and Math components to CI. @jwest115 let us know when system reference is ready for CIing
