### ISSUE TITLE
Add F´ Subprojects to `fprime-util new`

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#2005]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

Add subprojects (see #2004 ) to `fprime-uitl new`.  Might be a special flag for deployments.  Might be a new top-level item.

**Comment by thomas-bc** [comment]
#2004 was closed as will-not-implement, closing this one as well.
