### ISSUE TITLE
Downlinking 0-length files throws a division-by-0 error

### ISSUE THREAD

**Issue by JHDeerin** [nasa/fprime#201]
## Bug Description

Downlinking a 0-length file (like those created with the Unix `touch` command) causes a "division by 0" error in the GDS Python code.

## Steps to reproduce

1. Run the `Ref` application via `fprime-gds`
2. Create a 0-length file via `touch ~/test.txt`
3. Go to the `Commanding` tab in the GDS GUI and downlink the newly-created file by running the `fileDownlink.fileDownlink_sendFile` command, with sourceFileName `/home/<username here>/test.txt` and destFileName `/test.txt`
4. After running the command, an error should appear in your terminal

## Suspected Bug Location

The relevant bug appears to be in [line 232 of helpers.py](https://github.com/nasa/fprime/blob/de2e42157067ca8043d1ce764a000fa510ca8d48/Gds/src/fprime_gds/executables/cli.py#L436), as shown below:

```python
                "percent": int(item.seek / item.size * 100.0),
```

Since `item.size` doesn't appear to be checked before it's used, a 0-length file will always cause an error here.

## Suggested Solution

Per @LeStarch , replace the line in question with the following to check for this 0-length file case:

```python
"percent": 100 if item.size == 0 else int(item.seek / item.size * 100.0),
```

**Comment by LeStarch** [comment]
This is merged into our pre-release branch.
