### ISSUE TITLE
Clean Up Os CMake

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#2012]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

Clean up the OS CMake setup for micro-fs (separate libraries).

**Comment by LeStarch** [comment]
Note: Os would become an interface library for multiple back-end components.

**Comment by thomas-bc** [comment]
Is this a duplicate from https://github.com/nasa/fprime/issues/1685 ?

**Comment by Meganbrentshandacrain** [comment]
> Is this a duplicate from https://github.com/nasa/fprime/issues/1685 ?

Yes
