### ISSUE TITLE
Command-line MathOp port creation in Math-Component tutorial fails

### ISSUE THREAD

**Issue by NoahBraasch** [nasa/fprime#2019]
| | |
|:---|:---|
|**_F´ Version_**|3.2.0 |
|**_Affected Component_**| CLI Port Creation  |
---
## Problem Description
Step 3.1 of the math component tutorial fails when using the command-line port creation tool.

## How to Reproduce

$ fprime-util new --port
Port Name [ExamplePort]: MathOp
Short Description [Example usage of port]: Port for math operations
Directory Name [.]: MathPorts
Port Namespace [Ref]:
Would you like to add an argument?: y
Argument name: val1
Argument type (Valid primitive types are: I8, I16, I32, U8, U16, U32, F32, F64, NATIVE_INT_TYPE, NATIVE_UNIT_TYPE, and POINTER_CAST. You may also use your own user-defined types): F32
Short description of argument: First operand
Would you like to add another argument?: y
Argument name: op
Argument type (Valid primitive types are: I8, I16, I32, U8, U16, U32, F32, F64, NATIVE_INT_TYPE, NATIVE_UNIT_TYPE, and POINTER_CAST. You may also use your own user-defined types): MathOp
Short description of argument: Operation
Would you like to add another argument?: y
Argument name: val2
Argument type (Valid primitive types are: I8, I16, I32, U8, U16, U32, F32, F64, NATIVE_INT_TYPE, NATIVE_UNIT_TYPE, and POINTER_CAST. You may also use your own user-defined types): F32
Short description of argument: Second operand
Would you like to add another argument?: n
...
[ERROR] Failed to create port. CMake erred with return code 2

## Expected Behavior

A successful port creation. 

## Note
The port does become operational when fpp-from-xml is used on the output

**Comment by LeStarch** [comment]
We are in the process of discontinuing `fprime-util --new port`.  The current process is:
```
mkdir -p MyPort
touch MyPort/MyPort.fpp
```
Then design the port using the FPP modeling language. Eventually, we will replace this with `fprime-uitl new --module` which will create the basic structure for any of the autocode-only FPP types (Ports, Structs, Enums, and Arrays).
