### ISSUE TITLE
Autogenerate CLI Documentation (e.g. --help)

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#2027]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

Host the output of our CLI tools `--help` option, automatically, in our online API documentation.

**Comment by thomas-bc** [comment]
Rationale: see https://github.com/nasa/fprime/pull/2025

**Comment by thomas-bc** [comment]
Not planned. `--help` text can be printed out through the CLI... I don't see a reason to host that on the website
