### ISSUE TITLE
MVP: Baremetal System Reference

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#2029]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

Minimal viable product:
- Runs on feather
- CMD NO_OP, Events, Telemetry
- RG cycles at 1000Hz
- Has config to fit feather sized boards

**Comment by ethancheez** [comment]
[Baremetal Reference Repo](https://github.com/ethancheez/fprime-baremetal-reference/tree/dev)

- [x] Runs on feather
- [x] CMD NO_OP, Events, Telemetry
- [x] RG cycles at 1000Hz
- [x] Has config to fit feather sized boards

Additional Features:
- [x] Size utility for F' components/deployments. Recommends config settings for:
     - TLMCHAN_NUM_TLM_HASH_SLOTS
     - TLMCHAN_HASH_BUCKETS
     - CMD_DISPATCHER_DISPATCH_TABLE_SIZE
- [x] Uses a new TlmLinearChan component that reduces memory usage by 50% compared to Svc::TlmChan
- [x] Cookiecutter template for Arduino deployment
