### ISSUE TITLE
Build F´ Targets Wrapper

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#2033]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

Make a convience helper in fprime util for building targets directly.  E.g. Replace `cd <build>; make <target>` with `fprime-util build --target <target>`.

**Comment by LeStarch** [comment]
Fixed by nasa/fprime-tools#288

**Comment by thomas-bc** [comment]
Fixed by https://github.com/nasa/fprime-tools/pull/228
