### ISSUE TITLE
Remove in-source build of codegen templates

### ISSUE THREAD

**Issue by sobkulir** [nasa/fprime#2043]
| | |
|:---|:---|
|**_F´ Version_**| devel |
|**_Affected Component_**| Autocoder, build |
---
## Feature Description

Currently, the `codegen` templates are build in-source under `Autocoders/Python/src/fprime_ac/generators/templates/**/**.py`. Although, since there's a plan to ditch Autocoder in favor of F', maybe this becomes obsolete soon.

## Rationale

It's bad to mix sources with builds...

**Comment by LeStarch** [comment]
Aggreed!

**Comment by LeStarch** [comment]
Closing as v2.0.0 FPP will remove the need for these files.
