### ISSUE TITLE
Better linkage to FPP docs in F´ User Guide

### ISSUE THREAD

**Issue by thomas-bc** [nasa/fprime#2050]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**| Docs |
---
## Feature Description

FPP has **very comprehensive** documentation in their [wiki](https://github.com/fprime-community/fpp/wiki), with a [User Guide](https://fprime-community.github.io/fpp/fpp-users-guide.html), a [Language Spec](https://fprime-community.github.io/fpp/fpp-spec.html), etc... this is amazing, and I have not seen it mentioned in the F´ docs other than very briefly in the [v3 Migration Guide](https://nasa.github.io/fprime/UsersGuide/user/v3-migration-guide.html)

We very much need to reference those resources better in the F´ docs, in the same fashion we reference XML in our [User Guide](https://nasa.github.io/fprime/UsersGuide/guide.html).
It would be good to at least have a page on FPP in the User Guide, linking to these external resources.

**Comment by samwardbiddle** [comment]
I am a new contributor and plan to work on this as my first issue.
