### ISSUE TITLE
F´ GDS AttributeError: module 'flask.json' has no attribute 'JSONEncoder'

### ISSUE THREAD

**Issue by jwest115** [nasa/fprime#2053]
| | |
|:---|:---|
|**_F´ GDS Version_**| v3.2.0 |
|**_Affected Component_**|   |
---
## Problem Description

Received module 'flask.json' has no attribute 'JSONEncoder’ when attempting to start F Prime GDS in a python 3.9.6 virtual environment. It appears we’ll need to use an older version of flask (error received with Flask v2.3.2)? See https://stackoverflow.com/questions/76107450/flask-attributeerror-module-flask-json-has-no-attribute-jsonencoder

Uninstalled the flask version that was installed when installing fprime-gds, installed Flask v2.2.3, and confirmed the GDS started without error.

**Comment by LeStarch** [comment]
@jwest115 @thomas-bc good catch!  Yes, we should lock the version for now and prepare for a PR to fix this!

**Comment by jwest115** [comment]
PR ready for review https://github.com/fprime-community/fprime-gds/pull/132

**Comment by jwest115** [comment]
PR was merged, will close this issue.
