### ISSUE TITLE
FPP Build Native Image Action - ubuntu-18.04 action runner no longer supported 

### ISSUE THREAD

**Issue by jwest115** [nasa/fprime#2055]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

The Ubuntu 18.04 Actions runner image will begin deprecation on 2022/08/08 and will be fully unsupported by 2023/04/03 - see https://github.com/actions/runner-images/issues/6002

Will need to update label to one of the following: ubuntu-latest, ubuntu-20.04, or ubuntu-22.04

**Comment by LeStarch** [comment]
This is a more serious problem than it first appears.  In short lib C and kernel versions are too new when building on `ubuntu-20.04` for some of our packages (FPP) and thus we needed to run on `18.04`.\

**Comment by jwest115** [comment]
Registered RH8 box as a self-hosted runner for building the packages that were previously built on ubuntu-20.04. 
- Jobs completed successfully: https://github.com/fprime-community/fpp/actions/runs/5206201594
- PR: https://github.com/fprime-community/fpp/pull/257

**Comment by jwest115** [comment]
PR was approved and merged, closing this issue
