### ISSUE TITLE
NodeJS -> Flask Transition for FPP Visualizer

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#2060]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

Deploy Visualizer as Flask APP.

**Comment by thomas-bc** [comment]
Opened the above PR for the migration. I am wondering whether fprime-visual should be kept as a separate repo, or if it would be a good idea to merge it in fprime-tools as a separate package? Distributing everything under a single pip package does sound appealing to me.

**Comment by thomas-bc** [comment]
Released Flask version on pypi: https://pypi.org/project/fprime-visual/

See https://github.com/fprime-community/fprime-visual for instructions
