### ISSUE TITLE
Baremetal Reference: Communications

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#2063]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

A quick description of the requested feature.

## Rationale

A rationale for why the feature should be implemented in F´.

**Comment by ethancheez** [comment]
[RFM69 Component](https://github.com/ethancheez/fprime-baremetal-reference/tree/dev/Components/Radio/RFM69)
[RadioPassthrough Deployment](https://github.com/ethancheez/fprime-baremetal-reference/tree/dev/RadioPassthrough)
