### ISSUE TITLE
TopoFactory.py highest command ID check has no None check

### ISSUE THREAD

**Issue by AaronMcDaniel** [nasa/fprime#207]
Autocoders/Python/src/fprime_ac/models/TopoFactory.py:222 has no None check in case highest_id was not assigned. This is different from the checks on lines 193 and 207. I had a deployment that failed because it had no events or telemetry and only had commands. 
I fixed it by adding a None check like on the other lines. Should this change be made or is it there for a reason?
I can make a PR if it helps explain what I'm questioning and suggesting.

**Comment by LightPunster** [comment]
I had a similar issue with my deployment and can confirm that this suggestion works. I'd like to add that the correction should also be made on lines 238, 254, and 269 in order to support components with parameters but no events, telemetry, or commands.

**Comment by AaronMcDaniel** [comment]
I added PR #209, which includes LightPunster's recommended fixes as well

**Comment by LeStarch** [comment]
Merged in.
