### ISSUE TITLE
Hardcoded buffer size in TcpClient/TcpDriver/Udp

### ISSUE THREAD

**Issue by thomas-bc** [nasa/fprime#2074]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|   |
---
## Problem Description

See https://github.com/nasa/fprime/blob/da4b1daae77f46a940733fbb20a4be8efd3a89b8/Drv/TcpClient/TcpClientComponentImpl.cpp#L50-L51

We should do like UARTDriver (see [here](https://github.com/nasa/fprime/blob/da4b1daae77f46a940733fbb20a4be8efd3a89b8/Drv/LinuxUartDriver/LinuxUartDriver.cpp#L46-L47)) and configure the size at configure() time so that it can be configured for each instance in the topology. Set a default size of 1024 so that it doesn't break any existing code.

**Comment by LeStarch** [comment]
Also in UDP and possibly UART.  Should be a configuration parameter (on startup).

**Comment by menaman123** [comment]
So would a fix be having an allocation parameter in the getBuffer method?

**Comment by LeStarch** [comment]
@menaman123 the fix would be to add an "allocation size" to the `configure` method:

https://github.com/nasa/fprime/blob/da4b1daae77f46a940733fbb20a4be8efd3a89b8/Drv/TcpClient/TcpClientComponentImpl.cpp#L32-L36

**Comment by bdshenker** [comment]
This issue appears to have been fixed in commit 7FF002C by menamen123:

```
TcpClientComponentImpl.hpp
  PROTECTED: FwSizeType m_allocation_size;
  SocketIpStatus configure(const char* hostname,
                             const U16 port,
                             const U32 send_timeout_seconds = SOCKET_SEND_TIMEOUT_SECONDS,
                             const U32 send_timeout_microseconds = SOCKET_SEND_TIMEOUT_MICROSECONDS,
                             FwSizeType buffer_size = 1024);
TcpClientComponentImpl.cpp
  Fw::Buffer TcpClientComponentImpl::getBuffer() {
      return allocate_out(0, static_cast<U32>(m_allocation_size));
  }
```
If I am correct then this ticket can now be closed per GIT ticket # 2759.

**Comment by LeStarch** [comment]
@bdshenker the above ticket did resolve the problem in TcpClient, but not TcpServer nor Udp.

https://github.com/nasa/fprime/blob/0e4b4c2aa219ed23ac7fe03b6b4196146ae7e8e3/Drv/TcpServer/TcpServerComponentImpl.cpp#L50

**Comment by bdshenker** [comment]
Got it. Let me fix the other two.

From: M Starch ***@***.***>
Sent: Monday, October 28, 2024 5:55 PM
To: nasa/fprime ***@***.***>
Cc: Shenker, Boris D (US 348C) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [nasa/fprime] Hardcoded buffer size in TcpClient/TcpDriver/Udp (Issue #2074)


@bdshenker<https://urldefense.us/v3/__https:/github.com/bdshenker__;!!PvBDto6Hs4WbVuu7!ORjEyfqKG0YBosk6YTSLhzmWiqP-LZowUDCJnu7m8-T1TwapMkTix5jckU5SBvEp5dr-__50wu9rbLs8-wmRbftPmg5cDt01XQ$> the above ticket did resolve the problem in TcpClient, but not TcpServer nor Udp.

https://github.com/nasa/fprime/blob/0e4b4c2aa219ed23ac7fe03b6b4196146ae7e8e3/Drv/TcpServer/TcpServerComponentImpl.cpp#L50<https://urldefense.us/v3/__https:/github.com/nasa/fprime/blob/0e4b4c2aa219ed23ac7fe03b6b4196146ae7e8e3/Drv/TcpServer/TcpServerComponentImpl.cpp*L50__;Iw!!PvBDto6Hs4WbVuu7!ORjEyfqKG0YBosk6YTSLhzmWiqP-LZowUDCJnu7m8-T1TwapMkTix5jckU5SBvEp5dr-__50wu9rbLs8-wmRbftPmg584uRD7A$>

**Comment by bdshenker** [comment]
@LeStarch I completed Git#2074 and reran regression suite locally.
However, when making pull request, one of the integration tests failed. 
Please advise how I should proceed.

**Comment by LeStarch** [comment]
Closing as complete.
