### ISSUE TITLE
Improper order of namespace closing brackets

### ISSUE THREAD

**Issue by nathancheek** [nasa/fprime#208]
When nested namespaces are used, the autocoder generates component template `.cpp` and `.hpp` files with incorrect ordering of closing bracket comments. Example:

```
namespace Drv {
namespace support {
...
} // end namespace Drv
} // end namespace support
```

These are the problematic lines:
https://github.com/nasa/fprime/blob/f28c92e31d58e7e44bff09ad57d574ca5d5e91c7/Autocoders/Python/src/fprime_ac/generators/templates/impl/hpp.tmpl#L108
https://github.com/nasa/fprime/blob/f28c92e31d58e7e44bff09ad57d574ca5d5e91c7/Autocoders/Python/src/fprime_ac/generators/templates/impl/cpp.tmpl#L112

If there's a way to direct the parser to loop through the list backwards, that would solve this problem.

**Comment by LeStarch** [comment]
Fixed.
