### ISSUE TITLE
Missing Brace

### ISSUE THREAD

**Issue by hAkselS** [nasa/fprime#2080]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|   |
---
## Problem Description

In docs/Tutorials/HelloWorld/HelloWorld.md on line 178 there is a missing "}". The missing brace causes an error when building and may confuse F' beginners.

**Comment by LeStarch** [comment]
Good catch!  Will you fix this as you migrate the docs to the new repo?

**Comment by hAkselS** [comment]
Yes!

**Comment by thomas-bc** [comment]
Fixed in https://github.com/fprime-community/fprime-tutorial-math-component
