### ISSUE TITLE
FPrime ground system bool parsing

### ISSUE THREAD

**Issue by timcanham** [nasa/fprime#2086]
| | |
|:---|:---|
|**_F´ Version_**| 3.x |
|**_Affected Component_**| n/a  |
---
## Problem Description

If a command argument is specified as boolean and an integer is sent, the GDS gives a cryptic "unknown error" message.

## How to Reproduce

1. Specify a command argument as `bool`
2. Fill in the argument with an non-boolean (can be integer, float, character...)
3. Red Text `Unknown Error` appears beneath command field.

## Expected Behavior

Should give an error saying it wasn't `true` or `false`.

**Comment by LeStarch** [comment]
The GDS now does a drop-down for bools and won't allow non-enumerated True/False to be sent.
