### ISSUE TITLE
Max id for instance conflicts with base id for another instance

### ISSUE THREAD

**Issue by Daifaizonaldridge** [nasa/fprime#2093]
| | |
|:---|:---|
|**_F´ Version_**| 3.2.0 | 
|**_Affected Component_**|  MathSender |
---
## Problem Description
I am doing the math component tutorial and on problem 6.2 for unconnected ports I keep getting this error when i enter the command fprime-util fpp-check -u unconnected.txt where it says "max ID 3587 for instance mathSender conflicts with base ID 3584 for instance typeDemo" and tells where each instance is defined.

Terminal:
(venv) djaldridge@LAPTOP-4BBALQ2L:~/fprime/Math2C/fprime/Ref/Top$ fprime-util fpp-check -u unconnected.txt
fpp-check

Result:
error: max ID 3587 for instance mathSender conflicts with base ID 3584 for instance typeDemo
mathSender is defined here
/home/djaldridge/fprime/Math2C/fprime/Ref/Top/instances.fpp: 92.4
   instance mathSender: Ref.MathSender base id 0xE00 \
   ^
typeDemo is defined here
/home/djaldridge/fprime/Math2C/fprime/Ref/Top/instances.fpp: 90.4
   instance typeDemo: Ref.TypeDemo base id 0x0E00

End result;
## How to Reproduce

1.  do the math component tutorial all the way to 6.2
2.  add the component instances to the topology
3.  packetize the telemetry channels

## Expected Behavior
it's supposed to create a text file of all the unconnected ports. 
 
A description of the expected behavior.
when I type the command fprime-util fpp-check -u unconnected.txt, the text file should be created and be located in the Ref/Top directory.

**Comment by LeStarch** [comment]
Should be fixed in the tutorials.
