### ISSUE TITLE
Run LedBlinker (and others?) on self-hosted agents

### ISSUE THREAD

**Issue by thomas-bc** [nasa/fprime#2102]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

Following up on https://github.com/nasa/fprime/issues/2000, we want to add pretty much the same, but to build with cross-compilers and run on our self-hosted agents.
Might be worth creating a second reusable workflow like project-builder with cross compilers, but it might be easier to skip that step if only LedBlinker is intended to be ran on RPIs.

## Rationale

Moar tests, on RaspberryPi this time.

**Comment by LeStarch** [comment]
Run on:
1. odroid
2. RPI

and latest F´
