### ISSUE TITLE
Per-Deployment Override of AcConstants

### ISSUE THREAD

**Issue by SterlingPeet** [nasa/fprime#211]
How can the contents of the [AcConstants.ini](https://github.com/nasa/fprime/blob/master/Fw/Cfg/AcConstants.ini) file be overridden, such that two different deployments within the same project can have different optimizations?  This could be important if a project has two deployments that interact, but have very different execution platforms.

**Comment by LeStarch** [comment]
This is implemented and will come as part of the next release!

**Comment by LeStarch** [comment]
This is fixed.  Requires hotfix 1.5.2.
