### ISSUE TITLE
F' with FreeRTOS / Zephyr

### ISSUE THREAD

**Issue by ethancheez** [nasa/fprime#2111]
Deploy F' on hardware, or as a QEMU simulation, running FreeRTOS / Zephyr

**Comment by ethancheez** [comment]
[https://github.com/ethancheez/fprime-zephyr-led-blinker](https://github.com/ethancheez/fprime-zephyr-led-blinker)

**Comment by thomas-bc** [comment]
Moved over to fprime-community! https://github.com/fprime-community/fprime-zephyr-led-blinker
