### ISSUE TITLE
Component directory in tutorials

### ISSUE THREAD

**Issue by hAkselS** [nasa/fprime#2113]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|   |
---
## Problem Description

The math component and hello world tutorials have users create a "Components" directory, but as of the newest F', a Components directory is autogenerated with F' util new --project.

**Comment by thomas-bc** [comment]
This has already been fixed in HelloWorld (see https://fprime-community.github.io/fprime-tutorial-hello-world/docs/HelloWorld.html)

**Comment by thomas-bc** [comment]
Fixed in MathComponent as well
