### ISSUE TITLE
Math tutorial deployment naming issue 

### ISSUE THREAD

**Issue by hAkselS** [nasa/fprime#2114]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|   |
---
## Problem Description

In the math component tutorial and reference, the deployment is named "Deployment". We would like to rename the deployment to "MathDeployment" to be more descriptive & to match hello world.

**Comment by thomas-bc** [comment]
Closing as this was corrected in https://github.com/fprime-community/fprime-tutorial-math-component
