### ISSUE TITLE
Migrate tutorials to new build structure

### ISSUE THREAD

**Issue by hAkselS** [nasa/fprime#2115]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|   |
---
## Problem Description

The tutorials were written such that the user is expected to build their deployments from the deployment directory, but modern F' has users build deployments in the project's root directory.

**Comment by thomas-bc** [comment]
- [x] HelloWorld done (https://github.com/fprime-community/fprime-tutorial-math-component/blob/main/Deployment/CMakeLists.txt)
- [x] MathComponent done (https://github.com/fprime-community/fprime-tutorial-math-component/blob/main/Deployment/CMakeLists.txt)
- [ ] LedBlinker, To be done
