### ISSUE TITLE
Graviation compass system ref component

### ISSUE THREAD

**Issue by hAkselS** [nasa/fprime#2118]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

Create an application that takes data from the IMU and adjusts the position of a rotor so that the arrow attached to the rotor points straight up.

## Rationale

This component will demonstrate control data flow.

**Comment by thomas-bc** [comment]
https://github.com/hAkselS/fprime-system-reference/tree/dev/actuator

**Comment by thomas-bc** [comment]
https://github.com/fprime-community/fprime-system-reference/tree/dev/actuator
