### ISSUE TITLE
`Components` folder doesn't exist in newly created project folder

### ISSUE THREAD

**Issue by capsulecorplab** [nasa/fprime#2132]
| | |
|:---|:---|
|**_F´ Version_**| v3.2.0 |
|**_Affected Component_**|   |
---
## Problem Description

After following [Hello World: Creating an F´ Project](https://fprime-community.github.io/fprime-tutorial-hello-world/docs/NewProject.html) and starting on [Creating the Hello World Component](https://fprime-community.github.io/fprime-tutorial-hello-world/docs/HelloWorld.html#creating-the-hello-world-component), tutorial states "The project contains a Components/ directory to create components in.", but no such Components directory exists

## How to Reproduce

1. generate F' Project as per [Hello World: Creating an F´ Project](https://fprime-community.github.io/fprime-tutorial-hello-world/docs/NewProject.html)

## Expected Behavior

`MyProject` should contain a `Components/` directory

**Comment by thomas-bc** [comment]
This should be fixed by using the latest v3.3 release. I will close this issue, feel free to comment/reopen should you have issues getting it working again.
