### ISSUE TITLE
Experiencing Problems Launching the GDS in a Cloned Project on a Separate User-Name (and Machine) 

### ISSUE THREAD

**Issue by John-P-Cargille** [nasa/fprime#2145]
| | |
|:---|:---|
|**_F´ Version_**|  fprime-tools v3.2.0; fprime-gds v3.2.1a1
|**_Affected Component_**| fprime-gds and cloned repos
---
## Problem Description

Some context for this problem, albeit from a previous point of understanding, can be found in [this](https://github.com/nasa/fprime/issues/2142) issue. The short version is that my C&DH lead created a new F' project, generated and built it, made a components folder which was empty except for a README.txt, and pushed all of these changes to a team repository. When the lead cloned the repository, they were able to create deployments and run `fprime-gds` with no issues. When the rest of the team attempted to do the same, we got at error which looked similar to the following:

<img width="846" alt="Screenshot 2023-07-18 102526" src="https://github.com/nasa/fprime/assets/116765885/c86d993a-6818-4997-a385-d65baaf7b583">

We found this to be true regardless of our linux distribution, whether or not we were in the project's virtual environment (although interestingly I learned that, when using a different project's virtual environment, one could skirt around this issue and still access the correct project through the gds), our version of fprime-tools (between 3.2.0 and 3.2.1), our version fprime-gds (between 3.2.1a1 and 3.2.0), and what branch of the repository we were on. Ultimately, my team lead suggest we try having me make a new user with the same user name as him, which--after all of the F' dependencies were installed--worked perfectly well. 
We had our suspicions that it might have been some hard-coded path dependent on the machine, but the username makes just as much sense. I made sure to check the F' User's Guide section on the F' development process, but couldn't find anything there about this. Is there a way to edit whatever is dependent on this username manually? This feels like something that would've come up for more people in the standard course of development, so maybe our project has extraneous factor we can't currently perceive.

## How to Reproduce

1. Have someone make an F' project, generate it, and build it.
2. Have the same person commit all changes to a publicly-accessible repository.
3. Have a different person clone the project, ensuring they are on an account with a different username than the person who made the project.
4. Have that second person create, generate, and build in a new deployment for the project.
5. Have that second person run the command `fprime-gds` within that deployment.

## Expected Behavior

The person trying to run the ground data system will get an error like the screenshot from above, informing them that a binary location does not exist.

EDIT: In retrospect, it seems as though we did not investigate the different versions of fprime-tools and fprime-gds closely enough. What happened as best as I can reason is that the team lead--who was using fprime-tools v3.2.0 and fprime-gds v3.2.1a1--was able to successfully run the GDS when cloning projects both he had made and other people had made, because fprime-gds v3.2.1a1 appears backwards-compatible with fprime-gds v.3.2.0. However, neither a colleague nor I was able to successfully run the cloned project my team lead had made, seemingly because fprime-gds v3.2.0 is not forwards-compatible with fprime-gds v3.2.1a1. Once I created a new user for my installation of Ubuntu, the automatically installed versions for fprime-tools and fprime-gds matched those of my team-leads, hence giving the illusion that the variable of note was the name of the user, rather than the tool versions. 
The version of fprime-tools, between v3.2.0 and v3.2.1, didn't have an impact on the ability of a given deployment to launch the GDS during our debugging, although the compiler did still given a warning about the mismatched versions when generating and building the deployment. 
Also potentially of note, I had to install a previous version of flask--going from v2.3.2 to v2.2.3--to launch the GDS successfully; it also turned out that my team lead had v2.2.2 installed from a previous unrelated project, and changing this version was also necessary to fully solve the problem for my colleague. In the one case we built a deployment on a machine running flask v2.3.2, this did not impact the ability of machines running an earlier version of flask to rebuild the deployment and run the GDS themselves.

**Comment by dav-oss** [comment]
You sure /build-artifacts/Linux/bin/ exists in your project files?

**Comment by dav-oss** [comment]
Make sure the person committing the project to repo includes the /build-artifacts/Linux/bin/ contents too.
