### ISSUE TITLE
Add enum and serializable type loaders in F-Prime Dictionary Object

### ISSUE THREAD

**Issue by mohitsingh999** [nasa/fprime#2160]
| | |
|:---|:---|
|**_F´ Version_**| 3.2.1|
|**_Affected Component_**|  |
---
## Feature Description
Adding enumeration and serializable loaders in the Dictionaries object used in F-Prime GDS. Currently, there exist loaders for commands, channels, events, and packets, but no definitions for the enum and serializable directly in the Dictionaries object. The Dictionaries object loads in the TopologyAppDictionary.xml file and converts it to a Dictionaries object in python. This object does not have the definitions for the serializable and enumeration types, even though they are present in the TopologyAppDictionary.xml file.

## Rationale

Loaders for enumerations and serializable types would allow the entire TopologyAppDictionary.xml to be encapsulated in the Dictionary object in F-Prime GDS. This would be useful in defining enumerations and serializable types externally to the F-Prime GDS, such as an OpenMCT to F-Prime GDS interface.

**Comment by thomas-bc** [comment]
Closing as we are migrating to the new JSON dictionaries
