### ISSUE TITLE
[Math Component Tutorial] create Unit Test build cache error

### ISSUE THREAD

**Issue by miaohua131** [nasa/fprime#2167]
Hi,

I'm running through the Math Component tutorial right now and while i've been able to successfully run the MathComponent deployment through the GDS, but my `fprime-util generate --ut ` is failing in MathProject directory. I seem to be getting different output than is shown in the tutorial, so I'm not sure if it's something in my code or how I'm running it. Any help would be much appreciated!

![fprime-util generate --ut_error](https://github.com/nasa/fprime/assets/138548836/d86c02a7-413b-4d46-bde0-aae92251621b)

**Comment by thomas-bc** [comment]
This should be fixed by using the latest v3.3 release. I will close this issue, feel free to comment/reopen should you have issues getting it working again.
