### ISSUE TITLE
Allow Users to Select Various `comDriver` Implementations in `fprime-util new --deployment`

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#2191]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

F´ ships with 3 Linux drivers that could be used for the `comDriver`.  Users should be given a choice on which to use.

**Comment by thomas-bc** [comment]
Done and tested! Can now generate a deployment for with comms set to be TcpClient, TcpServer or UART. GDS has been tested to handle all 3.
