### ISSUE TITLE
make ut - No rule to make target

### ISSUE THREAD

**Issue by brhs17** [nasa/fprime#22]
![fprime error 4](https://user-images.githubusercontent.com/47761126/53373519-b41dc800-3923-11e9-8a08-13071ac7ef32.JPG)
I've checked all of the makefiles and as far as I can tell they are identical to the tutorial code.

**Comment by timcanham** [comment]
This looks like something different - it looks like `Ref/MathPort` might be missing from `mk/configs/modules/modules.mk`.

**Comment by brhs17** [comment]
This is what I have, looks right.  The directory is name MathPorts.
![modulesmk](https://user-images.githubusercontent.com/47761126/53374767-5db28880-3927-11e9-95d2-c6ab605f3d38.JPG)

**Comment by timcanham** [comment]
Your `module.mk` has `MathPorts` (plural), while your `MathSender/test/ut/mod.mk` looks like it has `MathPort` (singular). I'm guessing to have to fix the `mod.mk` in `test/ut`.

**Comment by brhs17** [comment]
That wasn't the problem, my mod.mk file had it plural as well.  I see the singular call you are talking about in the error but I have no idea where it could come from.
![modmk](https://user-images.githubusercontent.com/47761126/53462078-895d6d80-3a10-11e9-8066-6d4c6f9a48e9.JPG)

**Comment by Brian-Campuzano** [comment]
Try running the following command to try to figure out where the `MathPort`  target is coming from:

```
grep -r MathPort | grep -v MathPorts
```

**Comment by brhs17** [comment]
Seems to be some document in the makefile folder that I shouldn't mess with.  Do I need to rebuild or something?
![problem 2](https://user-images.githubusercontent.com/47761126/53462770-f6720280-3a12-11e9-9de6-0a790a2982fd.JPG)

**Comment by Brian-Campuzano** [comment]
Yes I would execute a `make rebuild` in the fprime/ref directory.

In general its a good idea to rebuild the build system after changing mod.mk files.

**Comment by brhs17** [comment]
Ok, when I was trying to debug earlier I remember finding a singular MathPort somewhere and fixing it, but  I didn't realize I needed to rebuilt before it would do anything, so I ran "make rebuild" in the ref directory.  I'm getting a different error now: 
![error 5](https://user-images.githubusercontent.com/47761126/53463359-ab58ef00-3a14-11e9-9d94-1def68ff3a3d.JPG)

**Comment by Brian-Campuzano** [comment]
Looks like compilation of `Ref/MathSender/test/ut/main.c` failed but the error message is cutoff.

**Comment by brhs17** [comment]
I fixed the compiling errors, but now I seem to get a permission error when I try to `run_ut`
![permissionerror](https://user-images.githubusercontent.com/47761126/53603988-2f2fea00-3b81-11e9-805c-a90bf8647daf.JPG)

**Comment by timcanham** [comment]
You need to do a `chmod u+x runtest_LINUX` to set the executable bit to run the shell script.

**Comment by brhs17** [comment]
I'm trying to run `make ut` in Math Receiver, where I've copied the tutorial files into ut, but when I try to build it the program claims that `m_factor1` does not exist.
![makeutreceiver](https://user-images.githubusercontent.com/47761126/53612258-9eb4d200-3b9f-11e9-93f9-08d825c80573.JPG)

**Comment by brhs17** [comment]
I type `m_factor1` wrong in the set factor 1 cmd handler, but now that I've fixed it and tried to rebuild it still returns the same error.

**Comment by brhs17** [comment]
I looked through the tutorial and couldn't find a mention of m_factor1 I didn't have and the tutorial version of `MathReceieverComponentImpl.cpp` results in the same errors, and another one.

**Comment by timcanham** [comment]
I see it here:

https://github.com/nasa/fprime/blob/master/docs/Tutorials/MathComponent/MathReceiver/MathReceiverComponentImpl.hpp#L102

It looks like we need to add header file descriptions to the demo.

**Comment by brhs17** [comment]
Adding the indicated variable allows the program to build successfully.  However, running the test cases results in some extremely strange values:
![testcaseerrors](https://user-images.githubusercontent.com/47761126/53665181-b55b3780-3c38-11e9-90dd-515ed39bb2b1.JPG)
All four of the math tests failed on the same assert statement in each case.
The offending line in tester.cpp for the math cases was
`ASSERT_TLM_MR_FACTOR1S(0,1);`
and for the throttle test:
`ASSERT_TLM_MR_FACTOR1S(0,cycle+1);`

**Comment by brhs17** [comment]
The large numbers change between multiple runs.

**Comment by timcanham** [comment]
The other thing: Did you initialize the values in the constructor?

**Comment by brhs17** [comment]
When I try to add that it doesn't compile:
![constructorerror](https://user-images.githubusercontent.com/47761126/53673811-c9626180-3c57-11e9-885a-76143bf82b08.JPG)

**Comment by timcanham** [comment]
Can you post the code fragment? It should work.

**Comment by brhs17** [comment]
![fragment](https://user-images.githubusercontent.com/47761126/53673958-c025c480-3c58-11e9-961a-137fe11a1dd8.JPG)

**Comment by timcanham** [comment]
`,m_factor(0.0)`, not `,m_factor(0,0)` :)

**Comment by brhs17** [comment]
4/5 Test cases passed, but there seems to be a problem with `paramSend_factor2`
![anothererror](https://user-images.githubusercontent.com/47761126/53674620-2dd3ef80-3c5d-11e9-9460-6131e47a928e.JPG)

**Comment by timcanham** [comment]
I just re-ran the unit tests based on the code checked in to `docs/Tutorials/MathComponent`. Did you diff against that code?

**Comment by brhs17** [comment]
Ok, I didn't put in the parameter updated function, but when I put it in I get this error.
![parameterupdated](https://user-images.githubusercontent.com/47761126/53839639-14d18400-3f66-11e9-94ba-bcd8c1a37319.JPG)
I don't know how to "override a virtual function" as listed in the tutorial.

**Comment by brhs17** [comment]
There is this line in MathReceiverComponent.hpp that looks like it should be declaring the function:
![mathreceivercomphpp](https://user-images.githubusercontent.com/47761126/53840053-19e30300-3f67-11e9-9913-d9d601863822.JPG)

**Comment by timcanham** [comment]
Can you post the function definition in the .cpp file? You should also take off the `virtual` on the declaration in `MathReceiverComponent.hpp`. This error usually means something in the definition doesn't match the declaration in the header file.

**Comment by brhs17** [comment]
![paramupdated](https://user-images.githubusercontent.com/47761126/53856616-a362f700-3fa0-11e9-957c-d8ea4357539b.JPG)

**Comment by timcanham** [comment]
This should work - is this in a fork somewhere? The only thing I can think of is that the declaration is outside the class definition or something.

**Comment by timcanham** [comment]
Also, a GitHub tip: you can post code with triple tics "```" + "c++" and get nicely formatted code:

```c++
namespace Svc {

    //! \class CommandDispatcherImpl
    //! \brief Command Dispatcher component class
    //!
    //! The command dispatcher takes incoming Fw::Com packets that contain
    //! encoded commands. It extracts the opcode and looks it up in a table
    //! that is populated by components at registration time. If a component
    //! is connected to the seqCmdStatus port with the same number
    //! as the port that submitted the command, the command status will be returned.

    class CommandDispatcherImpl : public CommandDispatcherComponentBase {
        public:
            //!  \brief Command Dispatcher constructor
            //!
            //!  The constructor initializes the state of the component.
            //!  In this component, the opcode dispatch and tracking tables
            //!  are initialized.
            //!
            //!  \param name the component instance name
#if FW_OBJECT_NAMES == 1
            CommandDispatcherImpl(const char* name);
#else
            CommandDispatcherImpl();
#endif
            //!  \brief Component initialization routine
            //!
            //!  The initialization function calls the initialization
            //!  routine for the base class.
            //!
            //!  \param queueDepth the depth of the message queue for the component
            void init(
                    NATIVE_INT_TYPE queueDepth, /*!< The queue depth*/
                    NATIVE_INT_TYPE instance /*!< The instance number*/
                    ); //!< initialization function
            //!  \brief Component destructor
            //!
            //!  The destructor for this component is empty
            virtual ~CommandDispatcherImpl();
```

**Comment by brhs17** [comment]
I don't have a fork, I'm not sure where I would put it.  I'm pretty sure it is in the class definition since the ending bracket is after it.  How is the best way to let you look at the files?

**Comment by brhs17** [comment]
I uploaded my code onto a branch at this link I think: https://github.com/brhs17/fprime/tree/MathTutorial/Ref

**Comment by timcanham** [comment]
I looked at your branch, and I don't see the function definition in `MathReceiverComponent.hpp`.

**Comment by brhs17** [comment]
Ok, got it to work.  What does the Ac vs Impl files do differently, I'm not sure when I have to define things in which file, because the definitions of `parameterUpdated` are very similar between the files.  Why do I need them both?

**Comment by timcanham** [comment]
In C++ when you define a virtual function in a base class, the derived class has to redeclare it in order to override it. It's a C++ thing. In F`, we make the handlers for ports and commands a pure virtual, which requires that the derived class override it. It's a way to make sure the developer doesn't forget to implement a handler.

**Comment by brhs17** [comment]
I went through section 3 of the tutorial and the `make` command in `Ref/Top` seems successful, but I get an error trying to build Ref total
![refmakeerror](https://user-images.githubusercontent.com/47761126/53930465-585be900-405f-11e9-9de8-2cf4ca058750.JPG)

**Comment by timcanham** [comment]
Have you uploaded the changes to `/mk/configs/modules/modules.mk`? It may be a linking order issue there.

**Comment by brhs17** [comment]
My `MathTutorial` branch should be up to date.  I didn't see any changes that needed to be made to `modules.mk` in this section of the tutorial?

**Comment by timcanham** [comment]
I see the entries in your latest push. I think it is an ordering issue. You have:

```
REF_MODULES := \
	Ref/Top \
	Ref/RecvBuffApp \
	Ref/SendBuffApp \
	Ref/SignalGen \
	Ref/PingReceiver \
	Ref/MathPorts \
	Ref/MathTypes \
	Ref/MathSender \
	Ref/MathReceiver
```

It should be:

```
REF_MODULES := \
	Ref/Top \
	Ref/RecvBuffApp \
	Ref/SendBuffApp \
	Ref/SignalGen \
	Ref/PingReceiver \
	Ref/MathSender \
	Ref/MathReceiver \
	Ref/MathPorts \
	Ref/MathTypes
```

Specifically, the `Ref/MathPorts` and `Ref/MathTypes` have to be after the `Ref/MathSender` and `Ref/MathReceiver` in the link order. This is not an F` thing, it is a linker thing.

**Comment by brhs17** [comment]
Ok, I got the math tutorial mostly working.  All the math operations and factors work correctly, but the `Log Events` and 'Channel Telemetry' tabs seem to stop working once I try to call the `doMath` command.  The commands still operate correctly in the extra window, just the gio stops working correctly.
![runerror](https://user-images.githubusercontent.com/47761126/53978894-53884b00-40da-11e9-8b97-4557617e234b.JPG)

**Comment by timcanham** [comment]
Let me look into the error. This rings a bell.

**Comment by rdaruwala** [comment]
@brhs17 This can be fixed by changing the following line:

`<event id="0" name="MS_COMMAND_RECV" severity="ACTIVITY_LO" format_string="Math Cmd Recvd: %f %d %f"  >`

to

`<event id="0" name="MS_COMMAND_RECV" severity="ACTIVITY_LO" format_string="Math Cmd Recvd: %f %f %d"  >`

in `Ref/MathSender/MathSenderComponentAi.xml`
