### ISSUE TITLE
Write an Adapter and Framer Plugin Setup

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#220]
We should add an comm adapter and framer plugin setup for instantiating user's adaptations easily.

**Comment by LeStarch** [comment]
Chat with GT for their approaches.

**Comment by efriesema** [comment]
High LeStarch  I'm a Computer Science grad student working on a CubeSat project. Is somebody running this issue that they could use some help?  I know Python and C++ and I'd be willing to help make this happen. .My email is rononfilms01@gmail.com

**Comment by LeStarch** [comment]
I don't have an assignee for this ticket yet. Another user recommended we contact them for advice on "what works" for python plugin stuff before starting.

**Comment by efriesema** [comment]
Would you like me to follow up with that user and get a baseline idea of
the architecture and framework?  Do we have a basic abstract of what we
want the plugin to be able to do?
Ed Friesema
Check out my github page www.github.com/efriesema for my latest projects!
