### ISSUE TITLE
add license option when generating project scaffold with `fprime-util new --project`

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#2225]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

Option to add an [OSI](https://opensource.org/about) approved license when generating project scaffold with `fprime-util new --project` - perhaps with default to Apache 2.0 to match core fprime codebase.

## Rationale

As to allow for ease of integration and contributions as an fprime community project

**Comment by thomas-bc** [comment]
Requested by the community: see https://github.com/fprime-community/fprime-tools/issues/155

**Comment by thomas-bc** [comment]
This feels to me like one of those things that sits on the edge of whether this is the responsibility of the framework to support. My gut says no. It's very easy to add on the user/github side, most likely safer, and probably out of the scope of developing FSW/F´. 

I am tempted to vote in favor of closing this issue as "Won't implement".

@LeStarch thoughts?

**Comment by capsulecorplab** [comment]
Isn't the entire point of `fprime-tools` to encourage best practices? To omit a license option would suggest a license is more of an afterthought.

**Comment by thomas-bc** [comment]
Not planned for the time being. Although we can reconsider if more users in the community are requesting this.
