### ISSUE TITLE
Copying From LED Blinker Tutorial Includes `...`

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#2245]
When doing LED Blinker Tutorial, users often copy the `...` from one of the blocks

**Comment by thomas-bc** [comment]
e.g. in [this section](https://github.com/fprime-community/fprime-workshop-led-blinker/blob/main/docs/initial-integration.md#adding-led-component-to-the-deployment) under the topology.fpp: 
We may want to come up with a system of _"hey this `[...]` block just means there's stuff here and we're displaying it so you can get a sense of where in the file to add this"_, and call it out // make it a pattern in **all** tutorials.

Propositions from the community would be welcome!
