### ISSUE TITLE
LED Blinker redundancy

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#2246]
LED Blinker has a redundancy in the "Try it youreself" Telemetry section.  Also `ledTransitions` often causes problems with `packet spec`

**Comment by kevin-f-ortega** [comment]
First part addressed here https://github.com/fprime-community/fprime-workshop-led-blinker/pull/39

**Comment by LeStarch** [comment]
@kevin-f-ortega are you going to adjust the second part of this ticket?  Or should that be assigned elsewhere?

**Comment by kevin-f-ortega** [comment]
That should be a separate ticket.
