### ISSUE TITLE
LED Blinker: Add param read to run function

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#2247]
The `run` function now occurs after the `parameter` section.  We can include the read and avoid the `//TODO`

**Comment by thomas-bc** [comment]
Are you referring to removing the TODO for this: 
```U32 interval = 0; // TODO: Get BLINK_INTERVAL parameter value```
here: https://github.com/fprime-community/fprime-workshop-led-blinker/blob/0670e571f2d51455c34285c362849138fec604a4/Components/Led/Led.cpp#L44 ?

I feel like it's pretty useful for users to learn how to read a parameter value

**Comment by LeStarch** [comment]
Revisit this one after the October workshop.
