### ISSUE TITLE
F´  Project Tool

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#2251]
Add a tool to `fprime-util` to work with shared project:

1. Clone and install tool
2. `requirements.txt` to project
3. Update tool (may be part of 1)

**Comment by LeStarch** [comment]
@thomas-bc could this be added to fprime-bootstrap?  That is, add a feature to clone an existing project and setup the venv for users?  That way users could:

1. Create a new project
2. Grab an existing project

**Comment by thomas-bc** [comment]
Scheduled for next sprint
