### ISSUE TITLE
Implement plugin architecture for the GDS

### ISSUE THREAD

**Issue by thomas-bc** [nasa/fprime#2268]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**| GDS |
---
## Feature Description

Users may sometimes need to extend/modify the capabilities of the GDS, e.g. to add some custom processing for packets etc...
This requires to fork the GDS. We want to have an architecture that allows users to easily write plugins, e.g. with [pluggy](https://github.com/pytest-dev/pluggy)

## Rationale

Easily extend the F´ GDS

**Comment by thomas-bc** [comment]
Implemented in https://github.com/fprime-community/fprime-gds/pull/164

**Comment by LeStarch** [comment]
See also: #2577
