### ISSUE TITLE
i used to get some kind of installation error 

### ISSUE THREAD

**Issue by h9zdev** [nasa/fprime#2283]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|   |
---
## Problem Description

i used to get some kind of installation error 
## How to Reproduce

1. 
2.
3.

## Expected Behavior

A description of the expected behavior.

**Comment by thomas-bc** [comment]
@haydenbanz would you be able to provide more information about your issue? Error messages, which step of the install etc... 
Without that there's really not much we can do to help.

**Comment by thomas-bc** [comment]
@haydenbanz closing this issue. Feel free to re-open a new one with more details
