### ISSUE TITLE
Documentation Link Broken

### ISSUE THREAD

**Issue by timcanham** [nasa/fprime#2295]
| | |
|:---|:---|
|**_F´ Version_**| 3.x |
|**_Affected Component_**| None  |
---
## Problem Description

Broken documentation link in GDS Test API docs:

![image](https://github.com/nasa/fprime/assets/8086374/a496728d-d599-4ceb-996d-83ae28c3a050)

## How to Reproduce

1. Go to https://nasa.github.io/fprime/UsersGuide/dev/testAPI/user_guide.html 
2. Click on link in "An example script to run the Ref App deployment without a GDS Tool can be found [here](https://nasa.github.io/Ref/scripts/run_ref_for_int_test.sh)."
3. 404

## Expected Behavior

Valid page

**Comment by thomas-bc** [comment]
This example script is likely out-dated with the introduction of the pytest fixture. Refactoring of the docs is to be addressed by https://github.com/nasa/fprime/issues/2295

**Comment by LeStarch** [comment]
Should be fixed by #1902
