### ISSUE TITLE
Python 3.12 Support

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#2321]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|   |
---
## Problem Description

With the introduction of Python 3.12, things have started breaking (e.g. pkg_resources importation), zmq installs, etc.  We should fix this.

**Comment by thomas-bc** [comment]
Supported in https://github.com/nasa/fprime/releases/tag/v3.4.1
