### ISSUE TITLE
Creation of a new deployment includes trailing white space in name

### ISSUE THREAD

**Issue by dheadrick1618** [nasa/fprime#2322]
| | |
|:---|:---|
|**_F´ Tools Version_**| 3.3.3 | 
|**_Affected Component_**| -- |
---
## Problem Description
Creation of a new deployment using the following fprime-tools command: "fprime-util new --deployment " , allows the deployment name to include trailing white space without any warning to the user. A trailing white space in the deployment name breaks the deployment build CMake process. 

## How to Reproduce
1. Create a new deployment using fprime tools command:  fprime-util new --deployment
2. Provide a deployment name with a trailing white space 
3. Attempt to build this deployment using fprime-util build in the associated deployment directory. 

## Expected Behavior
User should be informed of trailing white space in the deployment name with a warning, given a white space in the deployment name breaks the deployment build.

**Comment by thomas-bc** [comment]
This likely applies to new component and new project as well.
