### ISSUE TITLE
fprime-util visualize does not work

### ISSUE THREAD

**Issue by sriramyabhamidipati** [nasa/fprime#2328]
Fprime version: 3.3.2
fprime-tools: 3.3.3

When I run fprime-util visualize I get the following error: 
[ERROR] fpl-layout is not installed. Please install with `pip install fprime-fpp>1.2.0`
Note that I have fprime-fpl-layout==1.0.0 installed (as confirmed in my fprime/requirements.txt file). I am using F prime in linux-based parallels with arm64. My parallels is running on my MacOS with M1 chip.

**Comment by thomas-bc** [comment]
This is likely an issue with the FPP tools install on ARM64 and not with `fprime-util visualize` per se. The upcoming release (3.4.0) should correct that.
