### ISSUE TITLE
implement `fprime-util clean` command

### ISSUE THREAD

**Issue by capsulecorplab** [nasa/fprime#2332]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

`fprime-util clean` command

## Rationale

As to be able to cleanup/purge fprime build cache without having to run `rm -rf build-*`

**Comment by thomas-bc** [comment]
@capsulecorplab have you tried the `fprime-util purge` command? `--force` flag to skip the prompt

**Comment by warkuszmonika** [comment]
fprime-util clean

**Comment by capsulecorplab** [comment]
> @capsulecorplab have you tried the `fprime-util purge` command? `--force` flag to skip the prompt

Thanks! I completely missed that this was a command. Closing issue as this works
