### ISSUE TITLE
Remove unused files

### ISSUE THREAD

**Issue by thomas-bc** [nasa/fprime#2338]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Description

There are some files in the top level of the repository that are not used and I would like to suggest for deletion. Posting as an issue here so that we can discuss which one to move forward with.

- [x] [setup.py](https://github.com/nasa/fprime/blob/devel/setup.py)
- [x] [.dockerignore](https://github.com/nasa/fprime/blob/devel/.dockerignore): this could suggest to users that we support/maintain a Docker image, which we don't.
- [ ] [.clang-tidy](https://github.com/nasa/fprime/blob/devel/.clang-tidy) and [release.clang-tidy](https://github.com/nasa/fprime/blob/devel/release.clang-tidy): maybe only keep one? I'm not familiar with clang-tidy though
- [ ] [CONTRIBUTORS.md](https://github.com/nasa/fprime/blob/devel/CONTRIBUTORS.md): I'm not necessarily in favor of removing this one, but it has been marked "_This file will be removed in future releases._"
- [ ] [.pre-commit-config.yaml](https://github.com/nasa/fprime/blob/devel/.pre-commit-config.yaml)

**Comment by LeStarch** [comment]
Some notes:
1. CONTRIBUTORS.md isn't maintained.  It originally served as a list of contributors to F´, but has been surpassed by the insights tab listing of contributors.  We don't want to minimize the impact of new contributors and thus want to redirect to that tab.  It is possible we could keep the contributors as a link to that tab and maintain by hand other contributors who do not appear in the insights tab somewhere.
2. .pre-commit-config.yaml is needed for the python development pre-commit hooks.  This has mostly been replace by CI check, so is probably not needed.
3. @Joshua-Anderson can you speak to the .clang-tidy files.  I believe you put them in.
