### ISSUE TITLE
f' 1000th pull reward

### ISSUE THREAD

**Issue by mlebrun40** [nasa/fprime#2347]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
I had an idea to reward all contributors of the project with an easter egg in f' with a hidden Easter egg in f' with the name of all contributors from the 1st to the 1000th contributor

**Comment by thomas-bc** [comment]
@MaxenceLebrunDEV Would you be able to elaborate on what kind of easter egg you're thinking of?
