### ISSUE TITLE
Write loaders for new dictionary

### ISSUE THREAD

**Issue by jwest115** [nasa/fprime#2399]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|   |
---
## Problem Description

A description of the problem with sufficient detail to understand the issue.

## How to Reproduce

1. 
2.
3.

## Expected Behavior

A description of the expected behavior.

**Comment by thomas-bc** [comment]
Duplicate of https://github.com/nasa/fprime/issues/2592
