### ISSUE TITLE
Add version flag to new --project

### ISSUE THREAD

**Issue by thomas-bc** [nasa/fprime#2406]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

Add a --version to select release version in fprime-util new --projet. The cookiecutter input was discontinued since we retrieve automatically latest release instead of `devel`, but we could add `--version` flag to select version. Allows for easy switch back if, say there's a bug in latest release.

**Comment by ethancheez** [comment]
Does this affect the cookiecutter input for `new --deployment` (for the sake of [`fprime-arduino-deployment-cookiecutter`](https://github.com/fprime-community/fprime-arduino-deployment-cookiecutter))?

**Comment by thomas-bc** [comment]
No it should not have any side effect. This is also just a proposed feature, not sure if we'll move forward with it.
