### ISSUE TITLE
Record packet headers

### ISSUE THREAD

**Issue by rrieber** [nasa/fprime#2429]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

AMPCS has a system that records packet headers. One can do `chill_get_packets` and get a list of all packets received. FPrime-GDS records the raw received data in `recv.bin`, which is nice, but to suck out the packet headers, one has to read this in binary, which is just cruel.

## Rationale

Make my life easier when it comes to monitoring/watching/debugging the downlink.

**Comment by LeStarch** [comment]
We should document the process to handle these files so that user may make any flavor of process script they'd like.

**Comment by LeStarch** [comment]
Here is the sample GDS script that we will expand for this documentation: https://github.com/fprime-community/fprime-gds-client-sample-script

**Comment by LeStarch** [comment]
I am closing this, #2478 will provide the flexibility for users to define scripts for this process.
