### ISSUE TITLE
MacOS CI repeated fails

### ISSUE THREAD

**Issue by thomas-bc** [nasa/fprime#2462]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|   |
---
## Problem Description

MacOS CI has been failing repeatedly for no apparent reason, timing out after 6 hours. See for example 
https://github.com/nasa/fprime/actions/runs/7302456221/job/19901093748?pr=2454
https://github.com/nasa/fprime/actions/runs/7294730948/job/19901273821?pr=2451

**Comment by LeStarch** [comment]
This problem started around the time we corrected `fprime-util` to build with parallelism properly. This implies that the higher number of parallel jobs causes the issue.

As noted by @thomas-bc: https://github.com/actions/runner/issues/1326 seems to be related.  There is a lot of speculation that it could be an OOM or large memory usage that causes the issue.  We know FPP (Jav)a uses much memory, as does gcc/g++ so running many parallel jobs could strain the memory usage.

I would recommend we do the following:
1. Specifically limit macOS jobs to a single job or small number of jobs
2. Add a timeout as suggested there to something more normal

Looking for build-parallelism issues with random numbers of jobs could be restricted to Ubuntu as a matter of practicality.
