### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by williamWHC** [nasa/fprime#2469]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

A quick description of the requested feature.

## Rationale

A rationale for why the feature should be implemented in F´.

adicionar versão mais especifica. 
![image](https://github.com/nasa/fprime/assets/43853142/3bfdd87d-5c9c-4c73-bd1e-9611e7316a80)

**Comment by geoffreylgv** [comment]
Hi @williamWHC, what will we need for this issue, I'm not understanding it
