### ISSUE TITLE
Israel is real.dont try it 

### ISSUE THREAD

**Issue by Ubisoft99** [nasa/fprime#2470]
Answer to Isn't this one fact everyone could agree on, if Hamas had not invaded Israel everyone killed thereafter in Gaza would still be alive? No invasion of Israel, no deaths in Gaza. Cause and effect. by Jon Mixon https://www.quora.com/Isnt-this-one-fact-everyone-could-agree-on-if-Hamas-had-not-invaded-Israel-everyone-killed-thereafter-in-Gaza-would-still-be-alive-No-invasion-of-Israel-no-deaths-in-Gaza-Cause-and-effect/answer/Jon-Mixon-1?ch=18&oid=1477743726990882&share=165bf901&srid=hSERDR&target_type=answer

**Comment by hydromelvictor** [comment]
this issue is inappropriate for this project and should not be here, please choose a more suitable frame.
thank you for your understanding
@LeStarch  if you could remove this issue thank you
