### ISSUE TITLE
F Prime GDS channel selection usability suggestion

### ISSUE THREAD

**Issue by timcanham** [nasa/fprime#2476]
| | |
|:---|:---|
|**_F´ Version_**|v3.4.1, commit https://github.com/nasa/fprime/commit/8a1612c0dd1ec18ada8162d92d37ff7317835129 |
|**_Affected Component_**|   |
---
## Problem Description

When selecting a set of channels in the "edit view" mode using a filter, when the user presses "done" the filter stays when going back to the normal channel view. The normal channel view shows only the most recently selected channels. This can be confusing as it appears that only the last set of channels selected via the filter where the ones added to the custom view.

## How to Reproduce

1. Add some channels using one filter
2. Add a different set of channels using a different filter
3. Click "done"
4. Only the channels in 2\. are shown
5. Clear the filter
6. See all the channels selected

## Expected Behavior

As usability suggestion would be to clear the filter field when the "done" button is clicked to populate all the selected channels.

**Comment by LeStarch** [comment]
I think the appropriate fix is to clear the filter on enter and exit of the view tab.
