### ISSUE TITLE
Create standalone bootstrap tool

### ISSUE THREAD

**Issue by thomas-bc** [nasa/fprime#2477]
| | |
|:---|:---|
|**_F´ Version_**| v3.4.0 |
|**_Affected Component_**|  |
---
## Feature Description

Task list:

- [x] Create tool and repo : https://github.com/fprime-community/fprime-bootstrap
- [x] Publish to PyPi
- [x] Rewrite Install Guide : https://github.com/nasa/fprime/pull/2512
- [x] Double check docs for other references of installs
- [x] Rewrite tutorials to make sure they only reference install guide  https://github.com/fprime-community/fprime-tutorial-math-component/pull/25 https://github.com/fprime-community/fprime-workshop-led-blinker/pull/57 https://github.com/fprime-community/fprime-tutorial-hello-world/pull/17

Standalone tool shall:
- same functionality as `fprime-util new --project`
- create a venv within the newly created project, so that package management is similar to how npm does it (everything is within the project)

## Rationale

Make the whole install process more clear, and better venv management

**Comment by thomas-bc** [comment]
Also see https://github.com/nasa/fprime/issues/2251

**Comment by capsulecorplab** [comment]
I take it the venv creation will still be optional?

**Comment by thomas-bc** [comment]
Yes! But the venv will be created within the created project instead of having the user supply one. All dependencies will be contained in the project, similar to how `npm` does it. We're hoping this will make venv management much easier for users who might not be familiar with Python venv. Feel free to suggest any other improvements/approaches 🚀

**Comment by capsulecorplab** [comment]
I think you already know my preferred approach, which is building projects in the [fprime-workspace-image](https://github.com/fprime-community/fprime-workspace-image) :upside_down_face: Otherwise, seems like a reasonable approach for creating a venv on the fly
