### ISSUE TITLE
Resolve Shadowed `public` Members

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#2492]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

With the merge of #2482, shadowed public members were renamed with the `a_` prefix for "argument".  We should review these uses and decide how to proceed.  

## Rationale

Public members are discouraged but have a purpose. `a_` is not a long-term solution either, but effectively resolves the issue and makes it easy to find these problems for discussion.

**Comment by JohanBertrand** [comment]
For reference, we had some discussions about this point in a FPP issue: https://github.com/fprime-community/fpp/issues/326
