### ISSUE TITLE
Tutorial Updates

### ISSUE THREAD

**Issue by timcanham** [nasa/fprime#25]
This issue is to track issues found while others are working their way through the tutorial.

**Comment by timcanham** [comment]
1. Add `MathReceiver` header file to demo. Private members `m_factor1` and `m_factor1s` need to be shown.
2. Check link order in `modules.mk`
3. Add `Makefile` to each directory.

**Comment by rdaruwala** [comment]
Hi Tim- I addressed a few of these issues in #15. The changes are currently merged into the dev branch, if you'd like I could open a new PR to merge those changes into master so that people new to fprime see the most up-to-date tutorial version

**Comment by timcanham** [comment]
Fix event:

```
<event id="0" name="MS_COMMAND_RECV" severity="ACTIVITY_LO" format_string="Math Cmd Recvd: %f %d %f" >

to

<event id="0" name="MS_COMMAND_RECV" severity="ACTIVITY_LO" format_string="Math Cmd Recvd: %f %f %d" >
```
in Ref/MathSender/MathSenderComponentAi.xml

**Comment by timcanham** [comment]
Add a comment that states that you can type `make` after the first `make rebuild`.

**Comment by timcanham** [comment]
Fix variable initialization in `MathSender`.

**Comment by AaronMcDaniel** [comment]
Ref/scripts/compile_ref_sequence.sh expects the seqgen.py file to be in Gds/bin/tkgui but it is actually in Gds/src/fprime_gds/tkgui/tools. Changing the path fixed my sequence compiling issues.

**Comment by LeStarch** [comment]
@AaronMcDaniel can you submit this as a fix/PR? or direct me to the line that needs to be updated?

Also, thanks for reporting this.

**Comment by AaronMcDaniel** [comment]
I opened PR #56 into devel that fixes the issue I mentioned above.

**Comment by LeStarch** [comment]
PR #56 merged. Closing.
