### ISSUE TITLE
Add Troubleshooting Guide With Example Errors

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#2500]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

Troubleshooting guide linked to install and tutorials covering:

1. What happens with old versions of python
2. What happens with old versions of cmake

Other errors?

**Comment by rlcheng** [comment]
PR merged. https://github.com/nasa/fprime/pull/2684
