### ISSUE TITLE
Add Condition Variables to OS Layer

### ISSUE THREAD

**Issue by kubiak-jpl** [nasa/fprime#2503]
| | |
|:---|:---|
|**_F´ Version_**| N/A |
|**_Affected Component_**| Os |
---
## Feature Description

Add a condition variable class to the Os layer, analogus to the current Os::Mutex class.

## Rationale

Condition variables are a necessary for certain types of multi-threaded workloads and do not have a generic implementation in the F Prime Os layer

**Comment by LeStarch** [comment]
Partially addressed by #2725
