### ISSUE TITLE
Improve TcpClient, TcpServer, and Udp for Reconnections

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#2553]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**| TcpClient, TcpServer |
---
## Feature Description

Update the TcpClient, TcpServer, Udp to allow reconnection on `send` as it does already on the recv loop.  Add in a `close` port to these components such that other components may close the connection.

- [ ] Add a mutex as member to components
- [ ] Expose mutex (or lock/unlock) through the `getHandler()` inteface
- [ ] Lock/unlock mutex on `recv` thread reconnect
- [ ] Add lock, reconnect, unlock to the send call
- [ ] Add a close port to each component that will call close

## Rationale

Allows better interaction with sockets.

**Comment by Ahmad-Bamba** [comment]
I can look at this, if the enhancement is still wanted.
