### ISSUE TITLE
Google Search Shows Old Versions

### ISSUE THREAD

**Issue by csmith608** [nasa/fprime#2573]
| | |
|:---|:---|
|**_F´ Version_**| 3.4.3 |
|**_Affected Component_**| Documentation  |
---
## Feature Description

Add a theme to outdated fprime documentation indicating that it is outdated and has been superseded by a newer version. 

## Rationale

To quickly find a part of an fprime tutorial to reference I'll use Google to search. For example, I'll Google "math component fprime" and the first hit is the tutorial [from fprime 2.0.0](https://nasa.github.io/fprime/v2.0.0/Tutorials/MathComponent/Tutorial.html). The second hit is from fprime 3.1.0. 
Adding a header would reduce confusion and is standard in some other repositories.

**Comment by thomas-bc** [comment]
Changes probably need to be done in that branch here if what is requested is for the older versions of documentation: https://github.com/nasa/fprime/tree/docs/auto-documentation/docs

Not too sure what the best approach is to handle those kind of things - if anyone from the community wants to jump in and contribute for this, would be greatly appreciated!

**Comment by LeStarch** [comment]
We should stamp old versions with a tag saying:

"Latest documentation available here: link to devel"

**Comment by LeStarch** [comment]
One more to look into after the webwork!

**Comment by rithvikrajraapeti** [comment]
So which file should i work on this issue

**Comment by thomas-bc** [comment]
This issue is being handled by our team. Thanks for the help!

**Comment by thomas-bc** [comment]
Hopefully the new website will get picked up by google search better. Versioning is now all handled within the F´ website. There's not much we can do about google search results AFAIK.
