### ISSUE TITLE
Rename Time Interface File

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#2579]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|   |
---
## Problem Description

`Svc/Interfaces/Time.fppi` should be renamed to `Svc/Interfaces/TimeInterface.fppi` to match modern standards.

**Comment by rldettloff** [comment]
I'm working on this!

**Comment by LeStarch** [comment]
@rldettloff are you still working on this?

**Comment by CombustableLem0n** [comment]
I added a pull request addressing this issue. I'm new to submitting pull requests but I think this should help you find my pull request. (gh pr checkout 2728)

**Comment by CombustableLem0n** [comment]
I'm confused why some test checks failed first time on my pull request, but the same checks passed second with identical code. Any explanations?

**Comment by thomas-bc** [comment]
@CombustableLem0n thank you for closing this out!
