### ISSUE TITLE
Create Interface from LinuxGpioDriver

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#2581]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

Make an interface out of Drv/LinuxGpioDriver protocol. See #2255 for an example interface change set.

The following three ports should be pulled out of `Drv::LinuxGpioDriver` into `Svc/Interfaces/GpioInterface.fppi` such that other GPIO implementations can use it.

https://github.com/nasa/fprime/blob/a73bff28617b96736c0e3e222e4c6e1dea1c6f5e/Drv/LinuxGpioDriver/LinuxGpioDriver.fpp#L9

https://github.com/nasa/fprime/blob/a73bff28617b96736c0e3e222e4c6e1dea1c6f5e/Drv/LinuxGpioDriver/LinuxGpioDriver.fpp#L21

https://github.com/nasa/fprime/blob/a73bff28617b96736c0e3e222e4c6e1dea1c6f5e/Drv/LinuxGpioDriver/LinuxGpioDriver.fpp#L11

Note: annotations should be added to explain what each port does.

**Comment by thomas-bc** [comment]
Implemented by https://github.com/nasa/fprime/pull/2943
