### ISSUE TITLE
Create Events Interface

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#2584]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

Make an interface out of the standard Event ports. See #2255 for an example interface change set.

The following three ports should be put into an interface at `Fw/Interfaces/EventsInterface.fppi` such that component implementers can quickly use them.

https://github.com/nasa/fprime/blob/a73bff28617b96736c0e3e222e4c6e1dea1c6f5e/Ref/SignalGen/SignalGen.fpp#L50-L54

**Comment by menaman123** [comment]
Hi, I was wondering if this issue still needs to be worked on? This would be my first contribution.
