### ISSUE TITLE
Create Command Interface

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#2586]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

Make an interface out of the standard Command ports. See #2255 for an example interface change set.

The following three ports should be put into an interface at `Fw/Interfaces/CommandInterface.fppi` such that component implementers can quickly use them.

https://github.com/nasa/fprime/blob/a73bff28617b96736c0e3e222e4c6e1dea1c6f5e/Ref/SignalGen/SignalGen.fpp#L41-L48

**Comment by rmzmrnn** [comment]
Hello,
Is someone working on this? If none, I want to give it a try. This is my first time to contribute.

As I understand it, the three command ports should be put in `Fw/Interfaces/CommandInterface.fppi` and then pull out from `fprime/Ref/SignalGen/SignalGen.fpp`. Also, add `include "../../Fw/Interfaces/CommandInterface.fppi"` in `SignalGen.fpp`.

Just like the fix made here in [ Create TickDriver interface #2708 ](https://github.com/nasa/fprime/pull/2708)

Did I get it all right or am I missing some other details?
