### ISSUE TITLE
32-bit ARM Toolchain Verification

### ISSUE THREAD

**Issue by kdizzlle** [nasa/fprime#2596]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|   |
---
## Problem Description
The 32-bit ARM verification code is out of date. It currently is "/opt/toolchains/bin/arm-linux-gnueabi-gcc -v" when it should be "/opt/toolchains32/bin/arm-none-linux-gnueabihf-gcc -v" GitHub section link: https://github.com/nasa/fprime/blob/devel/docs/Tutorials/CrossCompilationSetup/CrossCompilationSetupTutorial.md

**Comment by thomas-bc** [comment]
@kdizzlle thanks for reporting this - feel free to open a PR if you'd like to contribute!
