### ISSUE TITLE
CI Bug: DefaultDict Already Exists

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#261]
From CI, somewhat randomly:

```
Failed to run 'check --all' in /github/workspace/
---------------------------------------
---------------- STDERR ---------------
[Errno 17] File exists: 'DefaultDict/serializable'
```

**Comment by Joshua-Anderson** [comment]
Given that we've made large changes to the dict target over the past 9 months, I suspect this issue has probably been resolved. I also haven't seen this triggering CI failures so I think we're good to close this.
