### ISSUE TITLE
Write Intergration Tests for Baremetal Reference

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#2611]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

In order to have a solid CI test of the [Baremetal System Reference](https://github.com/fprime-community/fprime-baremetal-reference), a set of basic functional integration tests should be written for the Baremetal reference deployment.  These tests should ensure the following functions work correctly:

1. Connectivity and flowing telemetry
2. Commanding
3. Events
4. If the developer identifies other critical functions, these may be tested too

These tests should be written with the [Integration and Test API](https://nasa.github.io/fprime/UsersGuide/dev/testAPI/user_guide.html).  However, the modern fixture-driver approach shown in [Ref](https://github.com/nasa/fprime/blob/devel/Ref/test/int/ref_integration_test.py) should be used as that guide uses old boilerplate code.

## Rationale

A set of integration tests for the baremetal reference is an essential first step for making this system something that may be run in CI.

**Comment by LeStarch** [comment]
@ethancheez heads-up, we will be poking at the baremetal reference again.

**Comment by ethancheez** [comment]
> @ethancheez heads-up, we will be poking at the baremetal reference again.

Sounds good, I am happy to help out if needed.
