### ISSUE TITLE
Run CMake UT CI On Minimum Required CMake Version

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#2618]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

When running. the CMake UTs, we should run them on the minimum CMake version to ensure that version isn't inadvertently broken.

**Comment by thomas-bc** [comment]
I believe we meant to close #2615 instead. Reopening this one.

**Comment by LeStarch** [comment]
@thomas-bc this is fixed by #2619.  I must have gotten my annotations wrong.
