### ISSUE TITLE
Autogenerate Better Release Documentation

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#2653]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

Need to autogenerate release documentation.

**Comment by capsulecorplab** [comment]
We currently have [auto-generated release notes](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes) configured for the fprime-workspace-image https://github.com/fprime-community/fprime-workspace-image/blob/main/.github/release.yml

**Comment by thomas-bc** [comment]
Adding some context:

The way we have our documentation versioned is with version folders (`3.0.0`, `3.1.0` etc.) in our docs branch here: https://github.com/nasa/fprime/tree/docs/auto-documentation/docs
And then exposed here https://nasa.github.io/fprime/

Generating these versioned docs is a manual process, through a couple of scripts in the docs/ folder.

The scope of this ticket is to automated that process.

Although we're currently in an effort to revisit the way we serve documentation, so the result of that effort might affect this issue.

Also see https://github.com/nasa/fprime/discussions/2635 - there is some insight about versioning in there

**Comment by LeStarch** [comment]
@ashleynilo assigned to you because you are working on the whole webpage rework task!  I don't expect you to do this work, so much as track it so we can revisit once we have a new setup.

**Comment by thomas-bc** [comment]
New website is taking care of this! Woohooo

https://fprime.jpl.nasa.gov
