### ISSUE TITLE
Clean Out Non-Standard OSAL Layer Items

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#2724]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

- [x] Remove `Os::Watchdog` as it is VxWorks specific without clear pattern for other OSes.
- [x] Remove `Os::InterruptLock` as it belongs more generally in a HAL layer
- [x] Remove `Os/Mem.hpp` and associated code as it belongs specifically to VxWorks implementations
- [x] Remove `Os::TaskLock` as it is VxWorks specific

**Comment by menaman123** [comment]
Hi, I was wondering if Im able to do this task. This would be my first contribution to this project or any open source project.

**Comment by aramk-hub** [comment]
Hey, I was wondering if this was still in progress / being worked on? I'm looking for my first contribution to F' right now. If this isn't being worked on anymore, I'm happy to take over. Otherwise, I see some first issues open, but what do you suggest to work on out of that list?

**Comment by aramk-hub** [comment]
Hey, I was wondering if this was still being worked on or in progress. If not, I'm happy to take over. Otherwise, I do see some first-issue labels open, but what specifically would be a good issue to gain exposure to the core fundamentals? I've loved space for a long time and found this, so I'm excited and want to make sure I have a solid foundation to contribute often.

**Comment by aramk-hub** [comment]
Hey @LeStarch, sorry for tagging you, I'm not sure if you get notifications for every response, but it seems like you were the lead in this issue. Thanks for any help!

**Comment by LeStarch** [comment]
This is not underway yet.  It will be done by our team in 2 weeks or so.....but if you want to do it first, go for it!

**Comment by aramk-hub** [comment]
Sure I'll give it a shot! Looking at `Os::Watchdog` right now and seeing the Timer classes, I assume this is what we want to remove, is that correct? Also, does this issue need all the references of `Os::Watchdog` deleted as well (i.e. in the `os-docs.md` or `CMakeLists.txt`, etc.)? This question also applies to `Os::InterruptLock`.

**Comment by LeStarch** [comment]
Preferably we'd remove documentation references, yes.
