### ISSUE TITLE
Refactor Os::SystemResources into CMake Selection

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#2727]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

- [ ] Refactor Os::Log into the Interface, Os::Log, and Implementation classes (following pattern of Os::File)
- [ ] Implement Posix implementation
- [ ] Implement Stub implementation
- [ ] Implement Test stub implementation
- [ ] Build common rules-based tests
- [ ] Build specific posix tests
- [ ] Build stub interface tests
- [ ] Setup default posix implementation for Posix platforms
- [ ] Document

**Comment by thomas-bc** [comment]
Note: 
-> use singleton pattern in the "face" class (`class SystemResources final : public SystemResourcesInterface {` to which the static methods delegate to the singleton

**Comment by LeStarch** [comment]
@kevin-f-ortega reassigning this to me.
