### ISSUE TITLE
Do not comment out `loadParameters()`

### ISSUE THREAD

**Issue by kevin-f-ortega** [nasa/fprime#2774]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**| Topology  |
---
## Problem Description

The autocoder does not put `loadParameters()` in to the Topology.cpp. This should be added regardless of if there are parameters defined or not.

## Expected Behavior

`loadParameters()` should not be commented out in Topology.cpp

**Comment by mosa11aei** [comment]
I can take this one! Needs to be updated in fprime-tools.

**Comment by mosa11aei** [comment]
PR submitted on fprime-tools (see mention above)
