### ISSUE TITLE
`loadParameter` FATALs Without PrmDb

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#2805]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|   |
---
## Problem Description

`loadParamerter` on a component will FATAL without a parameter database.

Expected: this should check if connected and return default.

**Comment by LeStarch** [comment]
The decision was to make a "cap" component that acts as a prmDb but does nothing.

**Comment by timcanham** [comment]
What is the context here? What is the FATAL? An unconnected port?
