### ISSUE TITLE
Update GDS JSON dictionary channel/event/command name parsing

### ISSUE THREAD

**Issue by jwest115** [nasa/fprime#2813]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Description

In the loaders, we parse the qualified names to infer name of component and channel/event/command
Logic will need to be adapted since we are now using fully qualified names in the JSON dictionary

https://github.com/nasa/fprime-gds/tree/devel/src/fprime_gds/common/loaders

## Rationale

In FPP [#349](https://github.com/nasa/fpp/issues/349) we are moving towards fully qualified component instance names in c++ auto generated code and JSON dictionaries. Command, channels, events, etc. and need to update the GDS to work with fully qualified command names, etc.

**Comment by thomas-bc** [comment]
@jwest115 can this be closed?

**Comment by jwest115** [comment]
Yes! Closing now!
