### ISSUE TITLE
`fprime-bootstrap` Does Not Contain Phase Configuration Code

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#2820]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|   |
---
## Problem Description

Ref does not contain the phase configuration code and as such, nor does `fprime-bootstrap new --project`

**Comment by thomas-bc** [comment]
Fixed in `new --deployment` https://github.com/nasa/fprime-tools/pull/212
`fprime-bootstrap` does contain deployment cookiecutters, only fprime-tools
