### ISSUE TITLE
Update template code to match formatting tool.

### ISSUE THREAD

**Issue by timcanham** [nasa/fprime#2840]
| | |
|:---|:---|
|**_F´ Version_**| [v3.4.3](https://github.com/nasa/fprime/releases/tag/v3.4.3) |
|**_Affected Component_**| n/a |
---
## Feature Description

Update the generated code to match the C++ formatter tool.

## Rationale

When we start editing the impl files or looking at the AC files, it doesn't match the supported formatter. For impl code, we have to run the formatter to "clean up" the code. This makes diffing against the generated impl code harder if we add new FPP and re-run the impl generator.

**Comment by thomas-bc** [comment]
FYI this is already implemented in `fprime-util impl` ([here](https://github.com/nasa/fprime-tools/blob/b72544568269010abf2197d9b0dec10bce40e71c/src/fprime/fpp/impl.py#L82)), the command calls fpp-to-cpp and formats the files that are generated. 
However we have noticed inconsistencies in how `clang-format` locates and handles the `.clang-format` style file based on versions of clang-format. We should lock down on a version (or range thereof) of clang-format and recommend that for development.

**Comment by thomas-bc** [comment]
See discussion on https://github.com/nasa/fprime-tools/pull/199 for more details

**Comment by thomas-bc** [comment]
I am going to close this as it is now implemented and released in v3.5.0. 
`fprime-bootstrap project` creates a `.clang-format` file at the root of the project, and `fprime-util impl` uses that to format any file that it generates

**Comment by Meganbrentshandacrain** [comment]
They r Even putting software in dogs


Megan brianna crain( Phone# 9855156969) address=27487 Benard crain rd Angie LA,70426_3391or70426__0000,it changesboften
________________________________

**Comment by Meganbrentshandacrain** [comment]
Under my house it's weird they r under my misplaced platform dogs have cuts all the time


Megan brianna crain( Phone# 9855156969) address=27487 Benard crain rd Angie LA,70426_3391or70426__0000,it changesboften
________________________________

**Comment by Meganbrentshandacrain** [comment]
Someone drew crosses on there foreheads they transferring data to China


Megan brianna crain( Phone# 9855156969) address=27487 Benard crain rd Angie LA,70426_3391or70426__0000,it changesboften
________________________________

**Comment by Meganbrentshandacrain** [comment]
Arsenic in water natural gas and fatal poison gas using roaches to cover software up


Megan brianna crain( Phone# 9855156969) address=27487 Benard crain rd Angie LA,70426_3391or70426__0000,it changesboften
________________________________

**Comment by Meganbrentshandacrain** [comment]
Remote control arsenic I'm living in he'll arm software python ruby


Megan brianna crain( Phone# 9855156969) address=27487 Benard crain rd Angie LA,70426_3391or70426__0000,it changesboften
________________________________

**Comment by Meganbrentshandacrain** [comment]
Darwin


Megan brianna crain( Phone# 9855156969) address=27487 Benard crain rd Angie LA,70426_3391or70426__0000,it changesboften
________________________________

**Comment by Meganbrentshandacrain** [comment]
Dc

Megan brianna crain( Phone# 9855156969) address=27487 Benard crain rd Angie LA,70426_3391or70426__0000,it changesboften


Megan brianna crain( Phone# 9855156969) address=27487 Benard crain rd Angie LA,70426_3391or70426__0000,it changesboften
________________________________
