### ISSUE TITLE
`fprime-util` -b Flag

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#285]
## -b Flag

I would expect the -b flag to allow users to point to a set of build caches and it would choose the "correct" build cache (based on build type). It does not, it want a specific build cache regardless of build type. I'd propose the following:

    1. Add a -d flag to specify the deployment it will be built for
    2. Add a not to help for -b that it is an "advanced feature"
    3. Prevent the specification of --build-type and -b at the same time

Expected use pattern (inverse of above):

```
cd Svc/CmdDispatcher
fprime-util build -d ../Ref
```

**Comment by Joshua-Anderson** [comment]
What is the use case for the -b flag? Is it so you can move your build cache to a location of your choosing? Does it point to an individual build cache or a directory holding the set of build caches?

**Comment by LeStarch** [comment]
-b is to point at and generate a specific build cache.  It points at the directory of the build cache itself (not the owning directory).

-d would point at the deployment and add a slightly more usable layer to it.

**Comment by Joshua-Anderson** [comment]
Why have both `-p` and `-d`? It seems like `-p` can do everything that `-d` can do, right?

**Comment by LeStarch** [comment]
They are inverses.  `-p`  Allows you to build a specified path from a WD of a  deployment.  `-d` allows you to build this WD using a specified deployment

**Comment by LeStarch** [comment]
We need to test `-p` and `-d`.

**Comment by LeStarch** [comment]
To close out:

1. Remove -b flag (work around is to use raw CMake)
2. Test `-p` and `-d` flags work as expected.
