### ISSUE TITLE
Lingering issues/improvements from TCP/IP restructuring

### ISSUE THREAD

**Issue by csmith608** [nasa/fprime#2886]
| | |
|:---|:---|
|**_F´ Version_**| v3.4.4 + |
|**_Affected Component_**| TcpServer, TcpClient, Udp |
---
## Feature Description

1. From a consistency perspective it would be good to move the server file descriptor to component level rather than have it as the only fd living at the library level [TODO: add link when PR is merged] -- DONE
2. Once the F\` scope locks are implemented, we should change the mutexes to scope lock for shutdown and close and stop functions in `SocketComponentHelper`.  --DONE
3. Once condition variables are added to F`, the mutexes in the open call in `SocketComponentHelper` could be converted to a state and condition variable.  Not needed
4. Put this warning back in the open call `"[WARNING] Failed to recv from port with status %lu and errno %lu\n"` and throttle it properly (no more than once a second!).

## Rationale

These items came up in review of the TCP/IP changes in https://github.com/nasa/fprime/pull/2683.

**Comment by LeStarch** [comment]
Going to close, should be fixed in PR
