### ISSUE TITLE
F Prime C Headers (.h) Are Not C++ Compliant

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#2899]
| | |
|:---|:---|
|**_F´ Version_**| devel |
|**_Affected Component_**|   |
---
## Problem Description

Currently, most or all `.h` headers in F´ do not work correctly when imported from C++.  Specifically, C headers are designed to interoperate with the C language and as such define symbols requiring C-linkage.  However, when including these headers from a C++ file these symbols gain C++ linkage and thus break interoperability between C and C++.

This can be fixed by surrounding the header in the following call to C linkage when included by C++

```
#include __cplusplus
extern "C" {
#endif

// ... C-definitions

#include __cplusplus
}
#endif
```

## Work Description

We need to do the following:

1. Identify `.h` headers in F Prime.  Two come to mind: `Fw/Types/CAssert.h` and `BasicTypes.h`.  Are there others provided by the core framework?
2. Surround those definitions with C-linkage constructs shown above
3. Test that F´ still builds (can be done through CI)

**Comment by bdshenker** [comment]
Question 1:
Currently we have BasicTypes.h and BasicTypes.hpp. 
BasicTypes.hpp includes BasicTypes.h as follows:
```
extern "C" {
#include "BasicTypes.h"
}
```
If we disable name mangling as recommended above in BasicTypes.h, then should we remove this "extern C" wrapper from BasicTypes.hpp? - Michael says no need.

Question 2:
Should we do the same exercise for the following .h files in fprime repository:
```
  config/FpConfig.h
  cmake/platform/types/PlatformTypes.h
  Utils/Hash/libcrc/lib_crc.h
  Utils/Hash/openssl/sha.h       - Already done
```
There are also numerous .h files in googletest, fprime-venv, STest. They are not affected.

**Comment by thomas-bc** [comment]
closed by https://github.com/nasa/fprime/pull/2936
