### ISSUE TITLE
Error in Rasberry Pi example

### ISSUE THREAD

**Issue by vigno88** [nasa/fprime#29]
In the example, it is mentionned that we need to connect the LED to GPIO 22. But if we look in the topology.cpp file, we can see that it is setup to work with pin 21.

**Comment by LeStarch** [comment]
I believe you are referring to this line:
```
https://github.com/nasa/fprime/blob/devel/RPI/Top/Topology.cpp#L203
```
We'll ensure the documentation and code are consistent.  Thanks!

**Comment by LeStarch** [comment]
I'll agree this is an issue, and would recommend a fix on the example text.
