### ISSUE TITLE
fprime-bootstrap should have an option for an existing git repo.

### ISSUE THREAD

**Issue by timcanham** [nasa/fprime#2910]
| | |
|:---|:---|
|**_F´ Version_**|3.4.3 |
|**_Affected Component_**| n/a |
---
## Feature Description

Add an option for fprime-bootstrap to set up in an existing git repo

## Rationale

It is common to create a repo at the start of a project and then clone it to start adding F Prime. It would be nice to have fprime-bootstrap set up the environment after it is cloned.

**Comment by LeStarch** [comment]
Fixed.
