### ISSUE TITLE
fprime-util new --deployment error

### ISSUE THREAD

**Issue by timcanham** [nasa/fprime#2915]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|   |
---
## Problem Description

I get this error when I try to compile the code:

```
[ 95%] Built target Drv_Udp
[ 95%] Building CXX object XXX/Top/CMakeFiles/XXX_Top.dir/XXXTopology.cpp.o
/home/tcanham/source/xxx-fsw-scp/XXX/Top/XXXTopology.cpp:11:10: fatal error: Os/Log.hpp: No such file or directory
   11 | #include <Os/Log.hpp>
      |          ^~~~~~~~~~~~
```

## Context / Environment

Execute `fprime-util version-check` and share the output.

```
Operating System: Linux
CPU Architecture: x86_64
Platform: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python version: 3.10.12
CMake version: 3.30.2
Pip version: 22.0.2
Pip packages:
    fprime-tools==3.4.5a1
    fprime-gds==3.4.4a3
    fprime-fpp-*==2.2.0a4
```

## How to Reproduce

1. Create a new deployment using `fprime-util new --deployment`
2. Compile
3.

## Expected Behavior

Clean compile.

**Comment by thomas-bc** [comment]
Same cause as https://github.com/nasa/fprime/issues/2913#issuecomment-2389095415 -- `fprime-util new --deployment` is meant to work with the latest release of F´ and not `devel`

We could come up with a system to have an option e.g. `fprime-util new --deployment --devel`. Might require some ingenuity to have CI warn when things go out of sync on `devel`, and fix things with a `pr-xxxx` branch like we do on tutorials. Then cookiecutter can dynamically download the `devel` cookiecutter template, which would free us from having to re-release fprime-tools every update.

**Comment by LeStarch** [comment]
Fixed.
