### ISSUE TITLE
TcpServer Does not Retry Properly

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#2940]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|   |
---
## Problem Description

TCP server does not have retry capability.  If it fails to open the TCP port, then send statuses fail with:

```
[ERROR] Failed to send framed data: 2
[WARNING] Failed to open port with status -11 and errno 9
```

This is a bad file descriptor.

**Comment by LeStarch** [comment]
Should be fixed by new PR

**Comment by thomas-bc** [comment]
Fixed by https://github.com/nasa/fprime/pull/2950
