### ISSUE TITLE
New deployment should warn if created in wrong location

### ISSUE THREAD

**Issue by thomas-bc** [nasa/fprime#2971]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## rationale

This would prevent the usual issue when running through hello world where users create the deployment within the LED component directory

**Comment by thomas-bc** [comment]
Also, new components created within components should warn.

We may even want to actually block it (or ask for `--force`) - since that will mess with the CMakeLists.txt and new users often trip over that

**Comment by Nemojn** [comment]
Hello! I'm a student taking a software engineering course at umich, and I was wondering if I could take a shot at tackling this issue! Thanks for your time!

**Comment by LeStarch** [comment]
@Nemojn sure!  This work is in our python tooling layer found here: https://github.com/nasa/fprime-tools

You'll need to add some code to check the location when adding a new component.  Let us know if you need more guidance!  Cluing in @thomas-bc who does much work in this area.

**Comment by Nemojn** [comment]
Wonderful, thank you!

**Comment by Nemojn** [comment]
Hi @thomas-bc, I just have a few questions: 

What exactly is "the wrong location" for this purpose? Is it only being inside a component directory, or are there other places the deployment/component should warn before being created?

Also, should I just clone the devel branch for adding the code? Or do I create a new branch?

Thanks for your help!

**Comment by thomas-bc** [comment]
@Nemojn yes please fork the repository and create a new branch, where you can add your commits in. Once you have something you'd like to submit, you can open a PR. Process should be explained in https://github.com/nasa/fprime/blob/devel/CONTRIBUTING.md

**Comment by thomas-bc** [comment]
As for what is a wrong location... this is up to interpretation. We're mostly trying to add guardrails for new users, so maybe a good starting point would be to say:

- if the current directory's `CMakeLists.txt` file contains the following pattern `register_fprime_module(.*)`, it is a wrong location

@LeStarch thoughts?

**Comment by LeStarch** [comment]
Yes, from the prospective of our tool suite, we should not create an module where another module is already declared.

That is, we should warn in the `fprime-util new` tool if the current directory contains a `CMakeListst.txt` that already contains a statement of the form `register_fprime_*`

**Comment by Nemojn** [comment]
Ok, sounds good! Thanks for the clarification!

**Comment by Nemojn** [comment]
@thomas-bc what is the process for making tests for an fprime-util command? I read about running the regression test suite in the CONTRIBUTING.md file, but since this is a new feature, how does testing its functionality work?

**Comment by thomas-bc** [comment]
We use pytest https://docs.pytest.org/en/stable/
If you'd like to add test for the fprime-util new commands, you likely want to create a new file somewhere under https://github.com/nasa/fprime-tools/tree/devel/test/fprime

However as you can see we don't currently run test for these, as they are just wrappers to cookiecutter and a few niceties around the build cache...
If you'd like to add test to `fprime-util new`, that would be amazing, but I am not expecting it out of this PR

**Comment by Nemojn** [comment]
Hello @thomas-bc @LeStarch I've submitted a pull request here: https://github.com/nasa/fprime-tools/pull/231. I can't seem to figure out why I can't link it to this issue, so sorry for the inconvenience.

**Comment by thomas-bc** [comment]
Thank you very much! 

I added the links for you. I am pretty busy right now, I'll try review this next week.

**Comment by Nemojn** [comment]
Wonderful! Thank you very much!
