### ISSUE TITLE
Have `fprime-util new component` add commented out unit tests in CMake file

### ISSUE THREAD

**Issue by timcanham** [nasa/fprime#2997]
| | |
|:---|:---|
|**_F´ Version_**| [v3.5.0](https://github.com/nasa/fprime/releases/tag/v3.5.0)|
|**_Affected Component_**| n/a |
---
## Feature Description

Have the `fprime-util new component` put the variables and list in the new component CMake file. Then the user can more easily add them later. Even better, have the `new component` generator generate the actual unit test files and put them in `/test/ut`.

## Rationale

Makes it easier for users to add unit tests.

**Comment by thomas-bc** [comment]
If anyone wants to take a crack at implementing, it should be around here: 
https://github.com/nasa/fprime-tools/blob/devel/src/fprime/cookiecutter_templates/cookiecutter-fprime-component/%7B%7Bcookiecutter.component_name%7D%7D/CMakeLists.txt
