### ISSUE TITLE
fprime-seqgen passes but FSW crashes on empty seq

### ISSUE THREAD

**Issue by zimri-leisher** [nasa/fprime#3005]
| | |
|:---|:---|
|**_F´ Version_**| 3.4.3 |
|**_Affected Component_**|   CmdSequencer, fprime-seqgen |
---
## Problem Description

1. Create an empty `.seq` file
2. Run fprime-seqgen on it
```
$ fprime-seqgen empty.seq -d <some dictionary>
Sequence is 0 bytes with timebase ANY
CRC: 4017330436 (0xEF739904)
$ echo $?
0
```
3. Run with `CS_RUN`:
```
Assert: "<path>/CmdSequencer/FPrimeSequence.cpp:97" 3
FATAL 14273 handled.
```
## Context / Environment

Execute `fprime-util version-check` and share the output.
```
Operating System: Linux
CPU Architecture: x86_64
Platform: Linux-6.5.0-26-generic-x86_64-with-glibc2.35
Python version: 3.10.12
CMake version: 3.27.2
Pip version: 22.0.2
Pip packages:
    fprime-tools==3.4.4
    fprime-gds==3.4.3
    fprime-fpp-*==2.1.0a3
```

## Expected Behavior

1. Either CmdSequencer should not assert, or fprime-seqgen should fail.

**Comment by LeStarch** [comment]
We merged a fix for this.
