### ISSUE TITLE
Svc::FileManager MoveFile command does not work across partitions

### ISSUE THREAD

**Issue by timcanham** [nasa/fprime#303]
This command invokes the native OS rename interface. This doesn't work on a file system when the source and destination are on different file system partitions. It does work to a different directory on the same file system. Is there a different underlying call that more mimics the system "mv" command?

**Comment by LeStarch** [comment]
My recollection is that in cross-platform c++ you'd need to copy and remove.  Which we could implement.

**Comment by thomas-bc** [comment]
To be fixed by #2871
