### ISSUE TITLE
Clean-Up `fprime-util` info

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#305]
We should clean-up `fprime-util info` to accomplish the following:

- [ ] Warn user if a build cache is not generated and some targets may be missing
- [ ] Rename build artifacts to build cache
- [ ] Add documentation?

**Comment by Joshua-Anderson** [comment]
@LeStarch `fprime-util info` is documented in the fprime-util documentation. Is there somewhere else it should be documented?
