### ISSUE TITLE
Accidental files added to LinuxTimer

### ISSUE THREAD

**Issue by zimri-leisher** [nasa/fprime#3068]
| | |
|:---|:---|
|**_F´ Version_**| devel |
|**_Affected Component_**| LinuxTimer  |
---
## Problem Description

The following files are in the LinuxTimer folder:
![image](https://github.com/user-attachments/assets/0c222dbf-8969-4779-9ce1-4168b8a852ca)
On inspection they contain things such as this:
![image](https://github.com/user-attachments/assets/7af704cc-37c5-45a2-b2f5-1832952870d4)

These are probably not intended to be in the repo

**Comment by LeStarch** [comment]
@zimri-leisher you are correct.  Want to fix this, or shall I?

**Comment by zimri-leisher** [comment]
in work

**Comment by zimri-leisher** [comment]
Please review and merge when ready
