### ISSUE TITLE
Force on fprime-util purge command doesn't work

### ISSUE THREAD

**Issue by jonathanmichel** [nasa/fprime#310]
# Issue
When using `fprime-util purge`, `--force` argument doesn't work

# Solution
Replace 
```python
if confirm() or parsed.force:
```
by 
```python
if parsed.force or confirm():
````
[here](https://github.com/nasa/fprime/blob/c486a0252651f3642968eacd99dbe8ff5fbb817f/Fw/Python/src/fprime/util/build_helper.py#L379) and [here ](https://github.com/nasa/fprime/blob/c486a0252651f3642968eacd99dbe8ff5fbb817f/Fw/Python/src/fprime/util/build_helper.py#L398) to ensure condition will pass if `--force` option is set. Otherwise `confirm()` function is called first and confirmation will always be asked to the user

**Comment by Joshua-Anderson** [comment]
Good Catch! @LeStarch we should consider writing some integration tests for the fprime-util cli. We're breaking a lot of corner causes like this because we don't have test coverage.
