### ISSUE TITLE
Migrate CI Docker Container from Docker Hub to Quay

### ISSUE THREAD

**Issue by Joshua-Anderson** [nasa/fprime#312]
| | |
|:---|:---|
|**_F´ Version_**| n/a |
|**_Affected Component_**| infrastructure  |
---
## Feature Description

Move hosting of fprime ci docker container from docker hub to quay.io

## Rationale

Docker Hub added rate limiting for container pulls, causing risk that CI could get rate limited while attempting pulling the image. Quay also provides free hosting for public images but container pulls are not rate limited.

**Comment by LeStarch** [comment]
I am going to recommend we scrub the docker image.  We don't use it in CI any longer, our tools are easy to install packages, and the docker support will code-rot.

**Comment by LeStarch** [comment]
See #1171
