### ISSUE TITLE
Errors Issue

### ISSUE THREAD

**Issue by brhs17** [nasa/fprime#32]
I am working on the testing section of my CLEMOps component, and I get this error when I try to run `make ut`.  I haven't started working on the tests themselves, but I think I have everything setup, including the blank testing functions.
https://github.com/brhs17/fprime/tree/MOpAgg
![makeUTCLEMOps](https://user-images.githubusercontent.com/47761126/55187708-13b00300-5170-11e9-9bad-ceea9483ec7d.JPG)

**Comment by timcanham** [comment]
Whenever you get the "cannot declare .... abstract type", it means that a pure virtual function from the base class has not been implemented. You need to make sure all the pure virtual functions, which are handlers, in the base class are implemented in your derived testing class.

**Comment by brhs17** [comment]
I don't know how to do that, both the handlers in my `ComponentImpl.cpp` file look implemented.  The error tells me that the `OPS_Get_Data_cmdHandler` in 'ComponentAc.hpp` is not implemented, but I don't know where I'm supposed to write that, or really what the code needs to do.

**Comment by timcanham** [comment]
You write the function in the `ComponentImpl.cpp`. A similar command handler can be found here:

https://github.com/nasa/fprime/blob/master/docs/Tutorials/MathComponent/MathSender/MathSenderComponentImpl.cpp#L76

**Comment by brhs17** [comment]
What did I do wrong in my implementation?
![OpsGetDatacmdHandler](https://user-images.githubusercontent.com/47761126/55283760-f168e180-5337-11e9-9874-e86c7ab9104c.JPG)
![error](https://user-images.githubusercontent.com/47761126/55283761-f594ff00-5337-11e9-8289-c5d650769c01.JPG)

**Comment by timcanham** [comment]
Looks like virtual is `OPS`, yours is `Ops`. You have to get the spelling exactly right.

**Comment by brhs17** [comment]
ok, I just needed to run the impl command to make new files and copy and paste everything.

**Comment by timcanham** [comment]
I've been using Fprime for a while now, and that's how I do it. Avoids errors like this.

**Comment by brhs17** [comment]
I'm getting a bunch of undefined Reference errors, what should I be looking for to fix them?
![undefinedReference](https://user-images.githubusercontent.com/47761126/55298893-3e16f000-53fe-11e9-99cf-babc52298f1d.JPG)

**Comment by timcanham** [comment]
Check the `mod.mk` for the unit test. The `TEST_MODS` variable should have any modules your component relies on for testing.

**Comment by brhs17** [comment]
I'm not sure where this error came from, I'm not even sure how its related to something I write:
![paramValid valid](https://user-images.githubusercontent.com/47761126/55441186-e7cdbc80-5577-11e9-8c45-c49183bd9e7b.JPG)

**Comment by timcanham** [comment]
The `Fw::ParamValid` type is used to see if parameters successfully loaded. If you haven't defined any parameters in your XML, the headers to define it aren't included. If you added some parameters and then removed them all, you could see this error.

**Comment by brhs17** [comment]
What should I do to fix these warnings?
![bunchOfWarnings](https://user-images.githubusercontent.com/47761126/55443438-be655e80-5580-11e9-901b-a6618abed7f4.JPG)

**Comment by brhs17** [comment]
I'm working on the topology and getting an error I don't understand at all:
![topologyError](https://user-images.githubusercontent.com/47761126/55492805-d7fcb980-5605-11e9-8046-51eb7caef565.JPG)

**Comment by LeStarch** [comment]
Your constructor is expecting a name when you declare the component.  Try something like this:

```
Ref::CLEAggComponentImpl("CLE Agg");
```

**Comment by LeStarch** [comment]
In response to your noted warnings 2 comments ago: these warnings occur when the order you define your member variables in the *.hpp are in a different order than the order in which you initialize them in the initializer list in the *.cpp.

The best way to fix those warnings is to go through your *.hpp in and list all declared members in-order of declaration from top to bottom.  Then go through the initializer list in th *.cpp and reorder it to match.

**Comment by brhs17** [comment]
I'm trying to run the ground system with my new components in addition to the math components and am getting this error, which is strange because the math components worked before.
![TryingToRunError](https://user-images.githubusercontent.com/47761126/56237688-9aaf1780-605a-11e9-94b7-2fad0fd89f4b.JPG)

**Comment by rdaruwala** [comment]
Make sure to run `make dict_install` before opening your GUI application

**Comment by LeStarch** [comment]
Right, if you do not build with `make rebuild` you need to ensure you run `make dict_install` since the dictionaries can get out-of-date, or cleared.

**Comment by brhs17** [comment]
I have my components mostly working, but I get this error whenever I try to use them that seems to be related to the text they are supposed to return somewhere, however, the error message seems to be completely void of any identifying information of where is it coming from.  The `Ref Application` window displays everything as expected, but nothing shows up in the `Log Events` tab, which is bad.
![OperationalError](https://user-images.githubusercontent.com/47761126/56474668-daa33f80-644a-11e9-8e76-d39b160d0f48.JPG)

**Comment by rdaruwala** [comment]
This looks to be the exact same error you encountered in #22. The fix will likely be along the same lines. Check the XML file to make sure you're passing in the right types of arguments in the right order

**Comment by brhs17** [comment]
Ok, so I seemed to have fixed it by changing something to want an integer instead of a float, but this seems super confusing because a string is mentioned in the error message.  Also, why did it not get autocasted since getting an integer and converting it to a float doesn't lose precision.

**Comment by timcanham** [comment]
This is a ground software side issue that we need to fix to give a better error message.  As @rdaruwala says, it indicates a mismatch between the format specifiers in the event/telemetry message and the actual type of the argument.

**Comment by Azlinkix** [comment]
Hi,

I'm running into a similar issue with the make ut command except the error is:

<img width="1424" alt="Screen Shot 2019-05-03 at 3 49 28 AM" src="https://user-images.githubusercontent.com/47834141/57133069-89525480-6d56-11e9-8d56-66475ec42327.png">

**Comment by Azlinkix** [comment]
Running the following command "make ut run_ut" returns the same error.

Running "make ut run_ut cov" returns a similar error:

<img width="1103" alt="Screen Shot 2019-05-03 at 3 55 44 AM" src="https://user-images.githubusercontent.com/47834141/57133361-670d0680-6d57-11e9-9370-f10462357562.png">



Any suggestions on how I might move forward?

**Comment by timcanham** [comment]
It looks like `main()` isn't defined anywhere in your test files. Do you have this file in your unit test `mod.mk`?

https://github.com/nasa/fprime/blob/master/docs/Tutorials/MathComponent/MathSender/test/ut/main.cpp

**Comment by Azlinkix** [comment]
Thanks for the tip--turns out I missed a file.

Almost done with the tutorial! 

One (hopefully last) question:

<img width="639" alt="Screen Shot 2019-05-07 at 12 07 01 AM" src="https://user-images.githubusercontent.com/47834141/57323053-dec19500-70b9-11e9-9c94-e7a3af3853c8.png">

I got alot of syntax errors? Or all of these are unititated? I looked at the reference files under Ref > Docs> Tutorials > MathTutorials and my files are the same.

Any suggestions or needed clarifications?

**Comment by brianthespoon** [comment]
Also stumped by this one

**Comment by timcanham** [comment]
For `m_factor`` and `m_factor1s`, make sure they are declared as private data members of your class:

```c++
      // stored factor1
      F32 m_factor1;
      // number of times factor1 has been written
      U32 m_factor1s;
```

See https://github.com/nasa/fprime/blob/master/docs/Tutorials/MathComponent/MathReceiver/MathReceiverComponentImpl.hpp#L101.

The header file is missing from the tutorial and should be added in. We have added it to #25.

**Comment by timcanham** [comment]
The uninitialized variable warning looks genuine. Maybe you are using a new compiler that checks for it. We'll add a fix to the tutorial, but in the meantime just initialize the variables where you declare them.

**Comment by brh68** [comment]
I am trying to add two components the the RPI topology, and keep getting this error:
![ExternDoesNotNameAType](https://user-images.githubusercontent.com/47760444/59152450-29fcf980-8a12-11e9-845a-e9bc03f7761d.JPG)
I am mostly worried about why aggregator isn't working because RTCComponent doesn't compile yet.

**Comment by timcanham** [comment]
It seems like there could be a typo in the name or namespace. Is this on a branch somewhere?

**Comment by brh68** [comment]
I'm trying to run a modified version of `Ref`, but I get some fatal 342 error after everything opens up, but before doing anything.
![fatal342](https://user-images.githubusercontent.com/47760444/59298088-bf3cff80-8c57-11e9-8702-cb2c2cbf7c24.JPG)

**Comment by LeStarch** [comment]
It looks like you need to increase the configuration for the command dispatcher.

In `Fw/Cfg/AcConstants.ini`, what is the line "CmdDispatcherComponentCommandPorts" set to?
```
CmdDispatcherComponentCommandPorts  =       30
```
Is it 30 like above?

**Comment by LeStarch** [comment]
This may also be an issue in your Topology.  In Your Topology Ai file, you should look for lines with the `cmdDisp`  where the number at the end is 100, or 101.  You need to keep these numbers sequential.
```
         <target component = "cmdDisp" port = "compCmdReg" type = "CmdReg" num = "11"/>
```

**Comment by brh68** [comment]
Thank you, changing the `cmdDisp` numbers to be sequential fixed the problem.

**Comment by LeStarch** [comment]
If you have more than 30 components connected to the cmdDisp, you need to increase the above config.

**Comment by LeStarch** [comment]
I am closing this issue, as I see no updates.  Please feel free to continue discussion on our mailing list:  https://groups.google.com/forum/#!forum/fprime-community

Or open a new issue if you detect a new bug.
