### ISSUE TITLE
Error copying file

### ISSUE THREAD

**Issue by Galatis-Giuliano** [nasa/fprime#321]
## Problem Description

I am working on a project which requires an array to be used as the input to a component. We are currently making modification to the MathComponent created in the Math Tutorial to accommodate our project. We attempted to follow the specifications shown at this [link](https://nasa.github.io/fprime/UsersGuide/dev/xml-specification.html#serializable) to create our .xml files. We are currently getting an error when building F` and were wondering if this is a common problem and if there is some way to fix it.

The .xml file defining our serializable type is shown below:

```
<serializable namespace="Ref" name="MathOp">
    <comment>
    This value holds the values of a math operation
    </comment>
    <import_array_type>Ref/MathTypes/TestArrayAi.xml</import_array_type>
    <members>
        <member name="val1" type="TestArray"/>
        <member name="val2" type="F32"/>
        <member name="op" type="ENUM">
            <enum name="Operation">
                <item name="ADD"/>
                <item name="SUB"/>
                <item name="MULT"/>           
                <item name="DIVIDE"/>
            </enum>
        </member>
        <member name="result" type="TestArray"/>
    </members>
</serializable>
```

The imported array .xml file is shown below:

```
<array name="TestArray" namespace="Ref">
  <type>F32</type>
  <size>3</size>
  <format>%f</format>
  <default>
    <value>0.0f</value>
    <value>0.0f</value>
    <value>0.0f</value>
  </default>
</array>
```

When attempting to build F` we are receiving the following error:

![MathTypes](https://user-images.githubusercontent.com/9275528/103162164-ced05a80-47a1-11eb-8270-8cc627ec1fb6.PNG)

We were wondering if anybody else had run into this problem and if so, what a potential solution might be. We're fairly new to F` so any advice is appreciated. Than you.

**Comment by DentOpt** [comment]
Hi @Galatis-Giuliano 
I have the same issue. Can you share your solution?
