### ISSUE TITLE
"fprime-util impl" not working for MathReceiver

### ISSUE THREAD

**Issue by Ruben1729** [nasa/fprime#327]
| | |
|:---|:---|
|**_Python Version_**|3.6.9|
|**_CMake Version_**|3.10.2|
|**_Commit_**|08b535c |
|**_Affected Component_**| MathReceiver  |
---
## Problem Description

I'm trying to run `fprime-util impl` in `/Ref/MathReceiver` but I keep running into this error:

![image](https://user-images.githubusercontent.com/26328810/103983238-e967e380-5152-11eb-9abf-c7eda5f541cb.png)

I checked the folder and it seems to create a `MathReceiverComponentImpl.cpp-template` file but it's empty.

![image](https://user-images.githubusercontent.com/26328810/103984103-811a0180-5154-11eb-8b9c-d671e0b2a12a.png)

Additionally, when using `fprime-util impl` in `/Ref/MathSender` the command keeps generating this line in `/Ref/MathSender/MathSenderComponentImpl.hpp`:

![image](https://user-images.githubusercontent.com/26328810/103983429-3a77d780-5153-11eb-8f77-b5e9e661811b.png)

on line 16.

I was just wondering if this should be `#include "Ref/MathSender/MathSenderComponentImpl.hpp` instead, given `#include "Ref/MathSender/MathSenderComponentAc.hpp` doesn't exist.

## How to Reproduce

I followed the [MathComponent tutorial](https://github.com/nasa/fprime/blob/devel/docs/Tutorials/MathComponent/Tutorial.md). Everything works up to the part where I have to run `fprime-util impl` in the `/Ref/MathReceiver` folder.

## Expected Behavior

The proper generation of `MathReceiverComponentImpl.hpp-template` and `MathReceiverComponentImpl.cpp-template` when running `fprime-util impl`.

**Comment by Joshua-Anderson** [comment]
@Ruben1729 Thanks for letting us know! It should be working now.
