### ISSUE TITLE
Receives [ERROR] Unknown arguments: -b when running ./docs/doxygen/generate_docs.bash

### ISSUE THREAD

**Issue by saba-ja** [nasa/fprime#335]
| | |
|:---|:---|
|**_F´ Version_**| 1.5>=|
|**_Affected Component_**|all   |
---
## Problem Description

Receives [ERROR] Unknown arguments: -b when running:
```./docs/doxygen/generate_docs.bash```

## How to Reproduce
run the following from fprime directory:
```./docs/doxygen/generate_docs.bash```

## Expected Behavior
Generate doxygen and sphinx documents

**Comment by saba-ja** [comment]
## Diagnosis:

The issue is raised from:
docs/doxygen/generate_docs.bash Line 57

![Screen Shot 2021-01-18 at 10 07 47 PM](https://user-images.githubusercontent.com/35859004/105001996-7594c900-59e5-11eb-8da0-c61d1e56bea5.png)

Removing -b argument  does not solve the issue as it gives the following error:

![Screen Shot 2021-01-18 at 10 09 54 PM](https://user-images.githubusercontent.com/35859004/105002097-9b21d280-59e5-11eb-8581-b0204dd8dedc.png)

The new issue is raised from:
Fw/Python/src/fprime/fbuild/builder.py line 258

![Screen Shot 2021-01-18 at 9 56 31 PM](https://user-images.githubusercontent.com/35859004/105002180-b987ce00-59e5-11eb-9580-5a694daecb49.png)

The root cause of the problem is Fw/Python/src/fprime/fbuild/builder.py line 196.
![Screen Shot 2021-01-18 at 9 55 22 PM](https://user-images.githubusercontent.com/35859004/105002248-cd333480-59e5-11eb-938d-f92467bebbb7.png)

"CMAKE_DEFAULT_BUILD_NAME" adds "build-fprime-automatic-" as prefix to the name for build directory. This causes "docs-build-for-docs" which is defined in "docs/doxygen/generate_docs.bash" line 57 be perceived as "build-fprime-automatic-docs-build-for-docs"

The easiest way to resolve the issue is by changing the cmake folder to build-fprime-automatic-docs (Line 53, 54, 64) and use “docs” as argument to fprime-util build (line 57) of docs/doxygen/generate_docs.bash

![Picture11](https://user-images.githubusercontent.com/35859004/105002521-47fc4f80-59e6-11eb-919c-cfb652df3e10.png)

**Comment by LeStarch** [comment]
Your suggested fix looks correct.

**Comment by saba-ja** [comment]
Fixed in #337. The issue is resolved.
