### ISSUE TITLE
Using rules-based testing for the unit tests

### ISSUE THREAD

**Issue by saba-ja** [nasa/fprime#341]
Originally posted by @bocchino in https://github.com/nasa/fprime/pull/283#pullrequestreview-542474363

I suggest using rules-based testing for the unit tests. I have a memory allocator that I wrote for the Autonomy research project that uses rules-based testing.

Consider using a more efficient algorithm for allocation. In the approach suggested below, the allocation time is worst-case linear in the number of bins. The deallocation time is constant.

Use a separate data structure for the bin metadata and for the allocated memory. For the bin metadata, you can have an array of bins. Each bin can store (1) an array of pointers to memory blocks and (2) a size, which is the number of buffers reserved from that bin (initially zero for each bin). The allocated memory can be an array of arrays of memory blocks. On setup, it can look something like this, assuming 2 bins with 6 pointers and 4 pointers:
buffer-manager-1
![image](https://user-images.githubusercontent.com/35859004/105430708-f67fda80-5c08-11eb-8ef2-e0861416277d.png)

To allocate, search the bins to find one that has big enough buffers and has an available buffer. You can use linear search for this. To reserve a buffer from a bin B, (1) use the buffer whose pointer is at the end of the array of pointers in B and (2) increment the number of reserved buffers for B. Here is an example after three allocations from the lower bin. Pointers marked with an X point to reserved buffers. The lower bin has three reserved buffers, so the next allocation from that bin will come from the buffer whose pointer is at index 3 in the bin. The allocation time is constant once a bin with available buffers is found.
![image](https://user-images.githubusercontent.com/35859004/105430725-00a1d900-5c09-11eb-91ba-ce9d3eacb43d.png)

To deallocate a buffer, if the buffer to be deallocated has its pointer at the end of its bin, just decrement the number of reserved buffers for that bin, like this:
buffer-manager-3
![image](https://user-images.githubusercontent.com/35859004/105430732-07305080-5c09-11eb-82a4-0875d9c306b6.png)

If the buffer to be deallocated does not have its pointer at the end of the bin, then swap its pointer with the pointer at the end before decrementing the number of reserved buffers, like this:
buffer-manager-4
![image](https://user-images.githubusercontent.com/35859004/105430737-0c8d9b00-5c09-11eb-9591-5c47ae4b51d9.png)

Another standard approach is to use two linked lists for each bin, an allocated list and a free list. This approach has the same algorithmic complexity as what I sketched above, but I find the code for this approach to be less elegant.

Originally posted by @bocchino in https://github.com/nasa/fprime/pull/283#issuecomment-737471143

Another variant is to use a bounded LIFO queue (stack) of indices for each bin. The max size of each queue is the number of buffers in the bin. The queue stores the array indices of buffers that are available. Initially, each queue is full (it contains one copy of each buffer index). Then allocation is by dequeuing an index and deallocation is by enqueuing an index. You can implement the bounded stack with an array and a size. A bin has buffers available if its size is greater than zero. I think this way is slightly easier than what I described above.

**Comment by LeStarch** [comment]
Added this to the full ticket.  Closing this partial.
