### ISSUE TITLE
It may be a good idea to toggle these telemetry reports on/off via commands.

### ISSUE THREAD

**Issue by saba-ja** [nasa/fprime#342]
_Originally posted by @cruise2coast in https://github.com/nasa/fprime/pull/283#discussion_r533802384_

It may be a good idea to toggle these telemetry reports on/off via commands. By default, these telemetry channels could be turned off and not reported to avoid constantly generating telemetry packets. When needed, these channels can be turned on for reporting via a command. This would help control telemetry packet generation/output especially in radio RF bandwidth constrained environments.

_Originally posted by @bocchino in https://github.com/nasa/fprime/pull/283#discussion_r533863034_

A related issue is that the previous version had a mechanism for suppressing out-of-memory warnings, so repeated requests wouldn't cause spam. I don't think that mechanism has been incorporated here. Maybe add event throttling to that event?

**Comment by LeStarch** [comment]
Added to full clean-up ticket.
