### ISSUE TITLE
Cleaning a subdirectory of a build cache

### ISSUE THREAD

**Issue by bocchino** [nasa/fprime#367]
| | |
|:---|:---|
|**_F´ Version_**| 1.5.3 |
|**_Affected Component_**| All |
---
## Feature Description

It would be helpful to have an `fprime-util clean` capability that cleans just a subdirectory of a build cache.

## Rationale

Due to bugs or quirks in the build, the build environment can get itself into a state where it is impossible to proceed without wiping out build artifacts and starting over. Often it is sufficient to wipe out the artifacts in a particular directory, for example a component unit test directory. Wiping out the entire build cache is inconvenient in this case.

**Comment by Joshua-Anderson** [comment]
Do you know what situations you were in where CMake was got stuck and was unable to properly rebuild a component after modifications? I've hit a few of those cases in the past but I think we've fixed most of the dependency tree issues now (post 1.5 release).

In theory, cmake should never need to be cleaned and should always rebuild properly after modifying C++ and XML files.

The reason I'm bringing this up is I'm trying to figure out what the use case would be for cleaning just a specific component.
Usually in the cases when cmake gets into a stange state it's broken enough that I'm going to want to recreate the entire build cache anyway.

**Comment by bocchino** [comment]
Issues I have encountered in the past include

* Failure to properly re-generate C++ files after modifying XML files.
* Failure to run component unit tests correctly after modifying the component and/or the unit tests.

I think both of these issues have been fixed.

**Comment by LeStarch** [comment]
The core errors have been fixed, and it is unclear what cleaning a subdirectory would entail as CMake doesn't have the notion of a local clean.

**Comment by warkuszmonika** [comment]
> **_F´ Version_**	1.5.3
> **_Affected Component_**	All
> ## Feature Description
> It would be helpful to have an `fprime-util clean` capability that cleans just a subdirectory of a build cache.
> 
> ## Rationale
> Due to bugs or quirks in the build, the build environment can get itself into a state where it is impossible to proceed without wiping out build artifacts and starting over. Often it is sufficient to wipe out the artifacts in a particular directory, for example a component unit test directory. Wiping out the entire build cache is inconvenient in this case.
