### ISSUE TITLE
Code coverage analysis causes unit test failures on Mac OS

### ISSUE THREAD

**Issue by bocchino** [nasa/fprime#368]
| | |
|:---|:---|
|**_F´ Version_**| 1.5.3 |
|**_Affected Component_**| All |
---
## Problem Description

On Mac OS, the following can occur:

1. Build and run component unit tests successfully. Doing this runs code coverage analysis, which generates .gcda artifacts.
2. Edit the component and/or the unit tests.
3. Build and run the component unit tests again, causing the coverage analysis to be re-run. This time the code coverage analysis gets confused by the old .gcda artifacts, causing it to spew warnings and sometimes fail with a segmentation fault.

A workaround is to manually wipe out the .gcda artifacts in the build cache, but this is inconvenient.

## How to Reproduce

Carry out the steps described above, on any component unit test. Do this on Mac OS. For some reason, the issue arises only on Mac OS and not on Linux.

## Expected Behavior

The code coverage analysis should not spew warnings and should not cause segmentation faults or other apparent test failures.

**Comment by gunjanmimo** [comment]
is this problem still open? I am interested to take this one.

**Comment by bocchino** [comment]
Yes, this issue is still open.

**Comment by Joshua-Anderson** [comment]
I think the solution is likely setting up cmake to clear the leftover `gcda` files from previous runs before re-running the test suite with coverage on.
