### ISSUE TITLE
User Guide XML Specifications page does not mention Event throttling 

### ISSUE THREAD

**Issue by gerikkub** [nasa/fprime#413]
| | |
|:---|:---|
|**_F´ Version_**| 1.5 |
|**_Affected Component_**| User Guide  |
---
## Problem Description

The xml-specification pages does not list the "Throttle" Event tag for throttling events.

https://nasa.github.io/fprime/UsersGuide/dev/xml-specification.html

https://github.com/nasa/fprime/blob/9198c47adde61c38d7a6a47a0789f5fba4e3684a/Autocoders/Python/schema/default/event_schema.rng#L62

## How to Reproduce

N/A

## Expected Behavior

The throttle tag should be documented in the XML specifications

**Comment by LeStarch** [comment]
Inprogress
