### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by billallen256** [nasa/fprime#422]
| | |
|:---|:---|
|**_F´ Version_**| current |
|**_Affected Component_**| Autocoder |
---
## Feature Description

Remove work-arounds in the code that are there to support Python 2.

## Rationale

There are some parts of the Autocoder that have work-arounds to support Python 2 and Python 3.  Since Python 2 reached end-of-life at the beginning of 2020, support should be dropped so these work-arounds can be removed.

**Comment by LeStarch** [comment]
We have formally dropped Python 2 support, however; as you have seen we haven't removed all work around.

**Comment by LeStarch** [comment]
We merged the PR here.  I am going to close this.  We can reopen if more are found.
