### ISSUE TITLE
Is this software actually being used?

### ISSUE THREAD

**Issue by robertramey** [nasa/fprime#436]
From the information in this repository, I gather that that this software is being or has been used on actual space flights.  Is this really true?  If that's the case how can there be so many bugs/issues with this software?  This isn't adding up for me.

**Comment by developerfred** [comment]
always have bugs in production :)

**Comment by robertramey** [comment]
Really?  Even for software destined for Mars?  Honestly, this is impossible for me to believe

**Comment by JonJakova** [comment]
Software on which people's life depends on have bugs in them. The Linux kernel on which the world's internet depends on have bugs.
What makes it so hard to believe that this given use case would be bug free?

**Comment by robertramey** [comment]
"What makes it so hard to believe that this given use case would be bug free?"

The potential cost of a bug in this environment is orders of magnitude larger than the cost of of making the software bug free.  There are well known documented cases where these kinds of mistakes in this environment have cost hundreds of millions of dollars. It makes no economic sense to use software with this many bugs for this environment.

As I said, it's unbelievable to me that anyone would find this situation acceptable.

**Comment by LeStarch** [comment]
This is neither a bug nor an enhancement.  Discussions in general should be done on the mailing list. Thus I am closing this ticket.
