### ISSUE TITLE
interface1 is active but does not have async_input port

### ISSUE THREAD

**Issue by billallen256** [nasa/fprime#452]
| | |
|:---|:---|
|**_F´ Version_**| current |
|**_Affected Component_**| Autocoder |
---
## Problem Description

interface1 component is of `kind="active"`:
https://github.com/nasa/fprime/blob/devel/Autocoders/Python/test/interface1/TestComponentAi.xml

However, it does not have an `async_input` port as required by the schematron spec.  In fact it has no ports at all.
https://github.com/nasa/fprime/blob/devel/Autocoders/Python/schema/default/active_comp_schematron.rng

## How to Reproduce

Found by enabling exceptions for schematron validation failures (see #325).

## Expected Behavior

Component should pass schematron validation an gtests.

**Comment by LeStarch** [comment]
This is a problem with the schematron.  This component has an "internal_interface".  The correct schema check is "must have async port or internal interface".

**Comment by LeStarch** [comment]
See #455
