### ISSUE TITLE
fprime-util ignores executable name set by register_fprime_ut()

### ISSUE THREAD

**Issue by saba-ja** [nasa/fprime#466]
| | |
|:---|:---|
|**_F´ Version_**| 1.5 < |
|**_Affected Component_**|  fprime-util |
---
## Problem Description

When running `fprime-util build --ut for Drv/Ip` unit test build fails with the following error:

```bash
-- Build files have been written to: fprime/build-fprime-automatic-native-ut
make: *** No rule to make target `Drv_Ip_ut_exe'.  Stop.
[ERROR] CMake erred with return code 2
```

But when directly run fprime-util check the Ut build and runs successfully. It seems like a bug in the fprime-util build, since it tries to look for the default Drv_Ip_ut_exe, but the Ip UT has two executables shown below:
```Cmake
### UTs ###
set(UT_SOURCE_FILES
                "${CMAKE_CURRENT_LIST_DIR}/test/ut/TestTcp.cpp"
)
register_fprime_ut("Drv_Ip_Tcp_test") <--------
 
set(UT_SOURCE_FILES
                "${CMAKE_CURRENT_LIST_DIR}/test/ut/TestUdp.cpp"
)
register_fprime_ut("Drv_Ip_Udp_test") <--------
```

This error was first found in PR https://github.com/nasa/fprime/pull/460
## How to Reproduce

1. cd fprime/Drv/Ip
2. fprime-util generate --ut
3. fprime-util build --ut

## Expected Behavior

Successfully build the UT

**Comment by LeStarch** [comment]
Likely the cleanest fix would be to register the default name anyway as a shadow target and then make each of the registered UT specific names as dependencies.  That way we'd run all UTs in a dir.
