### ISSUE TITLE
Port with Return Type Not Autocoded Correctly

### ISSUE THREAD

**Issue by brh68** [nasa/fprime#48]
I am trying to make a port that has a return type, and have put the return type in the port definition XML.  However, when I make a component that uses this port and should return a value, the impl files are generated with the associated function having a return type of void.  This causes the compile error below when I rebuild, and makes sense since there doesn't seem to be a way signify a return type in component XML.
![ReturnTypeMismatchError](https://user-images.githubusercontent.com/47760444/59150785-2314bd80-89f7-11e9-9c3b-3cac40169652.JPG)
Do I have to manually chance the return types of the Impl files, or is there something else I can do to fix this through the autocoder?

**Comment by timcanham** [comment]
What type of port did you define it as? (sycn, async, guarded?)

**Comment by brh68** [comment]
Synchronous Input

**Comment by brh68** [comment]
I put it in a repository after moving things around, so the errors have changed slightly:
![returnTypeError](https://user-images.githubusercontent.com/47760444/59218267-d8797980-8b8d-11e9-9da4-faecdfbaf979.JPG)
Here is the repository:
https://github.com/brh68/Cislunar-Flight-Software/tree/peripherals

**Comment by LeStarch** [comment]
Did you remake `make impl` and then copy over the new template files?

**Comment by brh68** [comment]
The problem remains after I rerun `make impl`.

**Comment by brh68** [comment]
I manually changed the return types of the functions in the impl files, which seems to work.

**Comment by LeStarch** [comment]
We'll still need to test for this bug before closing out the issue.  Thanks for the report.

**Comment by LeStarch** [comment]
Reviewing this issue, this is expected behavior.

We don't automatically update the impl files, as we do not want to clobber outstanding work that the user has done.

Once the implementation generator is run, the user owns the files and must manually update or manually regenerate (and move from the _template outputs).
