### ISSUE TITLE
identical condition

### ISSUE THREAD

**Issue by maddin200** [nasa/fprime#497]
[/Drv/SocketIpDriver/SocketHelper.cpp line 231

Code:
  // Error is EINTR, just try again
            if (sent == -1 && errno == EINTR) { // <-- identical
                continue;
            }
            // Error bad file descriptor is a close
            else if (sent == -1 && errno == EBADF) {
                Fw::Logger::logMsg("[ERROR] Server disconnected\n");
                this->close();
                this->m_socketOutFd = -1;
                break;
            }
            // Error returned, and it wasn't an interrupt
            else if (sent == -1 && errno == EINTR)  {   // <-- identical
                Fw::Logger::logMsg("[ERROR] IP send failed ERRNO: %d UDP: %d\n", errno, m_sendUdp);
                break;
            }

**Comment by Joshua-Anderson** [comment]
Fixed in #497. Thanks!
