### ISSUE TITLE
Cornell Comments

### ISSUE THREAD

**Issue by timcanham** [nasa/fprime#5]
•	Change "requirement.txt" to "required.txt" because that's what the actual file is named.
•	I had to manually install a few things not listed in the guide, but maybe the packages.sh file would have done that automatically.
•	Even though it tries to install lxml automatically, this hangs and doesn't appear to work. I had to do it manually and remove lxml from the required.txt to get it to proceed.
•	The demo is in "scripts" not "script".

**Comment by harryharpel** [comment]
Hi, I'm a member of the Cornell CisLunar Explorers team. Is there an example repo of a CubeSat that implements fprime or any additional resources that JPL can provide to help members of the team learn more about fprime? Thanks!

**Comment by ljreder** [comment]
There is a Ref example that comes with fprime.   There are not any open source cubesat examples that I know of.   This summer we will have a student potentially working on porting a balloon payload which is going to be come a Cubesat deployment.  If it happens I have agreement that this example will be open source but that will not be until the summer.  Perhaps email this question to fprime@jpl.nasa.gov for special consideration.

**Comment by harryharpel** [comment]
When writing the xml file for a port is String an accepted type? The make make_gen and make commands are generating the appropriate files with no errors when I make the type of my argument an F32 but errors are generated when I make the type= "String". Any help would be greatly appreciated!

<img width="1356" alt="Screen Shot 2019-03-13 at 7 47 01 PM" src="https://user-images.githubusercontent.com/11217270/54321888-3f0bed00-45c9-11e9-9068-f157f3f80d5b.png">

**Comment by timcanham** [comment]
Use `string` with no caps, and a `size` attribute to define the length of the string. See `Autocoders/test/string_port` for an example.

**Comment by harryharpel** [comment]
Thanks! That fixed the problem

**Comment by LeStarch** [comment]
I am closing this issue, as I see no updates.  Please feel free to continue discussion on our mailing list:  https://groups.google.com/forum/#!forum/fprime-community

Or open a new issue if you detect a new bug.
