### ISSUE TITLE
build errors using make gen_make

### ISSUE THREAD

**Issue by wr3484** [nasa/fprime#51]
I am having trouble with a gps component we are trying to create, the make gen_make command is providing an error that I cannot figure out. This is the error obtained:
![makeGenError](https://user-images.githubusercontent.com/48264496/59224172-c30b4c00-8b9b-11e9-95a2-a3efb2daaf49.png)

My code does not even reference the svc directory so I am not really sure how to fix that.

Here is the makefile for it:
![makefilePhoto](https://user-images.githubusercontent.com/48264496/59224356-31500e80-8b9c-11e9-854c-f71790034d05.png)

**Comment by LeStarch** [comment]
It looks like "BufferAccumulator" is referenced in your `mk/configs/modules/modules.mk` file.  Which branch did you start from?  Are you on the latest NASA devel?

**Comment by wr3484** [comment]
We are working on a side project incorporating fprime into a weather balloon, simple ideas, gps, etc.  I scrapped the previous idea, made a clone of fprime directly and copied our Balloon file into the fprime directory. The `make gen_make`  worked, but when I actually try to build using the `make` command, there is a strange error about Linux. Any suggestions? 

![Balloon Error](https://user-images.githubusercontent.com/48264496/60748800-a9bdab80-9f5f-11e9-84a2-9264e14ea0fd.png)

**Comment by LeStarch** [comment]
Is this compiling a Topology? If so, make sure you have defined a `main` function.

**Comment by wr3484** [comment]
It is compiling a topology and we do have a main function. It builds on a separate computer running a VM, but I am attempting to build through a Linux operating system. 

![s1](https://user-images.githubusercontent.com/48264496/60829852-ebc73700-a183-11e9-9420-4fccddfa02d3.png)
![s2](https://user-images.githubusercontent.com/48264496/60829859-f08beb00-a183-11e9-8487-bf914088a151.png)

**Comment by LeStarch** [comment]
Have you ensured that the "Topology.cpp" is in your mod.mk file, and that you have refreshed with `make gen_make`?

**Comment by wr3484** [comment]
Yes, it is included in the mod.mk file and refreshed with a `make gen_make`

![s3](https://user-images.githubusercontent.com/48264496/60836433-a7439780-a193-11e9-8263-b08972dcc736.png)

**Comment by LeStarch** [comment]
Checkout the new CMake build system.

I am closing this issue, as I see no updates.  Please feel free to continue discussion on our mailing list:  https://groups.google.com/forum/#!forum/fprime-community

Or open a new issue if you detect a new bug.
