### ISSUE TITLE
Settings.ini Change Detection

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#517]
| | |
|:---|:---|
|**_F´ Version_**| 1.5.3 |
|**_Affected Component_**|  fprime-util |
---
## Feature Description

The settings.ini file (should it change) should invalidate the CMAKE cache as its itmes are critical.

## Rationale

A settings.ini change is the only thing that should force a new `fprime-util generate` command.

**Comment by Joshua-Anderson** [comment]
@LeStarch I have some time this week and I'm guessing you haven't started this yet so I'm going to steal it 😄
