### ISSUE TITLE
Devel Failing Check --all

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#525]
| | |
|:---|:---|
|**_F´ Version_**| devel |
|**_Affected Component_**|   |
---
## Problem Description

Devel seems to be failing check all since yesterday.  Investigating.

**Comment by saba-ja** [comment]
Ran `check --all` on current devel (222048e679), with no issue.
![image](https://user-images.githubusercontent.com/35859004/117338689-b6f59b00-ae53-11eb-9418-de48946f5684.png)

The fail could be isolated to one of the pending PRs.

**Comment by LeStarch** [comment]
@saba-ja it appears to be a transient issue.  I checked `check --all` locally and reran the jobs on GitHub and both are passing.
