### ISSUE TITLE
Add "F Prime" To Main Page

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#526]
| | |
|:---|:---|
|**_F´ Version_**| docs |
|**_Affected Component_**| docs  |
---
## Feature Description

Need to add "F Prime" as an alternate name for F´ to the main page.

## Rationale

F Prime is an acceptable alternate name and should be indicated on our landing page.

**Comment by ThibFrgsGmz** [comment]
Is there anything left to do since the addition was merged?

**Comment by LeStarch** [comment]
Nope.
