### ISSUE TITLE
Add command  XML comment field to GDS

### ISSUE THREAD

**Issue by metzdigital** [nasa/fprime#535]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

As a way to help users understand the functionality of a particular command it would be nice to add the text from the commands XML <comment> field to the GDS interface. 

Example:
A command entry like this:
```
<command kind="guarded" opcode="3" mnemonic="xHWx_FREQUENCY">
    <comment>
        Set the excitation frequency, specified in kHz, 100kHz to 1000kHz
    </comment>
    <args>
        <arg type="F32" name="freq"> </arg>
    </args>
</command>
```
Would generate something like this:
![image](https://user-images.githubusercontent.com/2592986/117730330-07952d00-b1a1-11eb-9a52-bfaa248c7253.png)

## Rationale

A rationale for why the feature should be implemented in F´.

Gives the user a better understanding of the commands they are sending.

**Comment by LeStarch** [comment]
Done.  Woooooooooooooo!
