### ISSUE TITLE
Include External Libraries in Make

### ISSUE THREAD

**Issue by TizzC** [nasa/fprime#58]
Hello,

I'm attempting to build a component where I need to include external headers (Placed in a different directory, where I could ideally do a `-I` and include that directory in my compile) and include a different library at the linking stage of my project. Is there a simple way to integrate this into the Makefile?

**Comment by timcanham** [comment]
If you are compiling natively for Linux, you can modify the make configuration files as follows:

`/mk/configs/compiler/linux_gnu_common.mk`:

Add your library to `LINK_LIBS`.
Add your include path to `LINUX_GNU_INCLUDES`

This will add the include path to all the compiled code.
