### ISSUE TITLE
Error when issuing 'make rebuild' in Math Component Tutorial

### ISSUE THREAD

**Issue by ecruz480** [nasa/fprime#60]
When trying to build the `MathSender` component, I keep running into the same error when issuing the `make rebuild` command within the `Ref` directory. I have check the `mod.mk` file in the `configs/modules` folder and tried rearranging the module order under `REF_MODULES :=\`. Any help is appreciated.

![fprime error](https://user-images.githubusercontent.com/6435014/61999971-ab235500-b081-11e9-8e46-26e9259aa2fa.png)

**Comment by timcanham** [comment]
It looks like there is something incorrect in the `MathSenderComponentAi.xml`. Check it against the reference copy in `docs/Tutorials/MathComponent/MathSender/MathSenderComponentAi.xml`.

**Comment by ecruz480** [comment]
Hm, I must of missed something small, works fine now. Thank you!
