### ISSUE TITLE
Adding Compile Commands to make system

### ISSUE THREAD

**Issue by brh68** [nasa/fprime#61]
As part of our software, we are using a library called WiringPi, and in order to compile those files the compilier must be given the flag `-lwiringPi`.  How can we add this flag to the make system so that it will be able to successfully compile our drivers?
Ex:
![-lwiringPi](https://user-images.githubusercontent.com/47760444/62266011-879b3a00-b3f4-11e9-84eb-f819a15d113d.JPG)

**Comment by timcanham** [comment]
You can add `-lwiringPi` to this line: https://github.com/nasa/fprime/blob/master/mk/configs/compiler/raspian_gnu_common.mk#L28

**Comment by brh68** [comment]
I got is to that a `make rebuild` command will compile successfully, but the `make rebuild_rpi_cross` command gives a `no such file or directory #include <wiringPi.h>`, which is strange since the normal rebuild is able to find it.  Is there a certain place it needs to be installed, because I currently have WiringPi in my VM's home directory.

**Comment by brh68** [comment]
I installed WiringPi in the same directory as the cross compile tools and it works, is this the correct way to do it?

**Comment by timcanham** [comment]
That's one way, or you can put the wiringPi in `/opt` somewhere and add the include path here:

https://github.com/nasa/fprime/blob/master/mk/configs/compiler/raspian_gnu_common.mk#L45

It's better to keep the compile tools and wiringPi disentangled.

**Comment by brh68** [comment]
I'm not sure how to add the path, Im not familiar with the syntax of makefiles

**Comment by brh68** [comment]
![MultipleFIleError](https://user-images.githubusercontent.com/47760444/62325867-b2c86c80-b47a-11e9-87cc-432596a81a03.JPG)

**Comment by brh68** [comment]
Im not sure how to correct the above error

**Comment by timcanham** [comment]
Add a `-I` to the beginning of the `/opt/` path you've added.

**Comment by brh68** [comment]
Earlier when I thought it worked, I actually had just ran `make rebuild`, so I haven't gotten `make rebuild_rpi_cross`.  After adding `-I`, it can't find the file that I specifically included.
![raspianMK](https://user-images.githubusercontent.com/47760444/62433730-a4d94c80-b703-11e9-86f9-56c8787ec21b.JPG)
![with-I](https://user-images.githubusercontent.com/47760444/62433731-a4d94c80-b703-11e9-9868-4624772e6067.JPG)

**Comment by timcanham** [comment]
Sorry, my bad: `-I/opt/tools/rpi/WiringPi/wiringPi` Then your include should work.

**Comment by brh68** [comment]
That fixed the include problem, but now it is acting like wiringPi isn't installed, so I think the cross compiler can't tell it is installed on the VM, and I'm not sure how to correct this.
![cannotFindlwiringPi](https://user-images.githubusercontent.com/47760444/62484668-af89f500-b788-11e9-9488-a464dbd577c6.JPG)

**Comment by LeStarch** [comment]
I am closing this issue, as I see no updates.  Please feel free to continue discussion on our mailing list:  https://groups.google.com/forum/#!forum/fprime-community

Or open a new issue if you detect a new bug.
