### ISSUE TITLE
Adding more detail on cross compiling for math component tutorial. 

### ISSUE THREAD

**Issue by rawinza555** [nasa/fprime#667]
| | |
|:---|:---|
|**_F´ Version_**|devel |
|**_Affected Component_**|Math Components Tutorials  |
---
## Feature Description

Expand the math components more on the deploying to RPI or any other board. Basically, have something similar to cross compile section in R Pi tutorial but for math components.

## Rationale

From a newbie perspective, it's easier to understand how to run a GDS on host machine to interact with R Pi with more simple example like math components. It's more likely for people to have a R Pi or other SBC lying around than having that and a GPS module. A GPS module tutorial can then be focused for learning on hardware interaction.

**Comment by LeStarch** [comment]
This was done!
