### ISSUE TITLE
Cleaning up Unit Test folders

### ISSUE THREAD

**Issue by saba-ja** [nasa/fprime#689]
| | |
|:---|:---|
|**_F´ Version_**| 1.5 |
|**_Affected Component_**| All  |
---
## Problem Description

Unit test folders currently contain old binary executable UT files, old R&D checklists, and Google test suite files, gcov files, and old make files.
This ticket will be used to track the subsequent PRs cleaning up UT folders.

## How to Reproduce
To list binary files run `find . -type f -name runtest_*`
To list gcov files run `find . -type f -name *.gcov`
etc.

## Expected Behavior
With the new fprime-util tool there is no need to keep the old executable files or include Google test suite files.

**Comment by AdvaitDhingra** [comment]
Are there any more outdated ut test files to remove?
