### ISSUE TITLE
Issue with using Fw::Buffer

### ISSUE THREAD

**Issue by aaronbuchwald** [nasa/fprime#69]
I am getting some issues when using a U8 array with the Fw::Buffer. It says that it cannot convert from U8 to U64. I thought that Fw::Buffer would be a buffer of bytes and therefore should use U8, additionally this seems to be the way that @timcanham uses it in the RobotArm tutorial for the i2c component, so I assume there's a way to use it this way. Here's a screenshot of the error and my fork is at https://github.com/aaronbuchwald/fprime on the branch i2c-driver.

**Comment by aaronbuchwald** [comment]
<img width="1092" alt="Screen Shot 2019-08-30 at 9 38 02 PM" src="https://user-images.githubusercontent.com/24684335/64057734-b846ce80-cb6e-11e9-9c7d-0d7259ee1828.png">

**Comment by aaronbuchwald** [comment]
<img width="1092" alt="Screen Shot 2019-08-30 at 9 38 02 PM" src="https://user-images.githubusercontent.com/24684335/64057799-8c781880-cb6f-11e9-84b1-1d9acebe8c21.png">

**Comment by timcanham** [comment]
@aaronbuchwald Because there is a conversion from a pointer type (`U8*`) to the data member of `Fw::Buffer`, you need a cast of `data` to `U64`. Try:

```c++
dataBuffer.setdata(static_cast<U64>(data));
```

**Comment by aaronbuchwald** [comment]
<img width="1086" alt="Screen Shot 2019-09-03 at 1 40 56 AM" src="https://user-images.githubusercontent.com/24684335/64146686-ebe25c80-cdeb-11e9-80bc-d2d65bad5c41.png">

**Comment by aaronbuchwald** [comment]
I got past this, but now there is a number of undefined reference errors in auto-generated files. Do you know what might cause this behavior?

**Comment by aaronbuchwald** [comment]
<img width="1086" alt="Screen Shot 2019-09-03 at 1 40 56 AM" src="https://user-images.githubusercontent.com/24684335/64585802-1db56f00-d368-11e9-90da-ccb31bd3c3d5.png">

**Comment by aaronbuchwald** [comment]
<img width="1097" alt="Screen Shot 2019-09-10 at 1 10 47 AM" src="https://user-images.githubusercontent.com/24684335/64585816-2efe7b80-d368-11e9-8727-babb40952801.png">

**Comment by aaronbuchwald** [comment]
Still working on the same branch as I referenced before

**Comment by timcanham** [comment]
@aaronbuchwald Make sure that all the directories with the code you need are in the `LinuxI2CDriver/test/ut/mod.mk` file. You are probably missing some.
