### ISSUE TITLE
CMake System is not dependent on AcConstants.ini

### ISSUE THREAD

**Issue by pelmini** [nasa/fprime#71]
After editing AcConstant.ini CMake did not detect the change in the file.

**Comment by LeStarch** [comment]
Affects `cmake` system.  Work around is to regenerate cmake build from scratch.

**Comment by LeStarch** [comment]
Current work around: delete CMake build directory and start over.

**Comment by LeStarch** [comment]
Still broken, prioritizing fix.

**Comment by LeStarch** [comment]
Fixed.
