### ISSUE TITLE
implgen.py error

### ISSUE THREAD

**Issue by kmanchikanti** [nasa/fprime#74]
When I was trying to run implgen.py to generate a template for a port, it gave me an error like this:

"ERROR: Invalid XML found...this format not supported"

This error message is hard to understand, could it be changed to something more helpful, like implgen.py is not used to generate templates for ports, but rather for components

**Comment by LeStarch** [comment]
Agreed.  Thanks for the report.

**Comment by SterlingPeet** [comment]
looks like the ticket didn't close itself

**Comment by LeStarch** [comment]
I think this will close when the PR is merged.

**Comment by LeStarch** [comment]
...odd that didn't happen.
