### ISSUE TITLE
Ref example has no Main.cpp file

### ISSUE THREAD

**Issue by SterlingPeet** [nasa/fprime#75]
I was reading the instructions for creating a new F Prime deployment in the community documentation, and it mentions having a ``Main.cpp`` file in the ``Top`` folder.  Because I wanted to do this for a _new_ bare-metal system, I went to look at the ``Ref`` example to see how it was implemented, but there is no file here!

**Comment by LeStarch** [comment]
This is slated to be fixed.

**Comment by SterlingPeet** [comment]
Is this officially fixed now?

**Comment by LeStarch** [comment]
Yes!  Closing.
