### ISSUE TITLE
PrmBuffer m_data VxWorks issue

### ISSUE THREAD

**Issue by timcanham** [nasa/fprime#796]
| | |
|:---|:---|
|**_F´ Version_**| 2.0|
|**_Affected Component_**|   |
---
## Problem Description

The `m_data` member variable collides with the notorious `m_data` macro for VxWorks. Change the name of the data member to avoid the collision.

## How to Reproduce

1. Any VxWorks build

## Expected Behavior

Should compile fine under Vxworks

**Comment by LeStarch** [comment]
This was fixed in the vx works PR
