### ISSUE TITLE
Topology File generates even with missing imports and instances

### ISSUE THREAD

**Issue by timcanham** [nasa/fprime#802]
| | |
|:---|:---|
|**_F´ Version_**|2.0.0 |
|**_Affected Component_**| n/a  |
---
## Problem Description

A component instance can be used in a topology without an import statement or an instance declared.

## How to Reproduce

For example, in `Ref/Top/RefTopologyAi.xml`:

1\. Remove:

```xml
    <import_component_type>Svc/BufferManager/BufferManagerComponentAi.xml</import_component_type>
```

2\. Remove:

```xml
    <instance namespace="Svc" name="fileUplinkBufferManager" type="BufferManager" base_id="301"  base_id_window="20" />

```

3\. Build deployment. No errors are emitted. The `fileUplinkBufferManager` connections are there and it compiles correctly. Sometimes it can cause cmake to fail to detect the component type as a dependency and you get compiler errors due to missing generated headers.

## Expected Behavior

I would expect an error from the autocoder for missing import statements or instance declarations. There is no `setIdBase()` call made, which would cause issues if the component had ground system items. For `BufferManager` this isn't an issue.

**Comment by LeStarch** [comment]
FPP should be used at this time.  Closing this issue.
