### ISSUE TITLE
Inconsistency in Modeler specification

### ISSUE THREAD

**Issue by alex-brinkman** [nasa/fprime#820]
| | |
|:---|:---|
|**_F´ Version_**| all |
|**_Affected Component_**|  documentation  |
---
## Problem Description

I found the entry for `modeler` is inconsistent. This is low-impact but will be beneficial to get right.

https://github.com/nasa/fprime/blob/5dcbb5c322fa6f26e3d97826289d9aa47e2043ea/docs/UsersGuide/dev/xml-specification.md#components

**Comment by LeStarch** [comment]
It looks right to me.  If you can elaborate on the inconsistency, we can fix it.
