### ISSUE TITLE
Update GDS User Guide to reflect Flask server IP/port

### ISSUE THREAD

**Issue by Gregox273** [nasa/fprime#829]
The User Guide: 
https://nasa.github.io/fprime/UsersGuide/gds/gds-introduction.html#specify-gds-addresses-and-ports 
indicates that 0.0.0.0 is the default address for all GDS communications. However the UI port (Flask server) defaults to 127.0.0.1, so must be explicity told, via the --gui-addr option, to use 0.0.0.0 if that behaviour is desired e.g. to listen on all interfaces when running within a container. 

Could/should the documentation be updated to indicate this subtlety and/or with the new options introduced in #489 ?

**Comment by LeStarch** [comment]
Yes we should update the documentation to include this subtlety and to include the new options provided.
