### ISSUE TITLE
Telemetry Port/Channel Autocoder Bug

### ISSUE THREAD

**Issue by jweadick** [nasa/fprime#835]
| | |
|:---|:---|
|**2.0**| |
|**Autocoder**|   |
---
## Problem Description

Currently, components with a telemetry port but no telemetry channels will build, but the unit test build will fail.

## How to Reproduce

1. On a throwaway branch, navigate to any component without telemetry channels (I used Svc/ActiveTextLogger) and add `<import_port_type>Fw/Tlm/TlmPortAi.xml</import_port_type>` to the ActiveLoggerComponentAi.xml file. Additionally, add the telemetry port to the XML with the following line: 
`<port name="Tlm" data_type="Fw::Tlm" kind="output" role="Telemetry" max_number="1"/>`
2. Use fprime-util build
3. Use fprime-util build -ut and the bug should occur

## Expected Behavior

fprime-util build should either fail or warn the user that they have not specified telemetry channels for their telemetry port

**Comment by LeStarch** [comment]
FPP should supersede this.
