### ISSUE TITLE
getting-started.md: GpsApp modules.mk file incorrect reference

### ISSUE THREAD

**Issue by DKlaren** [nasa/fprime#85]
In the getting-started.md file the GpsApp tutorial when it tells you to make the modules.mk file it specifies to input:

GpsApp_MODULES := \
    ...
    $(DRV_MODULES) \
    ...

However DRV_MODULES does not exist and must be changed to DEMO_DRV_MODULES to compile.

**Comment by LeStarch** [comment]
This document has been entirely rewritten to use CMake as opposed to the heritage make system.
