### ISSUE TITLE
Os unit test fails intermittently on Mac OS X

### ISSUE THREAD

**Issue by bocchino** [nasa/fprime#856]
| | |
|:---|:---|
|**_F´ Version_**| v3.0.0 |
|**_Affected Component_**| N/A  |
---
## Problem Description

When I run the Os unit tests, on my Mac (MacBook Pro, Mac OS 10.15.1), I get this:
```
1: [ RUN      ] Nominal.IntervalTimerTest
1: /Users/bocchino/JPL/Tools/FPrime/bocchino/fprime/Os/test/ut/IntervalTimerTest.cpp:16: Failure
1: Expected: (timer.getDiffUsec()) < (1005000), actual: 9011207 vs 1005000
1: [  FAILED  ] Nominal.IntervalTimerTest (9011 ms)
```

## How to Reproduce

Run the Os unit tests. The behavior is intermittent; sometimes everything passes.

## Expected Behavior

The tests should pass.

**Comment by Joshua-Anderson** [comment]
I've encountered this as well, I'll take a look at it this afternoon.

**Comment by LeStarch** [comment]
This was fixed....OS "feature" that prevents this test working correctly.  Disabled on OSX
