### ISSUE TITLE
MagicDraw Plug-In Topology Generation Failure

### ISSUE THREAD

**Issue by TrentRich1997** [nasa/fprime#86]
Component Autocoder works well except when generating Topology XML files. The topology XML is created but is blank and MagicDraw reports the error below.

"Problem with getting Plugin Resource: Failed to initialize an instance of org.apache.velocity.runtime.log.Log4JLogChute with the current runtime configuration."

**Comment by LeStarch** [comment]
Sorry about the late reply.

This is typically caused by lack of permission when writing the velocity.log file as a library supporting MagicDraw.

If you still have issues, please reopen this ticket.
