### ISSUE TITLE
Better reporting from comLogger of file names

### ISSUE THREAD

**Issue by metzdigital** [nasa/fprime#898]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

When starting / closing file / stopping record you never get an indication of what the file name is. Example:
![image](https://user-images.githubusercontent.com/2592986/128460016-dabc846a-40b4-45ee-b6bd-32a6886170f7.png)

Activity low EVRs should be produced at each step so its clear what the file name is during each of these operations.

**Comment by LeStarch** [comment]
Closing this.  This was implemented in a custom comLogger on the source project.
