### ISSUE TITLE
Remove duplicate component imports in Ref/Top/RefToplogyAppAi.xml

### ISSUE THREAD

**Issue by timcanham** [nasa/fprime#909]
| | |
|:---|:---|
|**_F´ Version_**| 2.0 |
|**_Affected Component_**| None  |
---
## Problem Description

There are duplicate xml imports of components.

## How to Reproduce

In `Ref/Top/RefTopologyAi.xml`, the following imports are duplicated:

```
    <import_component_type>Svc/ActiveRateGroup/ActiveRateGroupComponentAi.xml</import_component_type>
    <import_component_type>Ref/SignalGen/SignalGenComponentAi.xml</import_component_type>
    <import_component_type>Svc/BufferManager/BufferManagerComponentAi.xml</import_component_type>
```

## Expected Behavior

A single import of each.

**Comment by LeStarch** [comment]
Looks like it was fixed!
