### ISSUE TITLE
Add equality operator for external enum enumerators.

### ISSUE THREAD

**Issue by timcanham** [nasa/fprime#933]
| | |
|:---|:---|
|**_F´ Version_**| 2.0 |
|**_Affected Component_**| None |
---
## Feature Description

Add an additional equality operator in the enum class for checking values.

They currently have:

```c++
    //! Equality operator
    bool operator==(
        const SomeEnum& other //!< The other object
        ) const;
```

This makes a test be:

```c++
SomeNamespace::SomeEnum x;

if (SomeNamespace::SomeEnum::SomeEnumerator == x.e) {
// do something
}
````

It would be simpler and more natural to do:

```c++
SomeNamespace::SomeEnum x;

if (SomeNamespace::SomeEnum::SomeEnumerator == x) {
// do something
}
````

Add an operator like this:

```c++
    //! Equality operator
    bool operator==(
        const SomeEnum::t& other //!< The other object
        ) const;
```

## Rationale

Coding would easier and more intuitive since the check is really for the enumeration.

**Comment by LeStarch** [comment]
This is done in the new enum autocoder.
