### ISSUE TITLE
Autogenerate separate `Tester::connectPorts` source file

### ISSUE THREAD

**Issue by timcanham** [nasa/fprime#934]
| | |
|:---|:---|
|**_F´ Version_**|2.0 |
|**_Affected Component_**|  |
---
## Feature Description

Currently, `Tester::connectPorts()` is generated by the `generate impl --ut` and placed in the `Tester.cpp` file. This becomes a maintenance annoyance and causes asserts if it's not corrected if a new port is added.

The proposal would be to generate this function into a separate .cpp file that would be treated like the other unit test files and generated each time the test is compiled. 

## Rationale

It makes maintaining unit tests a lot easier, and it isn't intuitive to know you have to go update this function when you add a port.

**Comment by LeStarch** [comment]
If we are going to fix this, we need to make sure the `for` connections for port arrays use non-hardcoded values.  I often have to rewrite these methods by hand to fix that oversight.

**Comment by timcanham** [comment]
What do you mean by `for` connections?

**Comment by LeStarch** [comment]
When you have an array port, it makes  a for loop:

```
for (i = 0; i < 3; i++) {
   //connect port @ i
}
```

However, instead of using the constant depicting the array size, it uses a hardcoded integer.  If one changes AcConstants.ini or that port size, this hardcoded int needs to be updated to.

**Comment by timcanham** [comment]
If the ut code is regenerated, does the port size get updated?

**Comment by LeStarch** [comment]
@timcanham would we be able to override this autocode?  Occasionally we need to override it.

e.g. for the hub unit tests, we create 2 hubs and cross-wire them together to proved that the outside interfaces of the hubs work in tandem.

**Comment by timcanham** [comment]
Since the connection functions are always re-callable, you can re-connect any way you like. You could also just comment out the call to `connectPorts()` from the `Tester` constructor.
