### ISSUE TITLE
broken links in user guide

### ISSUE THREAD

**Issue by gkieszkowski** [nasa/fprime#942]
In [user guide ](https://github.com/nasa/fprime/blob/devel/docs/UsersGuide/guide.md)we have 3 broken links in API documentation:
- https://github.com/nasa/fprime/blob/devel/docs/UsersGuide/api/c++/html/index.html
- https://github.com/nasa/fprime/blob/devel/docs/UsersGuide/api/python/fprime/html/index.html
- https://github.com/nasa/fprime/blob/devel/docs/UsersGuide/api/python/fprime-gds/html/index.html

I tried to find them to fix issue right away but they seem to be relocated or deleted.

**Comment by LeStarch** [comment]
We cannot really fix these items, as they refer to autogenerated documentation which is filled in elsewhere.  The last two are fixed, but the C++ one need to be there for the hosted-webpage.
