### ISSUE TITLE
Error running demo (Ubuntu 16.04)

### ISSUE THREAD

**Issue by abbiejlee** [nasa/fprime#98]
Hi,

I'm part of a small satellite design class at MIT this semester, and we are testing out F' to use with our system. I have been trying to run the demo script, and everything has built to completion, but when I go execute Ref/scripts/run_ref.sh, the GUI opens for about 10 seconds, then closes with
``[ERROR] Failed to start Ref Application ``

after make gnome-terminal Warnings similar to 
``(gnome-terminal.real:61438): Gtk-WARNING **: Theme parsing error: unity-greeter.css:59:22: The :focused pseudo-class is deprecated. Use :focus instead.``

I'm also not seeing the second window referenced by "Another window will show the standard output of the reference application" in the guide. I've looked through the output, and there aren't any error messages, just warnings, so I'm not sure what's causing the process to fail.

Any help would be appreciated. Thanks!

**Comment by LeStarch** [comment]
First, apologies for not responding to this sooner, it slipped past my radar.

Your specific issue looks like a problem with our old shell-runner used to capture Ref output.

In the latest F´ we have shipped a new HTML based GUI that should avoid these shell inconsistencies.

Take a look at our top-level README.md, it will walk through installs and setup of project using this new GUI.

I will close this ticket for now, but if you continue running into issues, don't hesitate to reopen or post a new issue.
